### ISSUE TITLE
Err before starting invalid services

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1291] opened 2017-01-26 20:56 UTC
Even if the data referenced in a job specification for a service does not exist, Pachyderm will still try to create the service.  This will obviously create a confusing situation.  The commit referenced in a specification could be completely phony and yet Pachyderm will still try to create the service.

@sjezewski and I think that we should check that the referenced commits exist and error if it does not.

**Comment by jdoliner** [comment] 2019-06-20 00:27
I believe this is now fixed because we need to create subvenance references in the inputs when we create the pipeline (or service). It is possible to reference branches that don't exist, but that's by design and creates the branches, you can't references repos that don't exist and you can't reference commits directly at all.

**Closed by jdoliner** 2019-06-20 00:27 UTC
Labels: help wanted
