### ISSUE TITLE
Manual cron tick doesn't backfill past ticks that were missed

### ISSUE THREAD

**Issue by adelelopez** [pachyderm/pachyderm#5276] opened 2020-09-18 19:59 UTC
**What happened?**:
We created a pipeline with a cron input that was set to start several days into the past, and scheduled to run once per day. 
It didn't create any new ticks immediately.

**What you expected to happen?**:
We expected it to create ticks for each day since the start time, but it didn't.

**Comment by JoeyZwicker** [comment] 2020-09-27 04:31
@pappasilenus @mindthevirt Based on conversation in last on-call handoff, I think we decided support team was going to confirm/repro and confirm a few different behaviors. Specifically:
- Does this behave differently if the pipeline is in standby or not?
- Does it wait for the next tick and then create all "catch up" ticks at that point? 

Note that this may only present when updating a cron pipeline with a start time in the past different than creating a new cron pipeline. Once we understand the exact behavior we're seeing I think the behavior we want is:

- Regardless of standby, updating the start time or any start time in the past should create all missing ticks.
- Adding a new tick file manually in the past should run that single tick, but should catch up for every time between then and now. I think the implementation current looks at the latest tick file and catches up from there, which may not be the best design. This is still an open-ended design discussion as well as implementation.

**Comment by jdoliner** [comment] 2020-11-30 22:00
I just tested this and it seems to be working correctly. Setting a start time causes the pipeline to backfill previous ticks when the pipeline is created. Closing this since afaict this is working as designed and the design is correct.

**Closed by jdoliner** 2020-11-30 22:00 UTC
Labels: bug, user
