### ISSUE TITLE
Custom Image Location in AWS Pachyderm

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#791] opened 2016-09-07 07:28 UTC
## Fundamental Environment

For an AWS Kubernetes 1.3.4 with 4 minor nodes and 1 master node. Pachyderm 1.1.0. 
## Stuck in PULL state when starting a pipeline

The pipeline run well when I use the `job-shim` image. But when it comes to the custom image built by user self, the pachyderm is stuck into PULL state and fails to run the computation task.
The Pachyderm job is shown as following,

```
ccf4c09c9559869618c7076098e9506d   wordcount_map/a023b1bbf96f4a92b16adba27123b558     34 minutes ago      -                   pulling
98524403fd504b449c777bcc6ab0651c   wordcount_input/5fce35bf56414dab91b39e84fc1dd95d   34 minutes ago      23 seconds          success
8000b9b4cbe460b0cc91469103616831   filter/2597cbbe54b64f27a6b04ab9af236cd2            About an hour ago   7 seconds           success
```

Pachyderm Log for the pulling container is 

```
pachctl get-logs ccf4c09c9559869618c7076098e9506d
container "user" in pod "ccf4c09c9559869618c7076098e9506d-psi4n" is waiting to start: image can't be pulled
```

Kubernetes log for the pulling pods is 

```
kubectl logs ccf4c09c9559869618c7076098e9506d-psi4n
Error from server: container "user" in pod "ccf4c09c9559869618c7076098e9506d-psi4n" is waiting to start: trying and failing to pull image
```

Kubernetes description for the pulling pods is 

```
Name:           ccf4c09c9559869618c7076098e9506d-psi4n
Namespace:      default
Node:           ip-172-20-0-106.us-west-2.compute.internal/172.20.0.106
Events:
  FirstSeen     LastSeen        Count   From                                                    SubobjectPath           Type            Reason            Message
  ---------     --------        -----   ----                                                    -------------           --------        ------            -------
  7m            7m              1       {default-scheduler }                                                            Normal          Scheduled Successfully assigned ccf4c09c9559869618c7076098e9506d-psi4n to ip-172-20-0-106.us-west-2.compute.internal
  7m            1m              6       {kubelet ip-172-20-0-106.us-west-2.compute.internal}    spec.containers{user}   Normal          Pulling           pulling image "wordcount-map:latest"
  7m            1m              6       {kubelet ip-172-20-0-106.us-west-2.compute.internal}    spec.containers{user}   Warning         Failed            Failed to pull image "wordcount-map:latest": Error: image library/wordcount-map not found
  7m            1m              6       {kubelet ip-172-20-0-106.us-west-2.compute.internal}                            Warning         FailedSync        Error syncing pod, skipping: failed to "StartContainer" for "user" with ErrImagePull: "Error: image library/wordcount-map not found"

  7m    2s      29      {kubelet ip-172-20-0-106.us-west-2.compute.internal}    spec.containers{user}   Normal  BackOff         Back-off pulling image "wordcount-map:latest"
  7m    2s      29      {kubelet ip-172-20-0-106.us-west-2.compute.internal}                            Warning FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "user" with ImagePullBackOff: "Back-off pulling image \"wordcount-map:latest\""
```
## Work Around

Similar situation has also happened in local Pachyderm for I haven't build the `wordcount-map` image before running pipeline. And according to the logs, I speculate Pachyderm does not find the image either although I have built it.

```
 docker images
REPOSITORY                                         TAG                                IMAGE ID            CREATED             SIZE
wordcount-map                                      latest                             f2dbb2f78745        5 minutes ago       626 MB
gcr.io/google_containers/kube-controller-manager   a0f67ab467c5a2841d8925de77c98772   99263d2ba75c        5 weeks ago         100.6 MB
gcr.io/google_containers/kube-apiserver            d87e7379ff273c82d5b7da828a6b9946   16b1321dd29f        5 weeks ago         110.7 MB
gcr.io/google_containers/kube-scheduler            0c6423ac2eb63edac9af789132ac2760   96b9af4da0ef        5 weeks ago         60.06 MB
pachyderm/job-shim                                 latest                             b4905a4664f4        8 weeks ago         251.7 MB
gcr.io/google-containers/kube-addon-manager        v4                                 fb28c478466a        11 weeks ago        240.4 MB
gcr.io/google_containers/pause-amd64               3.0                                99e59f495ffa        4 months ago        746.9 kB
gcr.io/google_containers/etcd                      2.2.1                              a6cd91debed1        10 months ago       28.19 MB
```

If my speculation is correct, then the key problem is where I put the images that Pachyderm and Kubernetes can find it. I built the image on Kubernetes-Master node, but it did not work.

**Comment by pdeburen** [comment] 2016-09-07 14:35
Had the same problem yesterday with kubectl v1.2.2 and pachctl v1.1.0 and custom docker images on docker hub. Switching to kubectl v1.3.6 and restarting solved this for me (not sure if due to the update of kubectl or the restart).

**Comment by jdoliner** [comment] 2016-09-07 18:31
@ShengjieLuo your diagnosis is correct I believe. The issue is that the image is only present on the k8s master node which might not be the same docker host that the pod gets scheduled on, thus it can't find the image and needs to pull it but that fails too because the image isn't available in a registry.

Probably the easiest to fix this is to use a registry, to do that you'd do:

```
docker tag wordcount-map <your-name>/wordcount-map
docker push <your-name>/wordcount-map
```

Then change the manifest to point to `<your-name>/wordcount-map`

**Comment by sjezewski** [comment] 2017-03-31 21:59
This issue is quite old, so I'm going to close it. Feel free to re-open if you're still experiencing this issue.

**Closed by sjezewski** 2017-03-31 21:59 UTC
