### ISSUE TITLE
Pipeline update with changing output branch produces a "zombie" job

### ISSUE THREAD

**Issue by cfga** [pachyderm/pachyderm#4027] opened 2019-08-23 15:29 UTC
**What happened**:

A pipeline update with a changing output branch creates a stuck job, which prevents pipeline from progressing.

**How to reproduce it (as minimally and precisely as possible)?**:

What you need is just two pipeline specs and a test script. The differences between the specs are basically just the glob patterns and the output branch.

#### join.json
```
{
  "pipeline": {
    "name": "join"
  },
  "transform": {
    "image": "alpine:latest",
    "cmd": [ "/bin/sh" ],
    "stdin": [
       "for a in /pfs/A/v0/*",
       "do",
       "for b in /pfs/B/v1/*",
       "do",
       "echo 'v1' > /pfs/out/$(basename $a)_$(basename $b)_v1",
       "done",
       "done"
    ]
  },
  "input": {
    "cross": [
        {"pfs": {
           "repo": "A",
           "glob": "/v0"
            }},
        {"pfs": {
           "repo": "B",
           "glob": "/v1"
            }}
  ]},
  "output_branch": "v1"
}

```

#### join1.json
```
{
  "pipeline": {
    "name": "join"
  },
  "transform": {
    "image": "alpine:latest",
    "cmd": [ "/bin/sh" ],
    "stdin": [
       "for a in /pfs/A/v0/*",
       "do",
       "for b in /pfs/B/v1/*",
       "do",
       "echo 'v1' > /pfs/out/$(basename $a)_$(basename $b)_v1",
       "done",
       "done"
    ]
  },
  "input": {
    "cross": [
        {"pfs": {
           "repo": "A",
           "glob": "/v0"
            }},
        {"pfs": {
           "repo": "B",
           "glob": "/v1"
            }}
  ]},
  "output_branch": "v1"
}

```

#### test.sh
```
#!/usr/bin/env bash

pachctl create repo A
pachctl create repo B
pachctl create repo join
pachctl create branch join@v0


echo "foo" | pachctl put file A@master:/v0/foo
echo "bar" | pachctl put file B@master:/v0/bar
pachctl create pipeline -f join.json

sleep 30

echo "baz" | pachctl put file B@master:/v1/baz
pachctl create branch join@v1
pachctl update pipeline -f join1.json

```

Then just run the test.sh script and do `plj --history -1 `. It will give you something like this:

```
ID                               PIPELINE STARTED        DURATION           RESTART PROGRESS  DL UL STATE    
d476cafc48fd43c886c02483623ac08f join     3 seconds ago  -                  0       0 + 0 / 1 0B 0B running  
f5cda7e140024cdbb06eb73d432f1c31 join     7 seconds ago  -                  0       0 + 0 / 0 0B 0B starting 
eddb8650298b4facbb631cc2f0b36a52 join     9 seconds ago  Less than a second 0       0 + 1 / 1 0B 0B success  
328e385264c14338bbc62d62a1ae977d join     36 seconds ago Less than a second 0       1 + 0 / 1 8B 3B success
```

With one "zombie" job without any datum attached:

```
$ pachctl list datum f5cda7e140024cdbb06eb73d432f1c31
ID                                                                   STATUS TIME 
7e49514f86c934db683b5e0a729bd4ecdaa8c7affcc14d5ee64a7cb9a6c633707032 -      -

```

It does not finish and makes the pipeline get stuck.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T16:57:42Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.8-eks-a977ba", GitCommit:"a977bab148535ec195f12edc8720913c7b943f9c", GitTreeState:"clean", BuildDate:"2019-07-29T20:47:04Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`): both 1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): AmazonLinux2 (ami-0199284372364b02a)

**Comment by JoeyZwicker** [comment] 2019-08-23 17:45
Thanks @cfga. This is a dupe of #4009. Check out that issue for workarounds to get your jobs unstuck.

**Closed by JoeyZwicker** 2019-08-23 17:45 UTC
