### ISSUE TITLE
pachctl edit/update pipeline fails when setting output_branch that doesn't exist

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4944] opened 2020-06-03 18:37 UTC
**What happened?**:

I used `pachctl edit pipeline` to change the `output_branch` on the definition of an existing pipeline to a branch, and got the error "/pachyderm_pfs/branches/<pipeline name>/ <branch name> not found"

Same error occurs if I change the spec and update the pipeline. 
**What you expected to happen?**:

Since I can create the pipeline and have it automatically create the output branch, I'd expect edit pipeline or update pipeline to work the same way. 

**How to reproduce it (as minimally and precisely as possible)?**:

1. Create a pipeline without output branch specified.
2. Verify it's operating
3. Use either `pachctl edit pipeline` or `pachctl update pipeline` to change the `output_branch` to one that doesn't yet exist
4. The update fails with the error message above.

**Anything else we need to know?**:

It's probably valid to have this fail for updates, but the error message should be more informative.  If we do create the branch, we should make it clear in the docs that the head commit will be blank.  The user should create the branch and set it accordingly.

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment] 2020-06-03 22:45
I think this is a dupe of #4009. Closing in favor of that since it has more info. Feel free to reopen or copy over anything in this issue you feel is missing there.

**Closed by jdoliner** 2020-06-03 22:45 UTC
Labels: bug
