### ISSUE TITLE
Using /** as a glob pattern processes files multiple times

### ISSUE THREAD

**Issue by mrene** [pachyderm/pachyderm#3940] opened 2019-07-25 18:43 UTC
**What happened?**:
Declare a pipeline with `/**` as pfs glob pattern. Notice that the user code is called multiple times for the same input files.

**What you expected to happen?**:
Each file is processed exactly once.

**How to reproduce it (as minimally and precisely as possible)?**:
- Create a pipeline with `/**`
- Echo each filename as it's being processed
- Commit things in multiple folders

**Anything else we need to know?**:
> Joey Zwicker [2:30 PM] so `/**` has a bug/issue with it right now where it’ll have each unique path, not just the files as its own datum. So you’ll get `pfs/repo/dir/*` AND `pfs/repo/dir/file1` — which means file1 gets processed twice 

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
COMPONENT           VERSION
pachctl             1.9.0
pachd               1.9.1

- Cloud  provider:GKE

**Comment by adelelopez** [comment] 2019-07-25 22:14
Duplicate of https://github.com/pachyderm/pachyderm/issues/3335

**Closed by adelelopez** 2019-07-25 22:14 UTC
Labels: bug
