### ISSUE TITLE
1.4 Doc Tweaks

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1515] opened 2017-03-28 19:58 UTC
List 'em here.

**Comment by derekchiang** [comment] 2017-03-28 19:59
* Under "Get more help" section in both the PFS and the PPS page, the slack invite link is invalid.
* On the PPS page, all links are 404
* This is not necessarily a "bug", but the Bill of Rights should have links to each subsections, so that the "enabling Accessibility" and ""enabling Reproducibility" links can link to those subsection directly, as opposed to the top of the page.

**Comment by sjezewski** [comment] 2017-03-28 19:59
Links on this page are broken:

http://pachyderm.readthedocs.io/en/stable/reference/pachyderm_pipeline_system.html

Looks like we need to add '../' instead of './' to those links

**Comment by sjezewski** [comment] 2017-03-28 20:01
The 'Deploying Pachyderm' section in the side bar has the 'Deploying Pachyderm' as a prefix to all the links.

**Comment by sjezewski** [comment] 2017-03-28 20:06
This page contains comments in the shell sections, but they're rendered as titles:

http://docs.pachyderm.io/en/stable/pachctl/pachctl_flush-commit.html#return-commits-caused-by-foo-xxx-and-bar-yyy

This can also be seen on the page 'above' it:

http://docs.pachyderm.io/en/stable/pachctl/pachctl.html

**Comment by derekchiang** [comment] 2017-03-28 20:08
The [AWS deployment page](http://pachyderm.readthedocs.io/en/stable/deployment/amazon_web_services.html) doesn't document `pachctl deploy amazon`, which means people who already have k8s running on AWS won't know how to deploy.

**Comment by derekchiang** [comment] 2017-03-28 20:09
All Slack links under the "Get more help" section are using the old, inactive link.

**Comment by sjezewski** [comment] 2017-03-28 20:15
@gabrielgrant noted that old doc links are borked:

http://docs.pachyderm.io/en/v1.3.18/deployment/amazon_web_services.html

404s

I'll look into this / it seems like a RTDs issue

**Comment by derekchiang** [comment] 2017-03-28 20:15
On [the pipeline spec](http://pachyderm.readthedocs.io/en/stable/reference/pipeline_spec.html), the "Refer here for more information on delimiters" link is 404.

**Comment by sjezewski** [comment] 2017-03-28 20:18
Oh, looks like the RTDs finally realized it needed to rebuild 1.3.18 (I had opened an issue about this) ... so its currently building RN. That should resolve itself.

**Comment by sjezewski** [comment] 2017-03-28 20:19
Beg tutorial has empty boxes: http://pachyderm.readthedocs.io/en/stable/getting_started/beginner_tutorial.html

**Comment by derekchiang** [comment] 2017-03-28 20:20
The [migrations page](http://pachyderm.readthedocs.io/en/stable/deployment/migrations.html) refers to automatic migration for 1.4, which doesn't exist.

**Comment by dwhitena** [comment] 2017-03-28 20:38
Need to add some details about volume sizes etc. on the AWS deploy doc page.  Write now those things are mostly hidden in the script.

**Comment by gabrielgrant** [comment] 2017-03-28 23:06
On the specific cloud provider docs pages, there is no version specified for the pachctl install commands. As a result, 1.3.16 is installed (at least via deb; not sure about brew):

http://docs.pachyderm.io/en/stable/deployment/google_cloud_platform.html#install-pachctl
http://docs.pachyderm.io/en/stable/deployment/amazon_web_services.html#install-pachctl
http://docs.pachyderm.io/en/stable/deployment/azure.html#install-pachctl

We really should explicitly specify a version every time we have an install command (even if we think that's the default install at the time, it will inevitably change in the future). Pin all the versions! :P

**Comment by sjezewski** [comment] 2017-03-28 23:27
@gabrielgrant's point means I need to update the release script to update those docs as well. I've updated #1514 to include that todo

**Comment by JoeyZwicker** [comment] 2017-03-29 01:36
```I would have expected http://pachyderm.readthedocs.io/en/stable/deployment/amazon_web_services.html to tell me how ot use `deploy amazon` .. instead of deploying the cluster for me..```

**Comment by dwhitena** [comment] 2017-03-29 13:56
```Alexandre Bourget [9:47 AM] 
@dwhitena http://pachyderm.readthedocs.io/en/stable/getting_started/getting_started.html  has broken links in the middle there..

[9:47]  
went looking for the docs but couldn't find them..```

**Comment by dwhitena** [comment] 2017-03-29 16:34
The handle in "Ping @pachyderm on Twitter" isn't accurate.

**Comment by gabrielgrant** [comment] 2017-03-29 18:56
clarify `uuid` dependency: it was listed in the aws deploy docs  in [stable](http://docs.pachyderm.io/en/stable/deployment/amazon_web_services.html#prerequisites) but is gone in [latest](http://docs.pachyderm.io/en/latest/deployment/amazon_web_services.html#prerequisites)

It's needed for the deploy script, but not the manual deploy, so should be added back in at the top of the [script section](http://docs.pachyderm.io/en/latest/deployment/amazon_web_services.html#scripted-pachyderm-deploy)

Should also include an explanation of what's actually needed (`sudo apt-get install uuid` and some brew command, i suppose?)

**Comment by rikonor** [comment] 2017-03-30 03:22
Noticed a few places in the Beginner Tutorial where the text is badly formatted:
[create-a-repo](https://github.com/pachyderm/pachyderm/blob/0ea911f6b307f5ae2373c2a1280c01496e51c943/doc/getting_started/beginner_tutorial.rst#create-a-repo) towards the end of the section.
[adding-data-to-pachyderm](https://github.com/pachyderm/pachyderm/blob/0ea911f6b307f5ae2373c2a1280c01496e51c943/doc/getting_started/beginner_tutorial.rst#adding-data-to-pachyderm) mid and end of section.

Possibly more places, just haven't read through the entire thing yet.

**Comment by gabrielgrant** [comment] 2017-03-31 06:28
http://docs.pachyderm.io/en/latest/fundamentals/getting_data_out_of_pachyderm.html?highlight=service#examining-file-provenance-with-flush-commit has a broken link to [a “How to leverage provenance” Guide](http://docs.pachyderm.io/en/latest/cookbook/how_to_leverage_provenance). Not sure where this should be pointing to (we used to have [an empty placeholder provenance page](http://docs.pachyderm.io/en/v1.3.18/advanced/provenance.html), but that seems to be gone from v1.4)

**Comment by gabrielgrant** [comment] 2017-03-31 06:30
Googling for "pachyderm service" brings up http://docs.pachyderm.io/en/stable/deployment/serving_data_from_pachyderm.html which is currently a broken link. Did we figure out how to add redirects? I think that should be pointed here: http://docs.pachyderm.io/en/latest/fundamentals/getting_data_out_of_pachyderm.html

**Comment by dwhitena** [comment] 2017-03-31 14:36
Ok, consolidating all the things that need to be addressed asap here:

- [ ] Enable readthedocs redirects for docs that existed in 1.3, but do not exist in 1.4 (e.g., deploying in the cloud, services, provenance, etc.)
- [ ] Make sure that all references to Slack point to the correct invite link.
- [ ] Modify and add back in the PPS and PFS reference docs.  Also test/fix the included links.
- [ ] Fix rendering on the pachctl doc pages (some comments are rendered as titles, pipeline spec shows up where it isn't supposed to, etc.)
- [ ] Further update the AWS deploy doc to have a better flow and better integrate the aws deploy script as a starting point (including clarifying dependencies).
- [ ] Check/fix/update broken links on the pipeline spec doc.
- [ ] Fix beginner tutorial formatting issues.
- [ ] Fix how the migrations page refers to automatic migration for 1.4, which doesn't exist.  Make sure the doc is clearly linked in the rendered site.
- [ ] Make sure all references to installing pachctl include an explicit version number, and make a list of all references, so these can be automatically updated.
- [ ] Add a glob/parallel processing section to fundamentals. 
- [ ] Note about valid characters for pipeline/repo names.
- [ ] Make sure all deploy commands have the necessary etcd flag.

Then, these are things that need to be added/modified after the initial high priority stuff above:

- [ ] Links for the subsection of the Bill of Rights.
- [ ] Update the bill of rights to make sure everything rings true with 1.4.  Also correcting typos along the way.
- [ ] Add services doc back under fundamentals, update for 1.4
- [ ] Update Jupyter example for 1.4, add back into the docs and update any info in the blog post.
- [ ] Update fruit stand and scraper to 1.4
- [ ] Better explanation for `from` options with update pipeline
- [ ] Better explanation of incrementality, when new data only is processed, etc.
- [ ] Clearer flow for describing the different uses of put-file.  It can be confusing that sometimes you need a path, sometimes you don't, sometimes you have a commit-id, sometimes a branch, etc.
- [ ] Explain splitting files, delimiters, with an example.
- [ ] Add dynamic provisioning examples and test them.
- [ ] Make sure the we mention vendoring issues somewhere in relation to the Go doc (i.e., that you need a specific version of grpc)

Then, these are things that need to be added as we can:

- [ ] SQL example cookbook doc
- [ ] Explicit ML workflow cookbook doc
- [ ] Jupyter integration cookbook doc
- [ ] Example OpenStack deploy integrated in the on-prem doc
- [ ] Best practices, scaling docs
- [ ] Update FAQ/troubleshooting and add them back in.
- [ ] Docs about branches
- [ ] Docs about deleting pipelines, repos, etc., why there isn't delete-commit, etc.
- [ ] Python client testing/example
- [ ] Whatever else has already been opened in individual issues.

**Comment by JoeyZwicker** [comment] 2017-04-06 00:47
default deployment node size on GKE is too small. It only has 4GB of memory. We should figure out what GKE side is roughly equivalent to the AWA xlarge and make that what users spin up when following our docs. You can't do anything interesting with the tiny default nodes.

**Comment by dwhitena** [comment] 2017-04-06 14:24
@JoeyZwicker Adding to the checklist above.  It's really simple to change this.  Testing now actually.

**Comment by dwhitena** [comment] 2017-04-06 18:55
Note @sjezewski @JoeyZwicker, I have created redirects for old pages that no longer exist.  However, as far as I can tell, we can't create redirects for new pages that didn't exist before (e.g., when you switch versions).  Not sure what the solution to that is.

**Comment by gabrielgrant** [comment] 2017-04-10 22:33
the link to glob patterns is broken in https://github.com/pachyderm/pachyderm/blob/master/migration/1.3.x-1.4.x/README.md#inputs 

is it supposed be broken on GH to make it work on readthedocs or something?

**Comment by dwhitena** [comment] 2017-04-18 19:07
Update `pypachy` to say it is compatible with 1.4 now.

**Comment by dwhitena** [comment] 2017-05-23 20:06
I'm moving any remaining things that are tracked here to the corresponding 1.5 checklist here: https://github.com/pachyderm/pachyderm/issues/1869, and closing this issue.

**Closed by dwhitena** 2017-05-23 20:06 UTC
Labels: docs
