### ISSUE TITLE
Shorten datum hashes

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#2113] opened 2017-08-02 18:53 UTC
Right now they're quite long

```
17-07-27[13:05:29]:pachyderm:0$pc list-datum 486cbb55-3ce0-4940-b0ca-b08bb54fa2ca
ID                                                                 STATUS              TIME                
eec3814a51f0a14e00b3744e568f5d0cfa06c165907831a1183fe017d3c6d0cc   success    Less than a second
```

And you need to specify that hash as an input for the `inspect-datum` command. It would be helpful for it not to take up as much space (so we could display more), and on the UI for us to be able to show a shorter hash.

**Comment by thedrow** [comment] 2017-08-08 08:16
See #2042 regarding using better hash algorithms. In this context we can use a a hash function that produces shorter hashes such as xxhash.
Also, #2031 is relevant to this issue.

**Comment by ysimonson** [comment] 2019-06-10 21:53
Dupe of #2031

**Closed by ysimonson** 2019-06-10 21:53 UTC
