### ISSUE TITLE
"create-repo" failed because network

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#613] opened 2016-07-01 05:55 UTC
I was deploying the Pachyderm on Google Container Engine. The main part has been finished and the pod is running.
`NAME                   READY          STATUS           RESTARTS                       AGE            NODE`
`etcd-gj2z1             1/1            Running          0                              4m             gke-pachyderm-default-pool-788e5c85-7rhn`
`pachd-gf40r            1/1            Running          2                              4m             gke-pachyderm-default-pool-788e5c85-a794`
`pachd-ma5os            1/1            Running          2                              4m             gke-pachyderm-default-pool-788e5c85-7rhn`
`rethink-irhoi          1/1            Running          0                              4m             gke-pachyderm-default-pool-788e5c85-7rhn`
 
Now , I need to create an empty repo to make sure that everything has been set up correctly as the manual said. Therefor, I execute the command `pachctl create-repo test`

But Pachyderm responded me with that
 `2016/07/01 13:47:07 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 104.197.165.43:30650: i/o ti
meout"; Reconnecting to {"104.197.165.43:30650" <nil>}`

**Comment by ShengjieLuo** [comment] 2016-07-01 05:58
The debug information can found here
`pachctl version`
`COMPONENT           VERSION `
`pachctl             1.0.1-ab10ee8e15ad854f27813fad3ab7af1378960497   `
`pachd               UNKNOWN: Error rpc error: code = 4 desc = context deadline exceeded`

The address information:
`echo $ADDRESS`
`104.197.165.43:30650`

The directory information
`ls $GOPATH/bin`
`pachctl  pach-deploy`

**Comment by ShengjieLuo** [comment] 2016-07-01 06:01
The firewall information is here
`NAME                                     NETWORK  SRC_RANGES         RULES                         SRC_TAGS  TARGET_TAGS`
`default-allow-icmp                       default  0.0.0.0/0          icmp`
`default-allow-internal                   default  10.128.0.0/9       tcp:0-65535,udp:0-65535,icmp`
`default-allow-rdp                        default  0.0.0.0/0          tcp:3389`
`default-allow-ssh                        default  0.0.0.0/0          tcp:22`
`gke-pachyderm-2e98fcbb-all               default  10.0.0.0/14        udp,icmp,esp,ah,sctp,tcp`
`gke-pachyderm-2e98fcbb-ssh               default  104.197.247.58/32  tcp:22                                  gke-pachyderm-2e98fcbb-node`
`gke-pachyderm-2e98fcbb-vms               default  10.128.0.0/9       icmp,tcp:1-65535,udp:1-65535            gke-pachyderm-2e98fcbb-node `                   
`my-rule                                  default  0.0.0.0/0          tcp:32080`
`my-rule1                                 default  0.0.0.0/0          tcp:32081`
`my-rule2                                 default  0.0.0.0/0          tcp:32082`
`my-rule3                                 default  0.0.0.0/0          tcp:30650`
`pachd                                    default  0.0.0.0/0          tcp:30650`

I add several firewall rules to allow the traffic in 30650. It seems that dial to 30650 should be allowed in firewall rules.

**Comment by ShengjieLuo** [comment] 2016-07-01 06:04
Hence , the question is that what happened to pachctl? It does confuse me a lot. @jdoliner @derekchiang

**Comment by ShengjieLuo** [comment] 2016-07-01 06:35
Also I tested the node to see whether the port is open
`netstat -ntpl`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name`
`tcp6       0            0       :::30650                     :::*                            LISTEN      -`
The 30650 port is open for any server.

I use telnet in Google Cloud Shell to see whether it is open. Unfortunately, the telnet told me the failure to connect to the port.
`telnet 104.197.165.43 30650`
`Trying 104.197.165.43...`
`telnet: Unable to connect to remote host: Connection timed out`

Ping 104.197.165.43 is right.

**Comment by derekchiang** [comment] 2016-07-01 18:49
Hi @ShengjieLuo, so I assume that you used `make google-cluster` to create the cluster?  That's where the firewall rule would be added.

Can you double-check that `104.197.165.43` is indeed the **external** IP address of the instance?  Each GCE instance has an external and an internal IP address.  You want to make sure to use the external one.

Another thing to check: since you are running 2 pachd pods on 3 GCE instances, it's possible that you just happened to be connecting to the instance that **does not** have a pachd pod.  So you might want to try using the IP addresses of the other two instances.

**Comment by ShengjieLuo** [comment] 2016-07-05 00:58
@derekchiang The company has ran out its google account, hence, I may migrate my work to local server. And this problem cannot be solved actually. I think the possible reason to this problem maybe that I deploy the cluster and execute the command in Google Cloud Shell instead of ssh to the instances. Also, the port's ip address is tcp6 instead of tcp. While GCE does not allow IPv6. I am not sure it works.

**Comment by sjezewski** [comment] 2016-09-06 21:58
Since we cannot reproduce, closing this issue

**Closed by sjezewski** 2016-09-06 21:58 UTC
