### ISSUE TITLE
pachctl logs -j Returns No Results (2.0.0-alpha.18)

### ISSUE THREAD

**Issue by dgeorg42** [pachyderm/pachyderm#6191] opened 2021-05-26 16:17 UTC
**What happened?**:

After running several jobs, I ran `pachctl logs -j <<job-id>>` on more than one of them to view the logs, and nothing was returned.

**What you expected to happen?**:

I expected to see the logs for the jobs whose IDs I provided.

**How to reproduce it (as minimally and precisely as possible)?**:

See above. :)

**Anything else we need to know?**:

I am able to access the logs for the pipeline via `kubectl logs <<podname>> user`  When I did this, I noticed that the way the job ID is logged changed with 2.0.  It used to appear with the name "jobId" whereas now it appears with the name "pipelineJobId".  So my suspicion is that the filtering by job ID broke as a result.

**Environment?**: 
- Kubernetes version (use `kubectl version`): 1.19
- Pachyderm CLI and pachd server version (use `pachctl version`): 2.0.0-alpha.18
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release):
- Others:

**Comment by nitinjainsj** [comment] 2021-05-28 00:59
Retest after global ID changes.

**Comment by nitinjainsj** [comment] 2021-06-16 01:53
We are returning the logs message from user but not complete.

```
$ kc logs pipeline-edges-v1-vlg88 user | grep 6c9e6a4d2f634a9cb41ce3fd52c2b38f | wc
      23     152    5997
$ pc logs  -j edges@6c9e6a4d2f634a9cb41ce3fd52c2b38f | wc
       4      56     514
$
```

**Comment by acohen4** [comment] 2021-06-16 20:08
> We are returning the logs message from user but not complete.
> 
> ```
> $ kc logs pipeline-edges-v1-vlg88 user | grep 6c9e6a4d2f634a9cb41ce3fd52c2b38f | wc
>       23     152    5997
> $ pc logs  -j edges@6c9e6a4d2f634a9cb41ce3fd52c2b38f | wc
>        4      56     514
> $
> ```

@nitinjainsj right now we are returning all log lines marked with "user". I think this makes sense for the use case where someone only expects logs from their code. If you filter the k8s logs with: 

`$ kc logs pipeline-edges-v1-vlg88 user | grep 6c9e6a4d2f634a9cb41ce3fd52c2b38f | grep "\"user\":true" | wc`
, you should get the same log lines.

It seems to me that it's behaving as intended. What do you think @nitinjainsj ?

**Comment by acohen4** [comment] 2021-06-29 19:31
Closing issue based on above comments

**Closed by acohen4** 2021-06-29 19:31 UTC
Labels: 2.0.0, bug
