### ISSUE TITLE
[Question] Helm chart, why dashboard left out

### ISSUE THREAD

**Issue by DarkBlaez** [pachyderm/pachyderm#4919] opened 2020-05-26 21:45 UTC
I have seen this issue floating around I think since 2018 so was curious as to why the dashboard deployment and service exposure is still being left out of the core helm chart? Surely it's as qucik as 30 minutes of adding the values, template for the deployment and service, testing, and releasing in "incubating". 

Why I ask, It's been missing as part of the deployment with no other reference. What is becoming mind numbing is the number of projects devising their on <my great project>ctl bin file to interact with the kubeconfig and service the pods and deployments rather than just tossing the manifest or helm charts out there and leaving the interacting client bin with the same or reduced functionality. Many corporations are not going to deploy apps with custom <repeat the phrase>ctl for every product.

The primary mechanism for deployment to a Kubernetes cluster needs to remain with the core kubectl, manifest, or helm charts which continue to gain over other deploy mechanisms

I am in the process of devising the heml chart for this but the container tosses a PACHD_SERVICE_HOST: undefined value  was unaware that the container is unable to except env being passed in as well. So with that, where is the Dockerfile for the dashboard? the container is out thre on docker hub but no associated dockerfile reference. I have not seen the dockerfile in the git either to resolve.

Thanks
DB<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/75'>Zendesk ticket #75</a>)<br>gz#75</i>

**Comment by ysimonson** [comment] 2020-06-08 19:38
The honest answer is that the helm charts just haven't been maintained. They're broken in a variety of ways:

* It's missing a variety of options:
  * https://github.com/pachyderm/pachyderm/issues/4808
  * https://github.com/pachyderm/pachyderm/issues/3729
  * https://github.com/pachyderm/pachyderm/issues/3594
* It doesn't handle migrations: https://github.com/pachyderm/pachyderm/issues/3439
* And as you noted, it doesn't deploy dash: https://github.com/pachyderm/pachyderm/issues/3440

The overall tracking issue for helm support is in #1068. @chainlink began working on helm support, but I think it took a backburner because there are now more kube-native ways of deploying applications with the operator pattern and kustomize. Reworking our deployment process to use this is also being headed up by @chainlink now, I'm not sure what the latest on it is though.

Closing as dupe of #3440

**Closed by ysimonson** 2020-06-08 19:38 UTC
Labels: user
