### ISSUE TITLE
`ListFileHistory` can deadlock

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/pachyderm#3608] opened 2019-03-25 21:59 UTC
Concurrently writing to a file and calling `ListFileHistory` on it can get into a deadlocked state. Here is a minimal, reproducible test: https://github.com/pachyderm/pachyderm/compare/list-file-history-test

Observed on k8s on docker for mac.

**Comment by ysimonson** [comment] 2019-03-25 22:05
^ I have committed the cardinal sin of mixing tabs and spaces in that branch, sorry

**Comment by ysimonson** [comment] 2019-09-18 15:15
This appears to have been fixed in the mean-time. I'll open a PR with the regression test.

**Comment by ysimonson** [comment] 2019-09-18 15:19
I spoke too soon. It passed the first few times, but is now failing again.

**Comment by ysimonson** [comment] 2019-09-19 18:03
I'm still seeing the issue - deadlocks occur when calling `View` on `*bolt.DB`.

**Comment by ysimonson** [comment] 2019-09-23 22:12
Holding on continued investigation of this. Our intention is to no longer use BoltDB for filesets, which would obviate the need for a fix.

**Comment by ysimonson** [comment] 2020-04-08 17:47
@Tryneus not sure if I heard right, but did @brycemcanally mention that you fixed this already?

**Comment by Tryneus** [comment] 2020-06-25 18:27
Could not reproduce this error with the given test, so I think it is safe to assume the problem has been fixed.  Ported the test forward to our current PFS unit tests and merged it in #5045.

**Closed by Tryneus** 2020-06-25 18:27 UTC
Labels: bug, storage
