### ISSUE TITLE
Implicit port-forwarding will randomly fail

### ISSUE THREAD

**Issue by Nick-Harvey** [pachyderm/pachyderm#3514] opened 2019-02-21 15:30 UTC
**What happened?**:
Occasionally when issuing a pachctl command implicit port-forwarding will throw the following error

```
nick at Nicks-MacBook-Pro-2 in ~/Git/Pachyderm/tests/RNN
$ pachctl delete-pipeline GoT_generate_large
ERRO[0009] Implicit port forwarding was not enabled because of an error: port forwarding failed: error upgrading connection: error sending request: Post https://4dnnq2j87l.us-central1-c-1.cloud.kubermatic.io:31091/api/v1/namespaces/default/pods/pachd-b9875cf8f-bht5n/portforward: dial tcp 35.192.123.145:31091: connect: operation timed out
could not connect (note: address "0.0.0.0:30650" looks like loopback, check that 'pachctl port-forward' is running): context deadline exceeded
```

However, if given the same exact command immediately after, will succeed with no changes done to the connection

```
nick at Nicks-MacBook-Pro-2 in ~/Git/Pachyderm/tests/RNN
$ pachctl list-pipeline
NAME               INPUT             CREATED        STATE / LAST JOB
GoT_generate_large GoT_train_large:/ 19 minutes ago running / failure
GoT_train_large    GoT_scripts:/     19 minutes ago running / running

nick at Nicks-MacBook-Pro-2 in ~/Git/Pachyderm/tests/RNN
$ pachctl delete-pipeline GoT_generate_large

nick at Nicks-MacBook-Pro-2 in ~/Git/Pachyderm/tests/RNN
$
```

**What you expected to happen?**:
A stable connection to the kubernetes cluster

**How to reproduce it (as minimally and precisely as possible)?**:
1. kubectl proxy to k8s cluster
2. Deploy pachyderm
3. deploy pipelines, add files, change pipelines, etc. Just general use of pachctl beyond just the 1-2 commands to test. 

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.13.3
- Pachyderm CLI version (use `pachctl version`): 1.8.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release): MacOS
- Others:

**Comment by ysimonson** [comment] 2019-03-01 14:07
I'm having trouble reproducing this issue. @JoeyZwicker I know you managed to, would you be able to add some details?

**Comment by JoeyZwicker** [comment] 2019-03-01 18:16
I was getting the error on my cluster yesterday, but have since restarted minikube it seems. I will try to repro

**Comment by ysimonson** [comment] 2019-03-19 16:20
I have managed to repro this issue in #3508.

In that case at least, port forwarding breaks down after a few minutes of intense activity (conformance test runs.) This happens regardless of whether it's `pachctl`'s port forwarder, or `kubectl`'s, so it's not the implicit port forwarder (in fact that probably helps, since most implicit port forwarding activity is short-lived), however our increased employment of port forwarding probably makes this issue more obvious.

It's consistently reproducible in k8s on docker for mac. I think I've seen it on minikube/ubuntu, but need to do more test runs to see whether those were one-offs.

**Comment by ysimonson** [comment] 2019-03-21 01:21
What follows may not be the only way to break the k8s' port forwarder, but it is a reliable way observed in s3gateway work.

k8s' port forwarder multiplexes many client tcp connections into a single spdy connection with many streams. If just a few client tcp connections unexpectedly close their connection, the port forwarder is unable to create new streams.

My guess is that there's a low limit to the number of spdy streams that can be maintained, and it's not closing up existing streams when a connection breaks.

This is a demonstration script, but it only works on the s3gateway branch:

```python
#!/usr/bin/env python3

import http.client
import subprocess
import time
import threading

def daemon(target):
    t = threading.Thread(target=target)
    t.daemon = True
    t.start()
    return t

server_proc = None
def server():
    global server_proc
    server_proc = subprocess.Popen(["pachctl", "port-forward"])

def worker():
    conn = http.client.HTTPConnection("localhost:30600")
    conn.request("GET", "/")
    conn.getresponse()
    conn.close()

subprocess.run(["make", "install"], check=True)
daemon(server)

time.sleep(3.0)
for _ in range(10):
    daemon(worker)

time.sleep(3.0)
server_proc.send_signal(3)
```

**Comment by ysimonson** [comment] 2019-03-21 16:14
Two streams are allocated for each tcp connection: one for tunneling traffic, and one for the server to report back errors. When a tcp connection closes unexpectedly, the traffic tunneling streams appears to close (at least on the client-side), but the error channel remains open. This has two implications:

1. Port forwarding doesn't exit because it blocks until the error stream is closed
2. A stream is leaked on both sides of the spdy connection

**Comment by ysimonson** [comment] 2019-03-21 19:55
It looks like this is NOT happening on ubuntu/minikube; only on docker for mac

**Comment by ysimonson** [comment] 2019-03-21 20:46
Nevermind; intiially, the test script was not reproducing the issue on ubuntu/minikube, but now it is. My guess is that prior runs eventually got it in a bad state, but resetting everything to investigate further.

**Comment by ysimonson** [comment] 2019-03-29 20:43
Related k8s ticket: https://github.com/kubernetes/kubernetes/issues/74551

**Comment by ysimonson** [comment] 2019-06-11 00:49
Given the nature of this issue, I don't think we can do anything above and beyond surfacing this with k8s core

**Closed by ysimonson** 2019-06-11 00:49 UTC
