### ISSUE TITLE
List file behavior differs from Get file

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#6515] opened 2021-07-12 15:23 UTC
When listing files in a repo, if multiple files of the same name coexist (We will definitely discourage this behavior and promote a healthy way for datums to write into files - by requesting one unique filename per datum), the list file lists each of the identical files and augments the info with a TAG to help disambiguate.

This is sub-optimal for several reasons:
1. Displaying the TAG implies that this behavior is normalized which it is not. It can lead to potentially disastrous behaviors in the downstream pipelines and should be avoided at all costs.
2. We do not have the ability to retrieve the content of those files anyway since the get file aggregates the content of all identical files.

You should probably display one file per path in the list file and add a clear warning when we detect that multiple files with the same name coexist.

**Comment by jdoliner** [comment] 2021-07-20 17:12
Going to check with @brycemcanally but I think we can close this because it won't be possible for the user to get into this situation.

**Comment by jdoliner** [comment] 2021-07-20 17:31
Confirmed with @brycemcanally, closing. We should remove the `TAG` field of the `list file` output, there might just be a single commit which can be reverted that contains the change.

**Closed by jdoliner** 2021-07-20 17:31 UTC
Labels: 2.0.0, bug
