### ISSUE TITLE
Corrupt data in Ceph object store is failing job, difficult to recover

### ISSUE THREAD

**Issue by pingenglj** [pachyderm/pachyderm#3687] opened 2019-05-01 08:29 UTC
**What happened?**:

Job encounters `object not found` error when it tries to retrieve large file (~50GiB).

```
{"pipelineName":"pipeline_name","jobId":"56efbbe75219....06c0fdf877","workerId":"pipeline-pipeline_name-v1-zzdlb","datumId":"a1add12745f2da1c9433ce42c502....6e90dd6c9709b28db1e009","data":[{"path":"/1","hash":"4z/Ex9SccZU5hZ....ZcRoXy147CKCPEV9dwZA="},{"path":"/1","hash":"8FkTBsizmVnk/geY4n....4muRqU+fX8="},{"path":"/1","hash":"+gh7hfgJNfnIok9QYt....jUP7y7kPAFMBZ0="},{"path":"/1","hash":"PrJ7ADbsEFBiN.....4d1/a6N74dDOYI="}],"ts":"2019-04-26T05:51:08.498351387Z","message":"errored downloading data after 38m58.683097515s: objectInfoGetter: object c73483aba4d991...75f2ffe0fd344fcb180f0d not found"} 
```

We are using a S3/Swift API on top of Ceph (via RADOS gateway) as a storage backend for our Kubernetes cluster.

The file was committed to a Pachyderm repo, and `put-file`/`finish-commit` finished without errors.

This file was segmented, and we traced the segment with hash `c73483aba4d991...75f2ffe0fd344fcb180f0d` in our object store (it shows up in the bucket's `/pach/object` directory). However, when trying to perform any operation on it (move/copy/delete/rename) it returns a `NoSuchKey` error and does not allow the operation.

I'm guessing the segment got corrupted somehow. As a consequence, when trying to re-commit the corrupted file, Pachyderm recognizes the segment is already there (I think it does see the reference file in `/pach/object`) and tries to reuse the object. This results in the same error when trying to get the data when the job starts since the data is not there. Therefore re-commiting is not a fix.

We "fixed" this by moving to a different Kubernetes environment, but it would be helpful to find an actual fix if it occurs again in the future. It is difficult to recover at the moment.

At the same time, we did a `delete-repo` and ran `garbage-collect`, but stopped the `garbage-collect` after about ~1.5days since it did not seem to do much. Perhaps it's also encountering this `NoSuchKey` error? Anyhow it is difficult to monitor what `garbage-collect` is doing and how it is progressing.

**What you expected to happen?**:

Not sure if this is a Pachyderm issue or Ceph issue (or somewhere in between). I expect the job to fail when data is corrupted, but it would be useful if `put-file` is able to spot corrupted data so that it actually re-uploads this data in stead of using the corrupted segment.

Additionally, it would be helpful if `garbage-collect` would give some indication on its progress or what it is doing.

**How to reproduce it (as minimally and precisely as possible)?**:

Not sure how the data was corrupted, at least a large enough file should be used so that it is segmented in object storage.

**Anything else we need to know?**:

-

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI version (use `pachctl version`):
```
COMPONENT           VERSION
pachctl             1.7.3
pachd               1.7.3
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
Canonical kubernetes juju charm (openstack) on private cloud.
- OS (e.g. from /etc/os-release):
Ubuntu 18.04.1 LTS
- Others:
-

**Comment by JoeyZwicker** [comment] 2019-05-01 18:55
Thanks for filing this.

A few things to note:

First, this initially seems like a weird issue with Swift, the fact that
they have an object there, but you can't do anything with it is a bad sign.
You're able to do those operations on other blocks, just not that one?

Second, I'm noticing you're running a fairly old version of Pachyderm.
We're about to release 1.9.0 in the coming 1-2 weeks and we will be
desupporting 1.7.x soon after. I dont think this issue is specifically
caused by the older version, but just wanted to mention it as you'll want
to talk with us through a migration path to get you to newer versions soon.
1.7 --> 1.8 does require a hefty migration. 1.8 --> 1.9 is very light and
something will be able to automate for you.

**Comment by pingenglj** [comment] 2019-05-02 14:53
> You're able to do those operations on other blocks, just not that one?
Yes
> Second, I'm noticing you're running a fairly old version of Pachyderm. [...]
Thanks! We have been wanting to upgrade and it is on our planning :)

**Comment by jdoliner** [comment] 2019-05-03 00:37
> (it shows up in the bucket's /pach/object directory). However, when trying to perform any operation on it (move/copy/delete/rename) it returns a NoSuchKey error and does not allow the operation.

This seems like a pretty clear indication that the object store is experiencing an internal error. Pachyderm expects that objects that it can list it can also perform other operations on without hitting `NoSuchKey` errors. Pachyderm's deduplication is the reason that recommitting the data doesn't help, unfortunately deduplication degrades to just throwing data away if the underlying storage says it has data when it doesn't. The only way we could really bulletproof against this would be to actually download the data to check it's there, but that would be massively inefficient. I think we just have to accept that pachyderm isn't going to be able to insulate itself against issues like this with the underlying object store and the behavior of running Pachyderm on such object stores is going to be undefined. I'd recommend raising this issue with the Ceph folks or using a different object store.

Having progress for `garbage-collect` is something that has been requested by others and that we would like to add. However we are also in the process of reworking garbage collection to be something that happens in the background rather than explicitly, which should obviate the need for progress.

I'm going to close this bug because I don't think there's anything we can add to Pachyderm to fix this issue.

**Closed by jdoliner** 2019-05-03 00:37 UTC
