### ISSUE TITLE
Client pipeline didn't trigger

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2491] opened 2017-11-01 16:44 UTC
Building a PoC with a client:
* They've created a pipeline to download several images and process them
* They're adding a second pipeline to upload the processed images to S3 (named with some scheme)
* After creating the second pipeline, Pachyderm didn't start any jobs, even though the input repo had two commits in it

**Comment by JoeyZwicker** [comment] 2017-11-01 17:42
just in case this has to do with some odd dag bug:

`Schema` (1 commit) --> `image_processor`
`Data` (2 commits) --> `image_processor`
`image_proc` actually had 7 commits on it do to a few failed attempts, a few --reprocess calls, and stats commits (which we know are on a separate branch)
Created `uploader` with only `image_proc` as input... no jobs were triggered

Other notes for repro:
 - Originally tried creating and updating pipeline in same json which failed #2485. Unlikely to be the cause
- pods/pipelines came up fine and everything looked good, but no jobs. Even `update-pipeline for uploader` didn't start jobs --> hypothesis: a pathalogical bug with flush-commit as opposed to some race state with pipeline creation/updates
- running `--reprocess` on the `image_proc` pipeline then _did_ trigger uploader to run, but only on those newly created commits

**Comment by msteffen** [comment] 2017-12-11 23:01
We just observed a similar bug with a user in our users channel:
- The user has a very similar DAG: two inputs feeding into one pipeline
- The user updated their pipeline, which spawned a job, which the user killed (deleted? Unclear from their message)
- The user then called `update-pipeline --reprocess` on the pipeline and it stopped 
- Once the user's cluster got into a broken state, new commits in either input branch didn't cause downstream pipelines to run

Either deleting the job, `--reprocess` or some interaction between the two could be related

**Comment by msteffen** [comment] 2017-12-12 00:34
Another client ran into a similar bug: they called UpdatePipeline (without `--reprocess`) and lost the ability to trigger the pipeline.

One hypothesis: this bug is due to dangling JobInfos in etcd. When a pipeline master receives a new commit, it checks etcd to see if there any jobs with the same salt as the current pipeline, and if so, doesn't spawn anything new. If a PipelineInfo document for a dead job gets stuck in etcd, the pipeline master might stop spawning new pipelines.

**Comment by jdoliner** [comment] 2019-06-20 23:11
Job triggering code has gone through several revisions since this issue was posted so I'm pretty sure this has been fixed. Since the commit invariant refactor we've had a lot fewer job triggering issues and the ones we have had proved to be pretty easy to fix. Unfortunately we never found a specific repro for this bug so I can't test to make sure it doesn't exist, but I think it makes sense to close this. Feel free to reopen if you feel you're still seeing this bug.

**Closed by jdoliner** 2019-06-20 23:11 UTC
