### ISSUE TITLE
request ids for all requests

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1578] opened 2017-04-04 22:09 UTC
This feature would help with debugging by adding an id field in the ctx of all requests. The ID would be logged along with the rest of the request which would make it possible to trace the flow of a request through the stack with logs.

**Comment by sjezewski** [comment] 2017-07-07 00:40
I think this is a duplicate of #922 

Though doing what's described here may be a simpler initial tool than using an off the shelf tracing library. TBD.

**Closed by sjezewski** 2017-07-07 00:40 UTC
Labels: technical-debt
