### ISSUE TITLE
Figure out why sometimes a node doesn't know about some repos

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#317] opened 2016-04-18 19:04 UTC
We've been assuming that a node always knows about every repo, but it's been observed in production that sometimes a node doesn't know about certain repos.  See #314.

One potential cause might be that a DeleteRepo operation only partially completed.

**Comment by jdoliner** [comment] 2016-04-18 19:15
This could also conceivably happen if the node wasn't assigned any shards. But in all the cases we've seen there were more than enough shards to go around which means that's likely not the full story.

**Comment by sjezewski** [comment] 2016-05-05 21:40
Hard to reproduce

**Comment by jdoliner** [comment] 2016-07-11 23:12
This is should go away with the pfs refactor. I'm going to add it to 1.2 so we remember to check it when we're done, although since we couldn't reproduce this reliable it may be hard to verify.

**Comment by sjezewski** [comment] 2016-09-06 21:52
Since we don't have a way to reproduce, closing after the pfs-refactor

**Closed by sjezewski** 2016-09-06 21:52 UTC
Labels: pfs_refactor
