### ISSUE TITLE
in 2.X , pachctl auth login needs to be run with -b flag when terminal session cannot launch a browser

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#6319] opened 2021-06-11 19:16 UTC
**Provide a link to the page with an issue:**

Troubleshooting documentation for authentication workflows

**Describe what is wrong:**

If the user is in WSL in Windows, or ssh'd into a machine from which a browser can't be launched, they won't be able to launch a browser.

**Describe the suggested changes:**

Recommend that  when running in an environment where the command line cannot launch a browser window,  to complete the session, they should run the `pachctl auth login` command with the `-b`  flag.  

```
pachctl auth login -b
```

**Anything else we need to know?**

**Environment:**
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS:
- Other:

**Comment by jdoliner** [comment] 2021-06-14 21:07
Closing as a dupe of #6318

**Closed by jdoliner** 2021-06-14 21:07 UTC
Labels: 2.0.0, auth, docs
