### ISSUE TITLE
Make it so that we don't have to re-create external PRs

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#2018] opened 2017-07-06 19:00 UTC
Currently CI won't run for PRs created by outside contributors, since CI embeds certain credentials which we want to protect.  To merge a PR from an outside contributor, we currently need to literally recreate the PR, which is a very manual and error-prone process and it might discourage outside contributions.

**Comment by sjezewski** [comment] 2017-07-07 00:38
Duplicate of #1935

**Closed by sjezewski** 2017-07-07 00:38 UTC
Labels: high priority
