### ISSUE TITLE
How to identify output from multiple datums?

### ISSUE THREAD

**Issue by jfri3d** [pachyderm/pachyderm#3770] opened 2019-05-27 16:23 UTC
**What happened?**:
Datum saves "incorrect" commit meaning it is not possible to identify which inputs caused what output (when running multiple datums in a single job).

**What you expected to happen?**:
I would expect to be able to list a datum and get the **actual** input and output commits. 

---

**How to reproduce it (as minimally and precisely as possible)?**:
* Add dummy pipeline **join.json** to “join” two input filenames

```json
{
  "pipeline": {
    "name": "join"
  },
  "transform": {
    "image": "alpine:latest",
    "cmd": [ "/bin/sh" ],
    "stdin": [
       "for a in /pfs/A/*",
       "do", 
       "for b in /pfs/B/*",
       "do",
       "touch /pfs/out/$(basename $a)_$(basename $b)",
       "done",
       "done"
    ]
  },
  "input": {
    "cross": [
        {"pfs": {
           "repo": "A",
           "glob": "/*"
            }},
        {"pfs": {
           "repo": "B",
           "glob": "/*"
            }}
  ]},
  "standby": true
}

```

* Add **repos**, empty **files** and **pipeline**

```sh
pachctl create repo A && pachctl create repo B
echo "" | p put file A@master:A1
echo "" | p put file B@master:B1
echo "" | p put file B@master:B2
pachctl create pipeline -f join.json
```

* this will generate a single job with **multiple** datums

```sh
pachctl list job

ID                               PIPELINE STARTED        DURATION   RESTART PROGRESS  DL UL STATE
eb751e1c6ed3421e960069efa74a5a6a join     13 minutes ago 11 seconds 0       2 + 0 / 2 4B 0B success
```

* both datums show identical commits

```sh
pachctl inspect datum eb751e1c6ed3421e960069efa74a5a6a b24d80f43a3d7389fb5f4fd542065386d27c54bd11e264b256d03333a115f20c

ID	b24d80f43a3d7389fb5f4fd542065386d27c54bd11e264b256d03333a115f20c
Job ID	eb751e1c6ed3421e960069efa74a5a6a

PFS State:
  REPO    COMMIT                             PATH
  join    931662a7f929439b8dbdbfbcfea29fc1   /b24d80f43a3d7389fb5f4fd542065386d27c54bd11e264b256d03333a115f20c/pfs
Inputs:
  REPO    COMMIT                             PATH
  A       d761f2dc575c416f8e3202b9d519dfde   /A1
  B       0e8d6d65b9794ce391be748ea5ec83ce   /B2
```

---

```sh
pachctl inspect datum eb751e1c6ed3421e960069efa74a5a6a 5e767c399b8f429777ce6e8bce9b5d251a4a7e31a915758390df92efa374df6c

ID	5e767c399b8f429777ce6e8bce9b5d251a4a7e31a915758390df92efa374df6c
Job ID	eb751e1c6ed3421e960069efa74a5a6a

PFS State:
  REPO    COMMIT                             PATH
  join    931662a7f929439b8dbdbfbcfea29fc1   /5e767c399b8f429777ce6e8bce9b5d251a4a7e31a915758390df92efa374df6c/pfs
Inputs:
  REPO    COMMIT                             PATH
  A       d761f2dc575c416f8e3202b9d519dfde   /A1
  B       0e8d6d65b9794ce391be748ea5ec83ce   /B1

```

* provenance appears broken since it only takes the **incomplete** history

```sh
pachctl list file B@master

COMMIT                           NAME TYPE COMMITTED      SIZE
0e8d6d65b9794ce391be748ea5ec83ce /B1  file 21 minutes ago 1B
0e8d6d65b9794ce391be748ea5ec83ce /B2  file 21 minutes ago 1B
```

* instead of the **complete** history

```sh
pachctl list file B@master --history -1

COMMIT                           NAME TYPE COMMITTED      SIZE
6825ce40328243f2a472c431d6526bb1 /B1  file 34 minutes ago 1B
0e8d6d65b9794ce391be748ea5ec83ce /B2  file 34 minutes ago 1B
```

* issue -> how to tell which datum is responsible for which output?

```sh
pachctl list file join@master

COMMIT                           NAME   TYPE COMMITTED      SIZE
82ed24973a214766b7e5cf1ea9616024 /A1_B1 file 21 minutes ago 0B
82ed24973a214766b7e5cf1ea9616024 /A1_B2 file 21 minutes ago 0B
```

**Comment by JoeyZwicker** [comment] 2019-05-27 21:16
@jfri3d Thanks for submitting this question. There are a few key concepts of Pachyderm that'll explain what you're seeing and I'll put them in line with the various parts of your initial submission.

> pachctl list file B@master

> COMMIT                           NAME TYPE COMMITTED      SIZE
0e8d6d65b9794ce391be748ea5ec83ce /B1  file 21 minutes ago 1B
0e8d6d65b9794ce391be748ea5ec83ce /B2  file 21 minutes ago 1B

> instead of the complete history
> pachctl list file B@master --history -1

> COMMIT                           NAME TYPE COMMITTED      SIZE
6825ce40328243f2a472c431d6526bb1 /B1  file 34 minutes ago 1B
0e8d6d65b9794ce391be748ea5ec83ce /B2  file 34 minutes ago 1B


First, commits in pachyderm are cumulative, meaning that file B1 exists both in the HEAD commit of B as well as the previous commit where it was actually added. Traversing the history to find the commit where a file was "last modified" is actually a pretty expensive operation (although we can possibly fix this). That's why in the below commands B1's commit is shown as `0e8...` when you do `list file` -- we want to make it fast -- but when you pass the history flag, then we do the more expensive operation.


> pachctl list job

> ID                               PIPELINE STARTED        DURATION   RESTART PROGRESS  DL UL STATE
eb751e1c6ed3421e960069efa74a5a6a join     13 minutes ago 11 seconds 0       2 + 0 / 2 4B 0B success

Second, notice you only had 1 job trigger that processed both datums -- as opposed to 2 jobs that each processed one datum. This is because Pachyderm pipelines, by design, only look at the HEAD commit of the branch of each input repo and process what they see there. They _will_ smartly skip datums that have previously been successfully processed, but we don't do that by looking at diffs of the input commits or anything like that, we know based on the actual content of the datum. In your case, the HEAD commit had two unprocessed datums in repo B, `B1` and `B2`. 

Therefore, when you do `inspect-datum`, file `B1` _is actually_ being read from commit `e08...` even if that file was added in the previous commit. Job `eb7...` took the HEAD commit from `Repo A`  and `Repo B` as input. Jobs always only take 1 commit (HEAD) from each input `repo@branch`.

> issue -> how to tell which datum is responsible for which output?

> (from your slack message): Why isn't this included in provenance?
pachctl list file join@master

> COMMIT                           NAME   TYPE COMMITTED      SIZE
82ed24973a214766b7e5cf1ea9616024 /A1_B1 file 21 minutes ago 0B
82ed24973a214766b7e5cf1ea9616024 /A1_B2 file 21 minutes ago 0B

Now, we get to your last question, which is totally valid. If you hadn't nicely named your input/output files, how would you tell that `A1+B1` created `A1_B1`? Why isn't this included in provenance?

A note about provenance. As a user mentioned in the slack channel, provenance at Pachyderm applies at the commit layer. Provenance can tell you that commit `82e...` in the join repo is the output of processing `d76...` from `A` and `0e8...` from B. offering true datum-level provenance could require a massive amount of metadata to track as it's very common to have tons datums for every single job. This is something we've discussed internally at length and are eventually hoping to offer, but it's still a major open design question. 

All of this said, Pachyderm actually _does_ give you a way to answer "If you hadn't nicely named your input/output files, how would you tell that `A1+B1` created `A1_B1`?" using the `enable_stats: true` flag in the pipeline json. With stat's enabled, Pachyderm will create a `stats` branch in your output repo with a commit that corresponds to every output commit (e.g. your `join` repo would have a stats commit that corresponds to `82e...`. **The stats commit will contain exactly the info you're looking for including, for each datum, what input files were seen AND what output files were created.** 

We recognize that for a large number of datums, using the stats commits can be a bit unwieldy and we're also working to improve this at some point.

**Comment by JoeyZwicker** [comment] 2019-06-02 00:57
@jfri3d I'm going to close this issue because there's no outstanding TODO, but if you have any followup questions or issues please reopen and I'm happy to continue the conversation.

**Closed by JoeyZwicker** 2019-06-02 00:57 UTC
