### ISSUE TITLE
Parallelism not totally working with `cross`

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2480] opened 2017-10-30 15:28 UTC
### Environment

- Ubuntu 16.04
- k8s 1.7 in minikube (although users have reported this with full clusters)
- Pachyderm 1.6.3

### Behavior

When using this pattern:

```
  "input": {
    "cross": [
      {
        "atom": {
	  "repo": "repo-with-sharding",
	  "glob": "/*"
	}
      },
      {
	"atom": {
	  "repo": "repo-without-sharding",
	  "glob": "/"
	}
      }
    ]
  }
```

Assuming that there are multiple files or directories at the root of `repo-with-sharding`, one would expect that this would produce many datums that look like:

```
/pfs/repo-with-sharding/file1
/pfs/repo-without-sharding/

/pfs/repo-with-sharding/file2
/pfs/repo-without-sharding/

/pfs/repo-with-sharding/file3
/pfs/repo-without-sharding/

etc...
```

Also, assuming that you have mutliple workers:

```
  "parallelism_spec": {
    "constant": "5"
  },
```

One would expect that the workers would process the datums in parallel. However, this appears to not always be the case:

- When using 2 workers, I see the datums split between the two, but
- When using more than 2 workers, I see that the datums are only processed sequentially by a single worker.

### Steps to reproduce

(this can be replicated locally, but users have also seen this on full Pachyderm clusters)

1. Deploy Pachyderm locally.

2. Set up the [iris ML pipeline](https://github.com/pachyderm/pachyderm/tree/master/doc/examples/ml/iris) as follows:

    ```
    $ pachctl create-repo training
    $ pachctl create-repo attributes
    $ pachctl create-pipeline -f python_train.json
    $ pachctl create-pipeline -f python_infer.json
    $ cd data 
    $ pachctl put-file training master -c -f iris.csv
    $ cd ..
    ```

3. Duplicate some of the data so there are more files to process:

    ```
    $ cd data/test
    $ cp 2.csv 3.csv
    $ cp 2.csv 4.csv
    $ cp 2.csv 5.csv
    $ cp 2.csv 6.csv
    $ cp 2.csv 7.csv
    $ cp 2.csv 8.csv
    $ cp 2.csv 9.csv
    $ cp 2.csv 10.csv
    $ pachctl put-file attributes master -c -r -f .
    ```

4. Update the infer pipeline to have more than 2 workers:

    ```
    "parallelism_spec": {
      "constant": "5"
    },
    ```

    and

    ```
    $ pachctl update-pipeline -f python_infer.json --reprocess
    ```

5. Wait for the pipeline workers to come up.

6. Look at the worker IDs in the raw job logs to see that only one worker shows up and is processing all the datums sequentially.

### Other comments

Note, I have tried to replicate this for other input patterns (e.g., without `cross`). The other patterns don't appear to suffer from this bug. For example, the edges pipeline in our OpenCV demo parallelizes just fine over more than 2 workers.

**Comment by jonandernovella** [comment] 2017-10-30 15:33
Issue reproduced. I can see the same behaviour. I tested it with 8 workers.

**Comment by jdoliner** [comment] 2017-10-30 23:29
I suspect the issue here is with queueing. Pachyderm distributes work evenly between the workers it can talk to and workers are able to enqueue more than one datum to process at a time. This helps them by allowing them to upload and download other datums while they're processing a different datum. However, it behaves badly when the number of datums is close in magnitude to the number of workers because the first workers to come online enqueue all the datums and there's nothing left for the others.
You can confirm that this is what's going on by doing an inspect job while the job is running, worker statuses should tell you how many datums each worker has enqueued.

There's a pretty good fix to this right now which is that you can decrease the `max_queue_size` field in the pipeline spec, unfortunately there's a bug where you can't set it to `0` since that'll get interpreted as the default value, but if you set it to `1` it should sufficiently spread out your datums. This should also be fixed by #2473.

**Comment by JoeyZwicker** [comment] 2017-10-31 04:46
This issue has confused a lot of early users as it's very common to have a small number of datums when you're first learning and developing pipelines on Pachyderm. 

Could we consider potentially making the default queue just 1 so it does what users expect at that scale and then changing the queue size larger is a performance optimization that users can add when they're productionizing pipelines? The increased performance we're trying to give with a default >1 is nullified for low datum counts.

The alternative to this would be to have smarter logic that sets queue size based on the number of datums if not set explicitly by the user.

**Comment by jdoliner** [comment] 2017-10-31 04:53
> Could we consider potentially making the default queue just 1

:+1:, this is a good answer imo. Except actually it's going to be `0` because the datum being processed doesn't count as queued. Implementing this actually just requires removing the logic that interprets as `0` in the protobuf as `10`, the default that I initially choose.

**Comment by dwhitena** [comment] 2017-11-14 17:57
@jdoliner Any update here. Do you know if we can squeeze this into the next release as a couple users have been asking (cc: @JoeyZwicker ).

**Closed** 2017-11-16 18:50 UTC
Labels: user
