### ISSUE TITLE
Error from InspectJob

### ISSUE THREAD

**Issue by stefanbacon** [pachyderm/pachyderm#605] opened 2016-06-30 10:54 UTC
After doing the local setup (https://github.com/pachyderm/pachyderm/blob/master/SETUP.md):

```bash
[...]
make launch-kube
make launch
```

I followed the quickstart guide to a T but getting the following error at this stage:
https://github.com/pachyderm/pachyderm/tree/master/examples/fruit_stand#what-happens-when-you-create-a-pipeline

```bash
# pachctl list-job
Error from InspectJob: grpc: failed to unmarshal the received message proto: bad wiretype for field google_protobuf.Timestamp.Seconds: got wiretype 2, want 0
```

versions:

```bash
# pachctl version
COMPONENT           VERSION                                          
pachctl             1.0.1-78819c8b134db6f2e9b708f3fe49ba8ff458fb25   
pachd               1.0.1-1433 
```

```bash
#  kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.2", GitCommit:"528f879e7d3790ea4287687ef0ab3f2a01cc2718", GitTreeState:"clean"}
```

**Comment by jdoliner** [comment] 2016-06-30 17:58
This is caused by a version mismatch between pachctl and the server that you launched.
Probably the best way to fix it would be to do:

```
make clean-launch
make docker-build
make launch-dev
```

This will launch you a cluster from head.

**Comment by jdoliner** [comment] 2016-07-08 21:11
Closing since I think it's just a version mismatch error. Please reopen if the above steps don't solve your problem.

**Closed by jdoliner** 2016-07-08 21:11 UTC
