### ISSUE TITLE
put-file/PutFile should (optionally?) indicate progress

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#2359] opened 2017-09-30 00:18 UTC
it would be useful to be able to show a progress indicator on files being ingressed into pach

for uploads this can probably be done more easily from the client, but when pach is fetching a file itself, it would be nice if status messages were streamed back (by making PFS.PutFile() into a bi-directional streaming request, instead of just using a client stream)

**Comment by sjezewski** [comment] 2017-10-19 00:23
This has come up many times w customers.

**Comment by gabrielgrant** [comment] 2017-10-19 08:57
I believe @derekchiang was working on this somewhat recently. Did that go anywhere?

**Comment by gabrielgrant** [comment] 2017-10-19 09:01
Looks like work i was thinking of may be in #2293, which doesn't seem to include anything about progress reporting

**Comment by ysimonson** [comment] 2019-06-10 21:47
Dupe of #1589

**Closed by ysimonson** 2019-06-10 21:47 UTC
Labels: 1.7 backlog
