### ISSUE TITLE
Better parsing errors for syntax problems in pipelines' JSON 

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3072] opened 2018-07-21 06:18 UTC
**What is the goal / desired outcome?**

As a user, I want to be able to easily understand why my pipeline spec isn't being accepted when I've introduced a syntax error rather than seeing `malformed pipeline spec: json: cannot unmarshal string into Go value of type []json.RawMessage` (see https://github.com/pachyderm/pachyderm/issues/1904#issuecomment-405141832 )

**What is your proposal for a feature to solve this?**

Report JSON parse errors with messages something like this: `Unexpected token "s" in JSON at line 1, position 0`. I believe both Python and V8 (JS) do something like this by default. There must be a Go lib that does too.

**If there is a way to accomplish this today via workaround, what does that require?**

1. Use some other JSON parser to validate
2. Squint really hard
3. Get confused at the opaque error (totally legitimately); helpfully open an issue reporting what seems like an internal problem; be told that no, in fact, it's not a "bug", we just have borderline-unusably opaque error reporting :P (https://github.com/pachyderm/pachyderm/issues/1904#issuecomment-405147770)

**Comment by ysimonson** [comment] 2019-06-10 23:26
Dupe of #2651

**Closed by ysimonson** 2019-06-10 23:26 UTC
