### ISSUE TITLE
Wrong number of pods for job with coefficient parallelism.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1541] opened 2017-03-31 01:27 UTC
> My 4 worker nodes have 8 vcpus each. I want to spread my data so that each CPU takes charge of a worker (pod) , so I set a coefficient of 8. However, the job only created 16 pods in kubernetes ( i expected 32) Any ideas about why is this?

This was reported for 1.3.16 but it seems like it should apply to 1.4 as well since the code hasn't changed much.

**Comment by dwhitena** [comment] 2017-03-31 11:07
More info from the user:

> I asked @jdoliner yesterday. He said: I’d try again with the constant field set to 32 and see if maybe that gets you a sane result, we’re going to have to run some tests and see if we can reproduce what you’re seeing here.
> 
> In that case, the same thing happened. 16 pods

**Comment by jonandernovella** [comment] 2017-03-31 13:16
+1

**Comment by jonandernovella** [comment] 2017-03-31 15:03
Tested it with 1.4 stable release. Now it seems to work better. However, instead of creating 32 (8vcpus*4worker nodes), i see that it created 48 pods (presumably 8 vcpus * 6 nodes including the 2 edge nodes ). Any ideas about this? I think it is desirable that they would only be scheduled in the worker nodes.

**Comment by sjezewski** [comment] 2018-02-09 00:05
Dupe of #1547 afaict

**Closed by sjezewski** 2018-02-09 00:05 UTC
Labels: user
