### ISSUE TITLE
Unexpected long processing time related to FUSE

### ISSUE THREAD

**Issue by ShengjieLuo** [pachyderm/pachyderm#699] opened 2016-08-04 05:32 UTC
Hi !  I am running Pachyderm Wordcount Sample on AWS EC2+Ubuntu14.04+Kubernetes1.2.2+Pachyderm1.1.0

The program can be executed successfully with a correct result. However, it lasts nearly  30 minutes, which is too long for a data processing platform. I am not sure about the problem. 

See processing time here,
```
ID                                 OUTPUT                                              STARTED             DURATION             STATE
b80331f28ac956ba308011b7ef969054   wordcount_reduce/605aa77a63f4456f867f2c476aced43d   59 minutes ago      24 minutes           success
105a07fead7878072e178a9440e5134f   wordcount_map/366ed6c782024fe0a58e5b43346ea70f      About an hour ago   5 minutes            success
cdeca10ac3f24292824a5c878542517b   wordcount_input/30e1f6d2f41a42eca350f76f15722d8b    About an hour ago   18 seconds           success
```
So strange that for Hadoop the work can be done in just seconds. I checked the log of the wordcount_reduce pods. See here,
```
0 | 2016-08-04T04:39:19Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"wordcount_reduce"},"id":"605aa77a63f4456f867f2c476aced43d"}},"repoAlias":"out","write":true},"name":"inclining","err":"no such file or directory"}
0 | 2016-08-04T04:39:19Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"wordcount_reduce"},"id":"605aa77a63f4456f867f2c476aced43d"}},"repoAlias":"out","write":true},"name":"inclining","err":"no such file or directory"}
0 | 2016-08-04T04:39:19Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"wordcount_reduce"},"id":"605aa77a63f4456f867f2c476aced43d"}},"repoAlias":"out","write":true},"name":"inclining","err":"no such file or directory"}
0 | 2016-08-04T04:39:19Z ERROR fuse.DirectoryLookup {"directory":{"file":{"commit":{"repo":{"name":"wordcount_reduce"},"id":"605aa77a63f4456f867f2c476aced43d"}},"repoAlias":"out","write":true},"name":"inclining","err":"no such file or directory"}
```
Totally 248409 times, all log events are about FUSE.  I am not sure the unexpected long processing time is caused by FUSE error, but I think it is not a normal phenomenon and too many interrupts (10000times/minute) would decrease the efficiency. 
Note: Docker log , Kubernetes log and Pachyderm log are the same. The only thing we can see is about the FUSE Error.

**Comment by jdoliner** [comment] 2016-08-04 22:57
Hi @ShengjieLuo afaict everything you're seeing here is expected behavior. Our performance isn't as good as we'd like it to be but the wordcount pipeline is designed to do a lot of work to stress the system. We'd like this particulary job to be quicker for sure but we certainly don't consider jobs that last 30 minutes to be inherently too long for a data processing platform, people regularly do jobs that last this long (and much longer) on Hadoop.

The directory error messages are harmless as well, they indicate that the system is checking for the existence of files before it attempts to write them and finding that they aren't there which is what's supposed to happen.

Closing since I don't think there's anything to fix here.

**Closed by jdoliner** 2016-08-04 22:57 UTC
