### ISSUE TITLE
Wait commit through pachctl not printing and / or returning commits.

### ISSUE THREAD

**Issue by brycemcanally** [pachyderm/pachyderm#6326] opened 2021-06-11 20:21 UTC
Wait commit through pachctl does not appear to return commits with the `<repo>@<commit-id>` or `<commitset-id>` format. The commitset appears to be setup properly after digging into the state, but the commits are not appearing in the output of pachctl.

**Comment by acohen4** [comment] 2021-06-28 16:33
playing with it now, I cannot reproduce the buggy behavior. Was this fixed in the last week? @brycemcanally @nitinjainsj

**Comment by acohen4** [comment] 2021-06-29 19:48
the output now seems to behave as expected. Closing this issue

**Closed by acohen4** 2021-06-29 19:48 UTC
Labels: 2.0.0
