### ISSUE TITLE
"pachctl deploy storage" requires pachd restart to be effective

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#3990] opened 2019-08-09 01:24 UTC
**What happened?**:

I performed a pachctl deploy storage to add credentials to ingress and egress from an S3 bucket.  I attempted to put a file into a repo from an S3 bucket and I got the error message "amazon-region not found". 

I deleted the pachd pod, the replication controller restarted it, and then I was able to access storage.

**What you expected to happen?**:
I expected the deploy storage would do the restart for me.

**How to reproduce it (as minimally and precisely as possible)?**:

1. deploy some storage credentials.
2. put a file from a bucket accessible from those credentials
3. Watch it fail with "amazon-region not found"
4. Kill the pachd pod and let it restart
5. put the file again, watch it succeed.

**Anything else we need to know?**:

This may just be a doc bug; if we make it clear in the doc that pach must be restarted that may be all that's necessary.

**Environment?**:
- Kubernetes version (use `kubectl version`): docker-for-desktop
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.3
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): docker-for-desktop
- OS (e.g. from /etc/os-release):macos
- Others:

**Comment by pappasilenus** [comment] 2019-08-09 01:25
@svekars note doc aspects.  I can show you where in the source to change this, if you'd like to...

**Comment by ysimonson** [comment] 2019-08-09 01:33
Dupe of #2678

**Comment by pappasilenus** [comment] 2019-08-09 01:44
Ah, we should note the wait period in docs, or recommend killing the pod. That may be why I never noticed it before.

**Comment by svekars** [comment] 2019-08-09 16:30
@pappasilenus where in the docs is the appropriate place to add this?

**Comment by svekars** [comment] 2019-08-09 19:41
After discussing this with @pappasilenus, it seems like this should be a part of a section that describes how to transition from a local test cluster to a production deployment. The instructions need to explain how to use the backup and restore/extract to move your cluster to production. The same credentials must be used for all buckets. A use case with a multi-cloud option that presumes that you might be running Pachyderm in let's say an AWS environment while consuming the data from an S3 storage from another provider must be described as well.

**Comment by mindthevirt** [comment] 2021-12-14 22:31
This no longer relevant since `pachctl deploy` has been deprecated.

**Closed by mindthevirt** 2021-12-14 22:31 UTC
Labels: docs, size: S, priority: medium
