### ISSUE TITLE
Python modules import fail when using pachyderm but run normally using local docker run

### ISSUE THREAD

**Issue by marcelfarres** [pachyderm/pachyderm#5653] opened 2021-01-27 22:11 UTC
**What happened?**:
I created a docker image using [repronim/neurodocker:0.7.0](https://github.com/ReproNim/neurodoc). I tested the image locally and it ran as expected. 

I created a pipeline using this image in pachyderm and it failed to import the modules. 

This error can be reproduced locally and also using the pachyderm hub.

**What you expected to happen?**:
Pipeline working as expected and tested, behaving as tested locally using docker run.

**How to reproduce it (as minimally and precisely as possible)?**:
You can find a minimum example [here](https://github.com/pachyderm/pachyderm/files/5883389/test-import.zip).

`Makefile` was created to help (you should have minikube/pachctl/kubectl/docker/… installed)

Run `make start` to start minikube etc.

Run `make docker-run` to generate the docker file (using `bwell2bids-test/create_dockerfile.sh`) and test the image. You will need to change `marcelfarres` for your dockerhub username in the make file and pipeline definition. This step should print `Script run successfully`.

Run `make run-dev` to create base repo, create pipline & update images and push the test file to the pipeline.

Run `make read-log` to see the import error.

```
Traceback (most recent call last):
  File "/src/bwell2bids-test.py", line 10, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-17T02:13:01Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Pachyderm CLI and pachd server version (use `pachctl version`):
pachctl             1.11.0              
pachd               1.11.0      

- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
local using minikube + pachyderm hub 

- OS (e.g. from /etc/os-release):
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal

- Others:

**Comment by echohack** [comment] 2021-01-27 22:55
Hi @marcelfarres Thanks for opening this issue and the detailed steps to reproduce!

I don't suspect any shenanigans happening here with the user container. There may be another issue going on here, such as a cached container -- I'm going to spend some time working through your example to see what might be happening.

**Comment by marcelfarres** [comment] 2021-02-09 00:07
Hi @echohack, and @mindthevirt, is there any updates/progress the bug? Can I help with something?

**Comment by echohack** [comment] 2021-02-09 00:15
Hi @marcelfarres I haven't gotten to your issue yet. Sorry for the wait!

**Comment by echohack** [comment] 2021-02-16 19:12
Hey @marcelfarres I had a look into your issue. First: You can resolve your issue by simply changing your pipeline.json as so:

old:

```json
    "transform": {
        "image": "echohack/bwell2bids-test:latest",
        "cmd": ["python", "/src/minibwell2bids.py",
            "--input", "/pfs/bwell-log-input/",
            "--output", "/pfs/out/"]
    }
```

new:
```json
    "transform": {
        "image": "echohack/bwell2bids-test:latest",
        "cmd": [ "/bin/bash" ],
        "stdin": [
            "/neurodocker/startup.sh",
            "python /src/minibwell2bids.py --input /pfs/bwell-log-input --output /pfs/out/"
        ]
    }
```

The reason you're running into this issue is that Pachyderm executes `cmd` outside the context of a shell. This is quite common (Docker/Kube also do this). Neurodocker's startup script and the provided Dockerfile in your repo make some assumptions about the running shell that means that your startup script never gets executed properly. I had a look at the Neurodocker repo, and it seems that most folks are using this project by running this locally on their personal machines using `docker run`. `docker run` will automatically give you a shell environment -- so there's a number of assumptions at runtime that aren't being accounted for when you want to run this in production in another system (like Docker/Kube).

You can fix this a couple of ways:

1. You can execute the startup script yourself by invoking a shell in `cmd`.

2. You can build the container in a way so it's not dependent on the user environment.

Ref: https://docs.pachyderm.com/latest/reference/pipeline_spec/#transform-required

I'm closing this issue now. I hope this was helpful, and again thank you for the detailed steps to reproduce!

**Closed by echohack** 2021-02-16 19:12 UTC
