### ISSUE TITLE
pachd OOM killed when submitting multiple files in parallel

### ISSUE THREAD

**Issue by marcadella** [pachyderm/pachyderm#4573] opened 2020-02-06 09:15 UTC
Pachd is being OOM killed when submitting multiple files in parallel, even though the size of the files is much less than the memory requested.

Here is pachd description:
```
Containers:
  pachd:
    Container ID:   docker://b2f29d5d9f12fb6d481f1e0a8056804aad9a90012037074c6b12b7fde42a2715
    Image:          pachyderm/pachd:1.9.11
    Image ID:       docker-pullable://pachyderm/pachd@sha256:6f6766741d88d9c57701e7df75f1eeaed0f3802f12e2fbe3c643127efd9eceea
    Ports:          650/TCP, 651/TCP, 652/TCP, 600/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 06 Feb 2020 10:05:06 +0100
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Thu, 06 Feb 2020 09:56:00 +0100
      Finished:     Thu, 06 Feb 2020 10:02:15 +0100
    Ready:          True
    Restart Count:  6
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     1
      memory:  1Gi
    Environment:
      TIMEOUT:                                        1m
      EXPOSE_OBJECT_API:                              false
      PACH_ROOT:                                      /pach
      NUM_SHARDS:                                     16
      STORAGE_UPLOAD_CONCURRENCY_LIMIT:               100
      STORAGE_BACKEND:                                MINIO
      STORAGE_HOST_PATH:                              
      GOOGLE_BUCKET:                                  <set to the key 'google-bucket' in secret 'pachyderm-storage-secret'>        Optional: true
      GOOGLE_CRED:                                    <set to the key 'google-cred' in secret 'pachyderm-storage-secret'>          Optional: true
      AMAZON_BUCKET:                                  <set to the key 'amazon-bucket' in secret 'pachyderm-storage-secret'>        Optional: true
      AMAZON_DISTRIBUTION:                            <set to the key 'amazon-distribution' in secret 'pachyderm-storage-secret'>  Optional: true
      AMAZON_ID:                                      <set to the key 'amazon-id' in secret 'pachyderm-storage-secret'>            Optional: true
      AMAZON_SECRET:                                  <set to the key 'amazon-secret' in secret 'pachyderm-storage-secret'>        Optional: true
      AMAZON_REGION:                                  <set to the key 'amazon-region' in secret 'pachyderm-storage-secret'>        Optional: true
      AMAZON_TOKEN:                                   <set to the key 'amazon-token' in secret 'pachyderm-storage-secret'>         Optional: true
      MICROSOFT_CONTAINER:                            <set to the key 'microsoft-container' in secret 'pachyderm-storage-secret'>  Optional: true
      MICROSOFT_ID:                                   <set to the key 'microsoft-id' in secret 'pachyderm-storage-secret'>         Optional: true
      MICROSOFT_SECRET:                               <set to the key 'microsoft-secret' in secret 'pachyderm-storage-secret'>     Optional: true
      MINIO_ENDPOINT:                                 <set to the key 'minio-endpoint' in secret 'pachyderm-storage-secret'>       Optional: true
      MINIO_BUCKET:                                   <set to the key 'minio-bucket' in secret 'pachyderm-storage-secret'>         Optional: true
      MINIO_SECURE:                                   <set to the key 'minio-secure' in secret 'pachyderm-storage-secret'>         Optional: true
      MINIO_ID:                                       <set to the key 'minio-id' in secret 'pachyderm-storage-secret'>             Optional: true
      MINIO_SECRET:                                   <set to the key 'minio-secret' in secret 'pachyderm-storage-secret'>         Optional: true
      MINIO_SIGNATURE:                                <set to the key 'minio-signature' in secret 'pachyderm-storage-secret'>      Optional: true
      PACHD_POD_NAMESPACE:                            metakube (v1:metadata.namespace)
      WORKER_IMAGE:                                   pachyderm/worker:1.9.11
      WORKER_SIDECAR_IMAGE:                           pachyderm/pachd:1.9.11
      WORKER_IMAGE_PULL_POLICY:                       IfNotPresent
      PACHD_VERSION:                                  1.9.11
      METRICS:                                        true
      LOG_LEVEL:                                      error
      BLOCK_CACHE_BYTES:                              100Mi
      PACHYDERM_AUTHENTICATION_DISABLED_FOR_TESTING:  false
    Mounts:
      /pach from pachdvol (rw)
      /pachyderm-storage-secret from pachyderm-storage-secret (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metakube-pachyderm-token-ddz8q (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  pachdvol:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  pachyderm-storage-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pachyderm-storage-secret
    Optional:    false
  metakube-pachyderm-token-ddz8q:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metakube-pachyderm-token-ddz8q
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
```

Then  when doing
```
#smallFile.txt size is 1743B << 
pachctl start commit input@master
for I in {0..5}; do pachctl put file input@master:/$I -f smallFile.txt & done
pachctl finish commit input@master
```
or even `pachctl put file input@master:/ -i list.txt`,
I get `transport is closing` because `pachd` has been OOM killed.

**Environment?**:
- Pachyderm 1.9.11
<br><br><i>(related to <a href='https://pachyderm.zendesk.com/agent/tickets/52'>Zendesk ticket #52</a>)<br>gz#52</i>

**Comment by marcadella** [comment] 2020-02-09 22:43
Tried to download a 650Mi file and pachd got OOM killed even though it had 2Gi requested mem and no pipeline was running... Uploading or downloading a file should not consume any memory whatsoever if it is decently implemented...

**Comment by kevindelgado** [comment] 2020-02-10 23:23
There is a lot more copying happening under the hood at various layers that end up eating more memory than you would expect. Specifically, some of the object storage go clients are making copies in memory as a tradeoff to increase network performance (e.g. we saw this happen when we upgraded our s3 client to enable multi-part uploads).

Go's pprof tool is exposed as part of pachctl. So if you run `pachctl debug pprof heap` you can post the profile and binary files created and we can see if there's anything out of the ordinary happening there.

In general, we see most of our deployments successful using 4GB of memory. As an experiment, I'd like to see if you're still running into issues at 4GB memory. In the meantime, we will be doing some experimenting on our end to better understand the relationship between the size of files, number of files, and memory limits.

**Comment by sinonkt** [comment] 2020-05-11 16:54
@marcadella  @kevindelgado Hi, I also encounter the same OOMkilled as well.

In my case, my pachd deployment request 3 Gi memory. and everything went well for many cases. for example upload 10 files of 1 GB, no memory errors occurs.

But when i've upload one of my dataset that has 10 files of just 13 MB and some intentionally added zero-byte file, memory rises exceed the limits.

Either 
1. removed that zero-bytes file Or
2. add one character to this file Or
3. increase limits memory to 4 GB.
Solved my issue.
hope this help you guys!

**Comment by jdoliner** [comment] 2020-05-11 17:20
@sinonkt 

Thanks for the report, this definitely sounds like a bug. Would you mind clarifying for us what you mean by "some intentionally added zero-byte file" how many 0-byte files were there? Just the one? Or more?

**Comment by sinonkt** [comment] 2020-05-11 18:12
@jdoliner Sorry for my english.
it's just a single metadata file that's describe what type of this dataset samples are.
```touch __type.16S``` just one of them can cause this issue. :((

**Comment by pappasilenus** [comment] 2020-05-18 18:23
@sinonkt We're going to reproduce this issue. Can you tell us what your object store is, and what storage backend you're using?

@marcadella Can you tell us if 1.10.4 option for reducing parallelism helps you out with this?

**Comment by sinonkt** [comment] 2020-05-19 04:12
@pappasilenus Hi, I use standalone MINIO,  STORAGE_BACKEND: "MINIO"
using image from docker hub minio/minio:RELEASE.2020-03-25T07-03-04Z
for Pachyderm stuffs:             
pachctl             1.10.1              
pachd               1.10.1

**Comment by pappasilenus** [comment] 2020-06-19 23:17
@sinonkt I can't reproduce this issue on 1.10.1.  The script I used is below.  Can you run this script on  your cluster, see if it oomkills pachd, and send us any pachd logs from you can?

```
rm -rf dir-with-empty-file
mkdir dir-with-empty-file
for file in  $(seq 1 130);  do  dd  if=/dev/urandom bs=1048576 count=1  > dir-with-empty-file/$file.bin ; done
touch dir-with-empty-file/empty1.bin

pachctl delete repo test
pachctl create repo test
pachctl put file test@master -r  -f $(pwd)/dir-with-empty-file/
```

**Comment by pappasilenus** [comment] 2020-06-19 23:18
@marcadella Checking in on my request above ^^^

**Comment by pappasilenus** [comment] 2020-06-23 00:11
@sinonkt I  just reproduced this with the minio storage backend.  It looks like that may be the problem.  Can you please change your storage backend to use the Amazon driver, instead, and see if you still get the issue?  It should work fine with minio. Its only limitation is that it doesn't support S3V2 signatures.  You can even replace the storage backend on your running version of  Pachyderm.  I can guide you through this; open a ticket at pachyderm.zendesk.com.

@marcadella Can you confirm if you're using the Amazon driver or the minio driver?

@brycemcanally @jdoliner Steps to reproduce.

1. Deploy minio
2. Deploy pachyderm using the minio driver, not the Amazon one.
3. Run this script
```
rm -rf dir-with-empty-file
mkdir dir-with-empty-file
for file in  $(seq 1 130);  do  dd  if=/dev/urandom bs=1048576 count=1  > dir-with-empty-file/$file.bin ; done
touch dir-with-empty-file/empty1.bin

pachctl delete repo test
pachctl create repo test
pachctl put file test@master -r  -f $(pwd)/dir-with-empty-file/
```
4. You'll see it fail with an EOF and pachd will restart with an oomkill.

I've put pachd logs, heap profile, and debug dump  [in gdrive](https://drive.google.com/file/d/1_pmyPhL6fTORz5JSGOQdkPSUV12d2X0r/view?usp=sharing) since it's pretty big,

**Comment by pappasilenus** [comment] 2020-07-06 03:19
@sinonkt @marcadella are you able to update to using the Amazon driver?

**Comment by sinonkt** [comment] 2020-07-06 12:28
> @sinonkt @marcadella are you able to update to using the Amazon driver?

I'ven't tried yet. I'll be back around Pachyderm again when 1.11.0 release. Before migrate to new release, I'll try what you suggest and let you know. Thank you, for your workaround. :)

**Comment by sinonkt** [comment] 2020-11-06 10:15
@marcadella @pappasilenus Hi guys, I've deploy newly released 1.11.6 with 4Gi memory pachd and MINIO as STORAGE_BACKEND. but still encountered quite similar issue.

this time no zero bytes files, but just tiny images of mnist dataset around 100s of 500B file. and after 10 ~ 20 files successfully put the OOMKilled was triggered.
```
pachctl put file -r -p 2 -o mnist_raw@staging -f cv
```
![Screen Shot 2563-11-06 at 16 58 50](https://user-images.githubusercontent.com/13428859/98353289-b1a8c680-2051-11eb-9682-dedc62570f43.png)

then i try to switch to AMAZON driver by set STORAGE_BACKEND: `AMAZON`, and port `minio-*` to `amazon-*`, `custom-endpoint`.
so all amazon-bucket, amazon-distribution, amazon-id, amazon-region, amazon-secret, amazon-token, custom-endpoint were point to our minio backend. but without luck i got this errors from pachd

![Screen Shot 2563-11-06 at 17 10 56](https://user-images.githubusercontent.com/13428859/98354665-9f2f8c80-2053-11eb-9587-7e1f6608a66c.png)

**Comment by sinonkt** [comment] 2020-11-06 10:45
Oh, I just forgot to set some field in `storage-secret`and `disable-ssl`: true to match my minio backend.
```
  amazon-vault-addr: ""
  amazon-vault-role: ""
  amazon-vault-token: ""
```
these fields was not generated when i run `pachctl deploy custom --persistent-disk aws --object-store s3 ...`.

Anyway, put multiple files with AMAZON driver on MINIO backend works now :)). switch to AMAZON driver does solved a lot of issues.

**Comment by pappasilenus** [comment] 2020-11-09 19:02
@sinonkt sorry you ran into [5421](https://github.com/pachyderm/pachyderm/pull/5421), 1.11.7 fixed it.

Also good to know the Amazon driver is working for you against a minio back-end.   I'll close this issue for now, please reopen if you end up having issues that aren't pachd resource issues...

**Closed by pappasilenus** 2020-11-09 19:02 UTC
Labels: bug, reproduced, user
