### ISSUE TITLE
Explore micro k8s as minikube alternative

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3290] opened 2018-12-16 03:32 UTC
Mostly a suggestion for documentation purposes. User reported easier installation path and MUCH better performance in dev cluster mode. 

Not sure if there are other "gotchas" or limitations, but we've seen a few users asking about it so probably worth documenting.

**Comment by jdoliner** [comment] 2018-12-17 20:45
> Not sure if there are other "gotchas" or limitations

Odds are roughly 1000% that there are, but minikube is rife with gotchas and limitations too... so it might still be worth it.

**Comment by ktarplee** [comment] 2018-12-29 00:02
Just reporting my experience...  I am trying a microk8s deployment with pachyderm.  I was able to get the snap installed for microk8s.  pachctl installed without issues.  `pachctl deploy local` also completes without errors.  The pods come up and `pachctl version` works as expected (though it hung twice).  The issue is when one tries to deploy workflow all the pipeline pods fail and keep restarting.  The same workflow worked on macOS.  I am new to k8s and pachyderm so I am still trying to track down the error.  `pachctl port-forward` also does not work.

**Comment by ktarplee** [comment] 2018-12-29 16:55
Just to follow up... I did end up getting it working with microk8s.  I had an error in the worker containers.

Turns out that /var/run/docker.sock was a directory (created by k8s when the hostPath did not exist) so the check in api_server.go os.Stat("/var/run/docker.sock") returns without error but it is not a file as expected but rather a directory and then the InspectImage call (trying to use the docker daemon) fails with error: "error inspecting image ...."

On the host I had to manually correct the docker.sock as root:

```
rm -rf /var/run/docker.sock
ln -s /var/snap/microk8s/current/docker.sock /var/run/docker.sock
```

Alternatively disable docker access with `pachctl deploy local --no-expose-docker-socket`.  This will prevent binding /var/run/docker.sock into the container and then the os.Stat() should do the correct thing.  This approach changes slightly the way pipelines are run so it might cause issues.  Exposing the docker socket is probably a bad idea anyway so this might be the best bet.

**Comment by JoeyZwicker** [comment] 2018-12-30 19:40
Thanks for the writeup @ktarplee! 

@pappasilenus I believe you were exploring and documenting micro k8s as well? How far did you get and have you bee hitting similar issues?

**Comment by ktarplee** [comment] 2018-12-31 01:40
I should add that micro k8s has been really nice to work with so officially supporting it at some point is probably a good idea for pachyderm.

**Comment by ktarplee** [comment] 2019-02-07 21:17
Current error with microk8s and pachyderm 1.8.3 is 

```
export PACHD_ADDRESS=localhost:30650
kmtarplee@gpuserver:~$ pachctl version
COMPONENT           VERSION             
pachctl             1.8.3               
pachd               (version unknown) : error connecting to pachd server at address (localhost:30650): context deadline exceeded

please make sure pachd is up (`kubectl get all`) and portforwarding is enabled
```

**Comment by ktarplee** [comment] 2019-02-07 21:18
```
NAME                         READY   STATUS    RESTARTS   AGE
pod/dash-655844658b-gk2vm    2/2     Running   0          10m
pod/etcd-6b866844bd-zrmsp    1/1     Running   0          10m
pod/pachd-7cc99f4946-ncnc9   1/1     Running   0          10m

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                                 AGE
service/dash         NodePort    10.152.183.103   <none>        8080:30080/TCP,8081:30081/TCP                                           10m
service/etcd         NodePort    10.152.183.91    <none>        2379:32379/TCP                                                          10m
service/kubernetes   ClusterIP   10.152.183.1     <none>        443/TCP                                                                 35d
service/pachd        NodePort    10.152.183.167   <none>        650:30650/TCP,651:30651/TCP,652:30652/TCP,654:30654/TCP,999:30999/TCP   10m

NAME                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dash    1/1     1            1           10m
deployment.apps/etcd    1/1     1            1           10m
deployment.apps/pachd   1/1     1            1           10m

NAME                               DESIRED   CURRENT   READY   AGE
replicaset.apps/dash-655844658b    1         1         1       10m
replicaset.apps/etcd-6b866844bd    1         1         1       10m
replicaset.apps/pachd-7cc99f4946   1         1         1       10m
```

**Comment by ysimonson** [comment] 2019-02-08 16:08
I managed to get a cluster up and running. The opencv example still fails, but I think the error is due to something with microk8s itself: pods can't reach the internet, even though I made the [suggested firewall updates](https://microk8s.io/docs/).

Here's what I did:

1) Made the config changes as noted in the previous comment.
2) Exported `PACHD_ADDRESS=127.0.0.1:30650`. It still seems to work without this, but doing this will disable implicit port forwarding and get rid of those annoying error messages.
3) Ran [a reset script](https://github.com/pachyderm/pachyderm/blob/minikubeless/etc/reset.py), which rebuilds the cluster from scratch. It's been updated to support microk8s. Note that the reset script isn't in master, as it's a work-in-progress.

**Comment by ysimonson** [comment] 2019-02-08 20:52
@ktarplee [here's the script](https://github.com/pachyderm/pachyderm/blob/minikubeless/etc/reset.py) I used to rebuild everything from scratch. It destroys the cluster and rebuilds everything from scratch. Very much a work-in-progress (hence why it's not on master yet), but maybe helpful?

**Comment by ktarplee** [comment] 2019-02-10 12:08
@ysimonson I took a look at your script and I do not see the "./etc/kube/push-to-microk8s.sh" script references by the reset.py script in the repo/branch.  Did you forget to commit and push that file?

It looks like your script is primarily focused on development of pachyderm which is great.  However for a deployer/user of pachyderm I would still like to know what steps are required to get it working on microk8s.  I had it working on 1.8.1 just fine and then upgraded to 1.8.3 (this was my first upgrade) and it got really flaky.

**Comment by ktarplee** [comment] 2019-02-10 19:19
I was able to get pachyderm 1.8.3 up on microk8s.  I have to do 
```
mkdir -p ~/.kube
microk8s.kubectl config view --raw > ~/.kube/config
pachctl deploy local --no-expose-docker-socket
# silence errors
export PACHD_ADDRESS=127.0.0.1:30650
```
I had to reinstall (or maybe just a microk8s.reset would have worked) to get it working.  I was able to deploy pipelines, repos, and see some work being done.

I there is a still a major issue but I think this has nothing to do with microk8s but more likely a regression in 1.8.3.  When I run `pachctl list-job` I get an error:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/server/pps/pretty.PrintJobInfo(0x1ba8b00, 0xc0003bb1a0, 0xc00018cf00)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pps/pretty/pretty.go:55 +0x8cd
github.com/pachyderm/pachyderm/src/server/pps/cmds.Cmds.func4.2(0xc00018cf00, 0xc00018cf00, 0x0)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds.go:158 +0x40
github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client.APIClient.ListJobF(0x7f08db0895a8, 0xc0004ee038, 0x7f08db0896a8, 0xc0004ee040, 0x7f08db089770, 0xc0004ee048, 0x7f08db089808, 0xc0004ee050, 0x7f08db0898c8, 0xc0004ee060, ...)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/pachyderm/pachyderm/src/client/pps.go:276 +0x19c
github.com/pachyderm/pachyderm/src/server/pps/cmds.Cmds.func4(0x2c32d88, 0x0, 0x0, 0x0, 0x0)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pps/cmds/cmds.go:157 +0x3ee
github.com/pachyderm/pachyderm/src/server/pkg/cmdutil.RunFixedArgs.func1(0xc000291d40, 0x2c32d88, 0x0, 0x0)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/pkg/cmdutil/cobra.go:20 +0x117
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).execute(0xc000291d40, 0x2c32d88, 0x0, 0x0, 0xc000291d40, 0x2c32d88)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:572 +0x24a
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000262d80, 0xc000519106, 0x16172e0, 0xc000518d8b)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:658 +0x2cc
github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000262d80, 0x0, 0x0)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/vendor/github.com/spf13/cobra/command.go:617 +0x2b
main.main.func1(0x19761c0, 0xc0001f8700)
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:21 +0x4a
main.main()
        /home/jdoliner/go/src/github.com/pachyderm/pachyderm/src/server/cmd/pachctl/main.go:22 +0xc3
```
@ysimonson Do you see the same thing on your microk8s setup?

**Comment by ysimonson** [comment] 2019-02-10 19:31
No, though that looks like something we just fixed: https://github.com/pachyderm/pachyderm/pull/3453

**Comment by ktarplee** [comment] 2019-02-10 19:52
Awesome.  What is the easiest way to try out master?  Is there a nightly build of pachyderm I could use?

**Comment by ysimonson** [comment] 2019-02-11 15:56
The reset script is probably the best bet, but first I need to commit `push-to-microk8s.sh` (sorry about that!) I'll get that in by end of day.

**Comment by ysimonson** [comment] 2019-02-11 16:45
Fixed!

**Comment by ysimonson** [comment] 2019-02-11 16:48
@ktarplee do you still need to set `--no-expose-docker-socket`? If so, would you happen to know why?

**Comment by ktarplee** [comment] 2019-02-11 17:05
@ysimonson  The reason I had to set that flag was because microk8s does not create a /var/run/docker.sock.
Pachyderm (at least in version 1.8.1) bind mounted /var/run/docker.sock to the container.  That flag prevents it from happening.  Apparently it is not needed anyway.  Maybe that behavior has changed in pachyderm because I am not sure if it is needed anymore.

**Comment by ysimonson** [comment] 2019-02-11 17:20
That make sense. I'm making some improvements to the reset script at the moment that'll make it a bit more resilient. These improvements will be in by EOD as well.

I'd love to get your feedback on any issues you encounter with microk8s; at the moment I'm a bit limited in how much I can kick the tires with microk8s because of the aforementioned firewall issue.

**Comment by ysimonson** [comment] 2019-02-11 18:37
Changes are in. I'm still hitting firewall issues, so haven't been able to check that it's working beyond compiling and starting the cluster successfully.

**Comment by ysimonson** [comment] 2019-02-13 14:15
@ktarplee with 1.8.4 out, you should be able to run `pachctl list-job` on microk8s, without having to build from master or use the reset script

**Comment by ktarplee** [comment] 2019-02-13 18:45
I just re-tested with 1.8.4 and the flag in `pachctl deploy local --no-expose-docker-socket` is still required.  `pachctl list-job` also works now.

**Comment by gabrielgrant** [comment] 2019-02-15 19:28
@ktarplee i believe you will continue to need the `--no-expose-docker-socket` flag if the docker socket is not located in the standard location. afaik the docker socket is mostly used by pach to introspect metadata from containers (getting the user to run as is what comes to mind, but there may be more use cases i'm forgetting)

**Comment by ysimonson** [comment] 2019-06-07 18:42
Unfortunately I think microk8s support is no longer practical, at least for dev work. They removed docker support, which we're pretty tightly integrated with: https://github.com/ubuntu/microk8s/issues/382

**Comment by ysimonson** [comment] 2019-06-20 19:19
Closing due to the aforementioned issue

**Closed by ysimonson** 2019-06-20 19:19 UTC
Labels: docs, feature request
