### ISSUE TITLE
Service Pipeline shown as "running" while still pulling (worker?) image

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3082] opened 2018-07-25 18:49 UTC
**What happened?**:

Created a Jupyter service pipeline as described here: https://github.com/pachyderm/pachyderm/issues/2846#issue-314293045

pachctl immediately shows it as being in `running` state:

```
$ pachctl list-pipeline
NAME    INPUT      OUTPUT         CREATED       STATE            
jupyter testrepo:/ jupyter/master 7 minutes ago running 
```
Despite the pod having status `Init:0/1`:

```
$ kubectl get all
NAME                            READY     STATUS     RESTARTS   AGE
pod/dash-5d974d8668-jhqqt       2/2       Running    2          18h
pod/etcd-66858555cd-75v9s       1/1       Running    0          18h
pod/pachd-586cd85d4b-hcs98      1/1       Running    1          18h
pod/pipeline-jupyter-v1-sphmr   0/2       Init:0/1   0          7m

NAME                                        DESIRED   CURRENT   READY     AGE
replicationcontroller/pipeline-jupyter-v1   1         1         0         7m

NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                                   AGE
service/dash                       NodePort    10.99.79.210     <none>        8080:30080/TCP,8081:30081/TCP                             18h
service/etcd                       NodePort    10.102.220.158   <none>        2379:32379/TCP                                            18h
service/kubernetes                 ClusterIP   10.96.0.1        <none>        443/TCP                                                   23h
service/pachd                      NodePort    10.107.117.23    <none>        650:30650/TCP,651:30651/TCP,652:30652/TCP,999:30999/TCP   18h
service/pipeline-jupyter-v1        ClusterIP   10.109.159.29    <none>        80/TCP,9090/TCP                                           7m
service/pipeline-jupyter-v1-user   NodePort    10.102.120.145   <none>        30888:30888/TCP                                           7m

NAME                    DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/dash    1         1         1            1           18h
deployment.apps/etcd    1         1         1            1           18h
deployment.apps/pachd   1         1         1            1           18h

NAME                               DESIRED   CURRENT   READY     AGE
replicaset.apps/dash-5d974d8668    1         1         1         18h
replicaset.apps/etcd-66858555cd    1         1         1         18h
replicaset.apps/pachd-586cd85d4b   1         1         1         18h
```

And so obviously the port isn't isn't responding to requests yet.

Inspecting the Pod shows it to be in `ImagePullBackOff`:

```
 $ kubectl describe pod/pipeline-jupyter-v1-sphmr
Name:           pipeline-jupyter-v1-sphmr
Namespace:      default
Node:           minikube/10.0.2.15
Start Time:     Wed, 25 Jul 2018 11:33:19 -0700
Labels:         app=pipeline-jupyter-v1
                component=worker
                pipelineName=jupyter
                suite=pachyderm
                version=1.7.4
Annotations:    pipelineName=jupyter
Status:         Pending
IP:             172.17.0.7
Controlled By:  ReplicationController/pipeline-jupyter-v1
Init Containers:
  init:
    Container ID:  
    Image:         pachyderm/worker:1.7.4
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /pach/worker.sh
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:
      PPS_WORKER_IP:       (v1:status.podIP)
      PPS_POD_NAME:       pipeline-jupyter-v1-sphmr (v1:metadata.name)
      PPS_ETCD_PREFIX:    pachyderm/1.7.0/pachyderm_pps
      PPS_NAMESPACE:      default
      PPS_SPEC_COMMIT:    8f2d81642a6d44258aeb9375e55bce50
      PPS_PIPELINE_NAME:  jupyter
    Mounts:
      /pach-bin from pach-bin (rw)
      /pachyderm-storage-secret from pachyderm-storage-secret (rw)
      /scratch from pachyderm-worker (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pachyderm-token-xjkrv (ro)
Containers:
  user:
    Container ID:  
    Image:         jupyter/datascience-notebook
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /pach-bin/worker
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     0
      memory:  64M
    Environment:
      PPS_WORKER_IP:       (v1:status.podIP)
      PPS_POD_NAME:       pipeline-jupyter-v1-sphmr (v1:metadata.name)
      PPS_ETCD_PREFIX:    pachyderm/1.7.0/pachyderm_pps
      PPS_NAMESPACE:      default
      PPS_SPEC_COMMIT:    8f2d81642a6d44258aeb9375e55bce50
      PPS_PIPELINE_NAME:  jupyter
    Mounts:
      /pach-bin from pach-bin (rw)
      /pachyderm-storage-secret from pachyderm-storage-secret (rw)
      /scratch from pachyderm-worker (rw)
      /var/run/docker.sock from docker (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pachyderm-token-xjkrv (ro)
  storage:
    Container ID:  
    Image:         pachyderm/pachd:1.7.4
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /pachd
      --mode
      sidecar
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:     0
      memory:  64M
    Environment:
      BLOCK_CACHE_BYTES:  64M
      PFS_CACHE_SIZE:     16
      PACH_ROOT:          /pach
      STORAGE_BACKEND:    LOCAL
    Mounts:
      /pach from pach-disk (rw)
      /pachyderm-storage-secret from pachyderm-storage-secret (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from pachyderm-token-xjkrv (ro)
Conditions:
  Type           Status
  Initialized    False 
  Ready          False 
  PodScheduled   True 
Volumes:
  pach-bin:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  pachyderm-worker:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  pach-disk:
    Type:          HostPath (bare host directory volume)
    Path:          /var/pachyderm/pachd
    HostPathType:  
  pachyderm-storage-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pachyderm-storage-secret
    Optional:    false
  docker:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:  
  pachyderm-token-xjkrv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  pachyderm-token-xjkrv
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age              From               Message
  ----     ------                 ----             ----               -------
  Normal   Scheduled              9m               default-scheduler  Successfully assigned pipeline-jupyter-v1-sphmr to minikube
  Normal   SuccessfulMountVolume  9m               kubelet, minikube  MountVolume.SetUp succeeded for volume "pachyderm-worker"
  Normal   SuccessfulMountVolume  9m               kubelet, minikube  MountVolume.SetUp succeeded for volume "docker"
  Normal   SuccessfulMountVolume  9m               kubelet, minikube  MountVolume.SetUp succeeded for volume "pach-disk"
  Normal   SuccessfulMountVolume  9m               kubelet, minikube  MountVolume.SetUp succeeded for volume "pach-bin"
  Normal   SuccessfulMountVolume  9m               kubelet, minikube  MountVolume.SetUp succeeded for volume "pachyderm-storage-secret"
  Normal   SuccessfulMountVolume  9m               kubelet, minikube  MountVolume.SetUp succeeded for volume "pachyderm-token-xjkrv"
  Warning  Failed                 2m               kubelet, minikube  Failed to pull image "pachyderm/worker:1.7.4": rpc error: code = Canceled desc = context canceled
  Warning  Failed                 2m               kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                2m               kubelet, minikube  Back-off pulling image "pachyderm/worker:1.7.4"
  Warning  Failed                 2m               kubelet, minikube  Error: ImagePullBackOff
  Normal   Pulling                1m (x2 over 9m)  kubelet, minikube  pulling image "pachyderm/worker:1.7.4"
```

**What you expected to happen?**:

1. The pipeline to not enter `running` state until the pod is, in fact, running
2. The worker image pull to work

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

This is a fresh install, using the 1.7.4 release

**Environment?**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Pachyderm CLI version (use `pachctl version`):
```
$ pachctl version
COMPONENT           VERSION             
pachctl             1.7.4               
pachd               1.7.4         
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): minikube (`vm-driver=virtualbox`)

**Comment by gabrielgrant** [comment] 2018-07-27 02:52
FWIW same thing seems to happen when a pod is `pending` (still gets listed as `running` in Pachyderm)

Is `starting` state just not being used at all any more?

**Comment by jdoliner** [comment] 2018-07-27 03:18
Is this only for services or for normal pipelines too?

**Comment by jdoliner** [comment] 2019-06-24 21:08
Maybe we should add a deploying state to pipelines and services to cover this, so you can see that it got stuck. This is another problem that goes away if we use CRDs since users will encounter these errors themselves when they try to deploy to K8s

**Comment by ysimonson** [comment] 2020-03-05 21:19
Dupe of #2925

**Closed by ysimonson** 2020-03-05 21:19 UTC
