### ISSUE TITLE
Panic in `diff file`

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#4686] opened 2020-03-06 03:03 UTC
**What happened?**:
panic with `diff file` on an input repo after a file has been deleted.

148-64-106-156:~ joeyzwicker$ pc list file images@master^
NAME         TYPE SIZE
/46Q8nDz.jpg file 57.27KiB
/8MN9Kg0.jpg file 78.7KiB
**/Togu2RY.jpg file 87.48KiB**
/g2QnNqa.jpg file 102.4KiB
/w7RVTsv.jpg file 606.3KiB
148-64-106-156:~ joeyzwicker$ pc list file images@master
NAME         TYPE SIZE
/46Q8nDz.jpg file 57.27KiB
/8MN9Kg0.jpg file 78.7KiB
/g2QnNqa.jpg file 102.4KiB
/w7RVTsv.jpg file 606.3KiB

pachctl diff file images@master --name-only
OP NAME TYPE SIZE
panic: runtime error: index out of range [0] with length 0

goroutine 126 [running]:
github.com/pachyderm/pachyderm/src/server/pfs/cmds.forEachDiffFile(0x0, 0x0, 0x0, 0xc0000cc140, 0x1, 0x1, 0xc0007dfd90, 0xc00000e0a8, 0x4d96fa8)
	src/server/pfs/cmds/cmds.go:1487 +0x38d
github.com/pachyderm/pachyderm/src/server/pfs/cmds.Cmds.func24.1(0x2ec1180, 0xc00000e0e8, 0x0, 0x0)
	src/server/pfs/cmds/cmds.go:1147 +0x3b2
github.com/pachyderm/pachyderm/src/server/pkg/pager.Page.func1(0xc00044d768, 0x2c71270)
	src/server/pkg/pager/pager.go:25 +0x42
github.com/pachyderm/pachyderm/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0001a9140, 0xc000558100)
	vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x64
created by github.com/pachyderm/pachyderm/vendor/golang.org/x/sync/errgroup.(*Group).Go
	vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
**What you expected to happen?**:

no panic. See a red `-` with the file that was removed. 

**How to reproduce it (as minimally and precisely as possible)?**:
Steps above

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`): 1.9.12
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment] 2020-03-06 23:10
I think this is a dupe of #4577, which has already been fixed. Was this reproduced with a recent RC?

Please try to get in the habit of searching for existing issues, including closed ones, since there can be a meaningful lag between when a fix is merged into master and the issue is closed, and when it actually ships.

**Closed by jdoliner** 2020-03-06 23:10 UTC
Labels: bug

**Comment by JoeyZwicker** [comment] 2020-03-07 03:14
Yup you're right, my bad -- didn't realize it hadn't shipped in 1.9.12 but should have looked closer at that.
