### ISSUE TITLE
`pachctl run pipeline` creates no job, crashes pachd

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#4103] opened 2019-09-17 15:28 UTC
**What happened?**:

I created a branch off master in an input repo and committed files to it.   I executed `pachctl run pipeline` on the branch and no jobs were created. I executed `pachctl run pipeline` on the top commit in the branch and crashed pachd.

**What you expected to happen?**:
I expected a job to process the new data in the branch or commit.

**How to reproduce it (as minimally and precisely as possible)?**:
1. set cwd to `pachyderm/examples`
1. deploy minikube or docker-desktop k8s
1. `pachctl deploy local` 
1. `pachctl create repo images` 
1. `pachctl create pipeline -f opencv/edges.json` 
1. `pachctl create pipeline -f opencv/montage.json` 
1. `pachctl put file images@master -i opencv/images.txt`
1. `pachctl put file images@master -i opencv/images2.txt`
1. `pachctl create branch images@staging --head master`
1. `pachctl put file images@staging -i opencv/images3.txt` 
1. `pachctl list branch images`
output:
```
BRANCH  HEAD                             
staging 72edd38bba5f44d6b51122a599788594 
master  d19b4d94b65d4d5895e0047456519149 
```
1. `pachctl run pipeline edges staging`
no jobs created, no data processed
1. `pachctl run pipeline edges 72edd38bba5f44d6b51122a599788594`
pachd crashes with this error in the logs
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1f20f4d]

goroutine 5624 [running]:
github.com/pachyderm/pachyderm/src/server/pps/server.(*apiServer).RunPipeline(0xc000451d40, 0x29e59e0, 0xc00061ca50, 0xc000ab20c0, 0x0, 0x0, 0x0)
	src/github.com/pachyderm/pachyderm/src/server/pps/server/api_server.go:2606 +0x4bd
github.com/pachyderm/pachyderm/src/client/pps._API_RunPipeline_Handler.func1(0x29e59e0, 0xc00061c870, 0x2453a00, 0xc000ab20c0, 0x2453a00, 0xc000ab20c0, 0x0, 0x0)
	src/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:5936 +0x89
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1(0x29e59e0, 0xc00061c870, 0x2453a00, 0xc000ab20c0, 0xc000739b60, 0xc000739b80, 0x0, 0x0, 0x298bf60, 0xc0001970f0)
	src/github.com/pachyderm/pachyderm/vendor/github.com/opentracing-contrib/go-grpc/server.go:44 +0x9db
github.com/pachyderm/pachyderm/src/client/pps._API_RunPipeline_Handler(0x2510b20, 0xc000451d40, 0x29e59e0, 0xc00061c870, 0xc0008b57c0, 0xc00058f6e0, 0x29e59e0, 0xc00061c870, 0xc00070f980, 0x31)
	src/github.com/pachyderm/pachyderm/src/client/pps/pps.pb.go:5938 +0x158
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00039a780, 0x2a15020, 0xc000a8e600, 0xc000a74f00, 0xc000727650, 0x40a1050, 0x0, 0x0, 0x0)
	src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/server.go:998 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc00039a780, 0x2a15020, 0xc000a8e600, 0xc000a74f00, 0x0)
	src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/server.go:1278 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000711000, 0xc00039a780, 0x2a15020, 0xc000a8e600, 0xc000a74f00)
	src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/server.go:717 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/server.go:715 +0xa1
```

**Anything else we need to know?**:

**Environment?**: docker-for-desktop
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Pachyderm CLI and pachd server version (use `pachctl version`):
```
COMPONENT           VERSION             
pachctl             1.9.4               
pachd               1.9.4               
```
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): N/A
- OS (e.g. from /etc/os-release): macOS 10.14.6 (18G95)
- Others:

**Comment by JoeyZwicker** [comment] 2019-09-17 15:41
is this a dupe of #3985? @pappasilenus

**Comment by adelelopez** [comment] 2019-09-18 20:31
Fixed by https://github.com/pachyderm/pachyderm/pull/4060

**Closed** 2019-09-19 00:16 UTC
Labels: bug
