### ISSUE TITLE
updating transform doesn't allow re-processing data

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#1654] opened 2017-04-12 00:44 UTC
I'm working w a user to address #1652 

We modified the transform (specifically we added a silly echo line to the end of the `stdin` field) ... but still got the 'skipping input' message.

If we changed the name of the input repo (and added the same data) we saw it reprocess appropriately.

**Comment by jdoliner** [comment] 2017-04-12 06:37
Hmm, that's surprising to me, looking at the [code](https://sourcegraph.com/github.com/pachyderm/pachyderm@d7e4fc2366b48f3575152524fcec5e96bfce6ce1/-/blob/src/server/pkg/worker/api_server.go#L360:21-360:30) it clearly seems to be hashing the transform as part of the `HashDatum` method. @msteffen any idea what could be happening?

**Comment by msteffen** [comment] 2017-04-13 04:04
I'll talk to Sean tomorrow morning to get some more details, but I'm having a hard time reproducing this. I tested this by creating a pipeline:
```
(pipeline.json)
{
  "pipeline": {
    "name": "sum"
  },
  "transform": {
    "image": "ubuntu:14.04",
    "cmd": [ "sh" ],
    "stdin": [
        "ls /pfs/d | while read file; do",
        "   wc -l /pfs/d/${file} >/pfs/out/${file}",
        "done"
    ]
  },
  "parallelism_spec": {
    "strategy": "CONSTANT",
    "constant": 1
  },
  "inputs": [
    {
      "name": "d",
      "repo": { "name": "data" },
      "branch": "master",
      "glob": "/*"
    }
  ]
}
```
and then modified transform:
```
  "transform": {
    "image": "ubuntu:14.04",
    "cmd": [ "sh" ],
    "stdin": [
        "echo \"This is new and different\"",
        "ls /pfs/d | while read file; do",
        "   wc -l /pfs/d/${file} >/pfs/out/${file}",
        "done"
    ]
  },
```
and when I ran `pachctl create-pipeline -f pipeline.json` and then `pachctl create-pipeline pipeline2.json` it reprocessed data appropriately. I printed out the transform it was using, and a hash of just the serialized transform's bytes, and they were different between pipeline 1 and pipeline 2.

**Comment by msteffen** [comment] 2017-04-13 18:13
I just talked to Sean, and we decided to close this bug, and re-open it if we see the behavior again.

**Closed by msteffen** 2017-04-13 18:13 UTC
Labels: bug
