### ISSUE TITLE
Allow pipelines to be triggered by time/cron

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#235] opened 2016-03-26 03:12 UTC
In the scenario such as a web scraper, the first stage of the pipeline isn't triggered by data coming in. Users would want to run the scraper stage on some time frequency and then only trigger the next stages is that data is different.

**Comment by JoeyZwicker** [comment] 2017-03-17 23:23
Wanted to add a few more details here based on discussions. There are a bunch of ideas here, not all of which probably make sense to implement.

The pipeline should have a trigger struct to let users kick off a pipeline job based on time or other constraints such as amount of data or number of commits. By default, the trigger setting for a pipeline is "new input commit."

Cron/time:
This makes the most sense for pipeline with no inputs such as a scraper. Theoretically, a user could want to trigger a pipeline based on time _instead_ of per commit even when it has an input repo so this should probably override the triggering on each new input commit. 

Number of commits:
User may make frequent input commits but only want to trigger the pipeline much less frequently because of expensive "reduce" jobs. This could easily be adding files to a datum over time. Some use cases may make more sense to be expressed as time, but this also seems reasonable.

Amount of data:
Trigger the pipeline when _n_ MB of new data has come in. The use case here is less well-defined, but we had one user ask if they just streamed logs into pachyderm, they could want a pipeline to trigger after 1GB of logs as built up. 

Combinations: Would it be possible for users to specify some sort of compound trigger argument? E.g. Every 10th commit OR if it's been 24 hours since the last job. <-- seems pretty contrived, but just a thought.

**Comment by brollb** [comment] 2017-03-29 21:41
I am interested in this as well. I am currently streaming large amounts of input data and I am interested in accumulating it to update a batch clustering classifier periodically (every hour or so).

**Comment by sjezewski** [comment] 2017-03-31 21:03
duplicate of https://github.com/pachyderm/pachyderm/issues/252

**Closed by sjezewski** 2017-03-31 21:03 UTC
Labels: core-feature
