### ISSUE TITLE
Finish porting 1.3 tests to 1.4

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#1580] opened 2017-04-04 22:20 UTC
Currently about 80% of tests are ported but not all of them,

**Comment by sjezewski** [comment] 2017-05-23 19:34
Duplicate of https://github.com/pachyderm/pachyderm/issues/1486

Closing this one since the other has a bit more detail

**Closed by sjezewski** 2017-05-23 19:34 UTC
Labels: technical-debt, testing
