### ISSUE TITLE
Give a better error when you're getting firewalled.

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#147] opened 2015-09-10 20:48 UTC
Right now when a firewall blocks you the cli just hangs. We should add a timeout and print out that a firewall is likely the culprit.

**Comment by sjezewski** [comment] 2016-07-05 23:52
Not able to reproduce this behavior.

I setup a local firewall [using pf](http://blog.scottlowe.org/2013/05/15/using-pf-on-os-x-mountain-lion/) and while I validated that I was blocking all outgoing traffic (curl didn't work / intitializing portforwarding didn't work), I still couldn't get it to hang. I think we must have added a timeout on the context already. Here's the error I see:

```
$ pachctl version
COMPONENT           VERSION                                          
pachctl             1.0.1-766b799e20ce22f1cf63e4e6ee2c36a1816d27b6   
pachd               (version unknown) : error connecting to pachd server at address (0.0.0.0:30650): context deadline exceeded

please make sure pachd is up (`kubectl get all`) and portforwarding is enabled
```

I'm closing this issue. If we have a user exhibit different results behind a firewall, we'll debug from there.

**Closed by sjezewski** 2016-07-05 23:52 UTC

**Comment by jdoliner** [comment] 2016-07-05 23:55
I actually meant firewall in the other direction, google machines have a firewall up by default that will block pachctl from talking to pachd. I still think closing this is legit though because we've made the error message you get in this case a lot more descriptive.
