### ISSUE TITLE
Irregular behaviour Delete repo of a stopped pipeline

### ISSUE THREAD

**Issue by ChaiBapchya** [pachyderm/pachyderm#518] opened 2016-06-14 08:00 UTC
When we tried deleting another repository
First time, ON MY PC
```
 pachctl list-repo
NAME                CREATED             SIZE                
filter102           About an hour ago   0 B                 
test010             18 hours ago        0 B                 
data1               19 hours ago        874 B               
[root@chai /]# pachctl delete-repo test010
**rpc error: code = 5 desc = remove /pach/diff/test010/14/49818e99525343daa99eb954b6204340: no such file or directory**
```

ON SARVESH'S PC
```
 pachctl delete-repo test010
**No error**
```
Repo is deleted, since 
pachctl list-repo
Does not show the repo

When we try the other way round,
First Sarvesh tried deleting another repository (which didnt have a pipeline running)
He got the same error
```
**rpc error: code = 5 desc = remove /pach/diff/test010/14/49818e99525343daa99eb954b6204340: no such file or directory**
```
While, I tried deleting it, it got deleted without any error (**No message displayed though**)

**Comment by derekchiang** [comment] 2016-06-14 20:35
Hi @ChaiBapchya, I think we merged a patch a couple days ago that should've fixed this issue.  Is this a recent build of Pachyderm that you are running?

**Comment by ChaiBapchya** [comment] 2016-06-16 05:15
Ya, I did rebuild the pachyderm
```
go get github.com/pachyderm/pachyderm
make install
```

**Comment by jdoliner** [comment] 2016-07-11 22:47
I believe this is a duplicate of #614. Should be resolved as part of the pfs refactor.

**Closed by jdoliner** 2016-07-11 22:47 UTC
