### ISSUE TITLE
Collect more advanced metrics

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1107] opened 2016-11-29 00:38 UTC
We used to have advanced metrics that tell us the number of files, cancelled commits, etc.  It was found that those metrics were too expensive to collect (#1101) so we removed them.  However, ideally we'd still collect those metrics, but with more efficient queries (e.g. using secondary indexes).

**Comment by ysimonson** [comment] 2019-06-10 21:08
Dupe of #662

**Closed by ysimonson** 2019-06-10 21:08 UTC
