### ISSUE TITLE
Document Auth login

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#3034] opened 2018-07-06 00:50 UTC
Document login process both via CLI and Dash (and the fact that you'll need to do both). Test doing them in various orders with failures and deactivations. 

Probably also good to include CLI message when activating auth that dash login is also required. User got confused when they weren't automatically logged into the dashboard.

**Comment by JoeyZwicker** [comment] 2019-06-06 17:43
We need add okta auth docs.

**Comment by svekars** [comment] 2019-07-16 18:07
@JoeyZwicker @pappasilenus We have these sections: 

* https://docs.pachyderm.io/en/latest/auth/saml_setup.html
* https://docs.pachyderm.io/en/latest/auth/saml.html

Do we still need to add something (apart from adding these sections to the toctree) or can we close this issue?

**Comment by JoeyZwicker** [comment] 2019-07-17 00:54
Do we have docs on Auth via OAuth GitHub? Neither of the SAML docs above quite walk through the GH auth flow both in the CLI and Dash.

**Comment by pappasilenus** [comment] 2019-07-17 02:24
I haven't yet set up Okta, so I don't know what's missing. It'd be worthwhile to attempt it, at some point.

**Comment by JoeyZwicker** [comment] 2019-07-17 03:30
While testing the okta doc might be nice, we had a customer recently follow it with minimal help from us and they were successful so it’s likely ok for now. 

The other auth stuff that isn’t documented at all are my bigger concern

**Comment by svekars** [comment] 2019-07-17 03:38
@joey @jk thanks for the explanation. The issue is on my todo list. We can discuss the priority in the sprint planning meeting.

**Comment by mindthevirt** [comment] 2020-12-21 19:35
Closing since docs exist for this.

**Closed by mindthevirt** 2020-12-21 19:35 UTC
Labels: docs, priority: medium
