### ISSUE TITLE
changing contexts persists data from old context

### ISSUE THREAD

**Issue by RaananHadar** [pachyderm/pachyderm#4373] opened 2019-12-02 20:31 UTC
**What happened?**:
pachyderm contexts don't seem to work on my azure deployment

**What you expected to happen?**:
doing CRUD operations on repos in pachyderm should persist only in the active context. after deploying to a new context, i see the old context repos even deleting a repo and switching contexts would persist the changes between all contexts.

**How to reproduce it (as minimally and precisely as possible)?**:
- I have multiple pachyderm contexts on azure and one local to the computer.
- create a repo "pachctl create repo foo"
- switch context: "pachctl config set active-context differentcontext"
-list repos: pachctl list repo
repos will persist, even doing other operations such as pachctl delete all will remove everything from all contexts

**Anything else we need to know?**: nope.

**Environment?**:
- Kubernetes version (use `kubectl version`): 1.13.10 (AKS)
- Pachyderm CLI and pachd server version (use `pachctl version`): (1.9.8 for both)
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AKS and local
- OS (e.g. from /etc/os-release): my client is ubuntu 18.04.3

**Comment by ysimonson** [comment] 2019-12-09 20:36
@RaananHadar when you switched contexts, did you get any kind of error, or non-zero exit code? My suspicion is that it didn't successfully switch.

**Comment by RaananHadar** [comment] 2019-12-09 22:30
@ysimonson I didn't get any error thrown to standard output using pachctl. Is that what you meant or should an error appear to be somewhere in the logs in pachyderm or k8s?

**Comment by ysimonson** [comment] 2019-12-09 23:04
Yeah it should be from `pachctl`, albeit stderr.

**Comment by ysimonson** [comment] 2019-12-12 14:26
I think I found the root cause. It's triggered when all of these conditions hold:

1) You have a cloud deployment that you don't directly connect to.
2) You have a local deployment with pachd listening on `localhost:30650`.

In this case, when the active context is the cloud deployment, the following will occur:

1) `pachctl` will attempt to implicitly port forward (because direct connection is not enabled.)
2) Implicit port forwarding will fail because the port is already bound by the local deployment.
3) `pachctl` will continue onward since implicit port forwarding issues do not hard fail.
4) `pachctl` will connect to the local cluster.

Working on a fix for this.

**Comment by RaananHadar** [comment] 2019-12-13 12:17
Thank you this was weird indeed. I did find on some cases that the bug was 'transient' that is:
1. I'm in context a and doing a 'pachctl list repo' for example would list repos for context a
2. switching to context b -> list repos would still list context a.
3. after some time, this will list the correct repos for context b.

So indeed i'm rather certain that this has something to do with port forwarding.

**Comment by ysimonson** [comment] 2019-12-13 15:32
Fix in progress in #4416, but it's not quite ready yet. In the mean-time, there's a couple of options:

1) Setup your cloud deployment to directly connect. This requires more legwork, but it's the overall best because directly connecting brings large performance and stability benefits over port forwarding. Unfortunately, these instructions are cloud-specific and we don't have a documented way to do it in azure.
2) Run explicit port forwarding in a separate tab (`pachctl port-forward`) with the context set to the cloud deployment. This will prevent `pachctl` from running implicit port forwarding.

**Closed** 2019-12-19 00:54 UTC
Labels: bug, priority: high, user
