### ISSUE TITLE
pachctl with --help or no args generates error in beta3

### ISSUE THREAD

**Issue by tybritten** [pachyderm/pachyderm#6599] opened 2021-07-23 17:19 UTC
**What happened?**:
```
$pachctl
Access the Pachyderm API.

Environment variables:
  PACH_CONFIG=<path>, the path where pachctl will attempt to load your config.
  JAEGER_ENDPOINT=<host>:<port>, the Jaeger server to connect to, if PACH_TRACE
    is set
  PACH_TRACE={true,false}, if true, and JAEGER_ENDPOINT is set, attach a Jaeger
    trace to any outgoing RPCs.
  PACH_TRACE_DURATION=<duration>, the amount of time for which PPS should trace
    a pipeline after 'pachctl create-pipeline' (PACH_TRACE must also be set).

Error: template: top:13:47: executing "top" at <.IsHelpCommand>: can't evaluate field IsHelpCommand in type *cobra.Command
```
**What you expected to happen?**:

**How to reproduce it (as minimally and precisely as possible)?**:
run `pachctl` in beta3
**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI and pachd server version (use `pachctl version`):
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- If you deployed with helm, the values you used (`helm get values pachyderm`):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment] 2021-07-26 20:50
Looks like this was a pretty recent regression. Beta2 seems to not have this issue. A bisect should reveal what introduced this.

@Tryneus would you mind taking a look? Or reassigning to someone if you don't have bandwidth.

**Closed** 2021-07-26 22:22 UTC
Labels: 2.0.0
