### ISSUE TITLE
Awkward workflow when a pipeline outputs incorrect data but doesn't fail. (Leads to people committing manually to an output repo)

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2159] opened 2017-08-11 16:57 UTC
# Behavior

There is some reasonably confusing behavior that pops up if you commit manually to the output of a pipeline, where the output of that pipeline is the input to another pipeline.  Obviously, one might expect some weirdness here as it breaks some parentage and provenance things.  

However, we should either disallow this type of manual commit or prevent the weirdness that results.  In particular, it seems like data that is manually committed to a pipeline's output disappears after that pipeline runs again "normally."

# Steps to reproduce

Using the opencv demo, with the pipeline set up as follows:

![image](https://user-images.githubusercontent.com/4524535/29223338-3d05fb66-7e94-11e7-9f19-413edf68492f.png)

Make the following three commits (one of which commits manually to the edges output of the edges pipeline):

```
➜  opencv git:(master) ✗ pachctl put-file images master -c -f liberty.jpg 
➜  opencv git:(master) ✗ pachctl list-job
ID                                   OUTPUT COMMIT                            STARTED        DURATION           RESTART PROGRESS  DL UL STATE            
04f61d86-37f9-4557-b864-6ea62ebf2b79 montage/fa51f7d39b14422ebc5d97b6f367bea5 50 seconds ago Less than a second 0       1 + 0 / 1 0B 0B success 
cac0bbfb-b0f1-4361-bfe3-05800079f8ae edges/2bda1dd039e34ee49aa47eeb58ddf0b0   51 seconds ago 1 second           0       1 + 0 / 1 0B 0B success 
➜  opencv git:(master) ✗ pachctl put-file edges master -c -f wrench.jpg 
➜  opencv git:(master) ✗ pachctl list-job
ID                                   OUTPUT COMMIT                            STARTED            DURATION           RESTART PROGRESS  DL UL STATE            
dcae456c-9225-4165-bb5c-99717fba5078 montage/aa7a0f1fe64a486a8a7ed5e35fffcdcc 4 seconds ago      Less than a second 0       1 + 0 / 1 0B 0B success 
04f61d86-37f9-4557-b864-6ea62ebf2b79 montage/fa51f7d39b14422ebc5d97b6f367bea5 About a minute ago Less than a second 0       1 + 0 / 1 0B 0B success 
cac0bbfb-b0f1-4361-bfe3-05800079f8ae edges/2bda1dd039e34ee49aa47eeb58ddf0b0   About a minute ago 1 second           0       1 + 0 / 1 0B 0B success 
➜  opencv git:(master) ✗ pachctl put-file images master -c -f star_wars_kid.jpg 
➜  opencv git:(master) ✗ pachctl list-job
ID                                   OUTPUT COMMIT                            STARTED            DURATION           RESTART PROGRESS  DL UL STATE            
2e760b30-6b4d-468c-b719-df669e09a1fc montage/2f206dbbbc4c43d7a35b204b4ca32aac 9 seconds ago      Less than a second 0       1 + 0 / 1 0B 0B success 
f2f3c790-eedd-4d93-824a-23fc883c1379 edges/c61260d4bd014960b27b84837a6ff2c4   10 seconds ago     Less than a second 0       1 + 1 / 2 0B 0B success 
030f2676-ccb3-4662-9bf0-a532d0ae663d montage/678bbf77b0c64f50b93e61329b38b841 10 seconds ago     Less than a second 0       1 + 0 / 1 0B 0B success 
dcae456c-9225-4165-bb5c-99717fba5078 montage/aa7a0f1fe64a486a8a7ed5e35fffcdcc 44 seconds ago     Less than a second 0       1 + 0 / 1 0B 0B success 
04f61d86-37f9-4557-b864-6ea62ebf2b79 montage/fa51f7d39b14422ebc5d97b6f367bea5 About a minute ago Less than a second 0       1 + 0 / 1 0B 0B success 
cac0bbfb-b0f1-4361-bfe3-05800079f8ae edges/2bda1dd039e34ee49aa47eeb58ddf0b0   About a minute ago 1 second           0       1 + 0 / 1 0B 0B success 
➜  opencv git:(master) ✗ 
```

As can be seen, this results in four output commits in montage.  The four output commits look like the following:

![untitled drawing](https://user-images.githubusercontent.com/4524535/29223415-77ee8176-7e94-11e7-8349-7a9046871a97.png)

Most of this makes sense in terms of non-transitive pipelines.  However, it is weird that the wrench disappears from the head of montage, and thus the head of edges:

```
➜  opencv git:(master) ✗ pachctl list-commit edges
REPO                ID                                 PARENT                             STARTED             DURATION             SIZE                
edges               c61260d4bd014960b27b84837a6ff2c4   84eb3739aaa1410fac930bda8c340371   22 minutes ago      Less than a second   43.92KiB            
edges               84eb3739aaa1410fac930bda8c340371   2bda1dd039e34ee49aa47eeb58ddf0b0   23 minutes ago      Less than a second   40.57KiB            
edges               2bda1dd039e34ee49aa47eeb58ddf0b0   <none>                             24 minutes ago      Less than a second   22.22KiB            
➜  opencv git:(master) ✗ pachctl list-file edges 2bda1dd039e34ee49aa47eeb58ddf0b0
NAME                TYPE                SIZE                
liberty.png         file                22.22KiB            
➜  opencv git:(master) ✗ pachctl list-file edges 84eb3739aaa1410fac930bda8c340371
NAME                TYPE                SIZE                
liberty.png         file                22.22KiB            
wrench.jpg          file                18.34KiB            
➜  opencv git:(master) ✗ pachctl list-file edges c61260d4bd014960b27b84837a6ff2c4
NAME                TYPE                SIZE                
liberty.png         file                22.22KiB            
star_wars_kid.png   file                21.7KiB             
➜  opencv git:(master) ✗
```

**Comment by jdoliner** [comment] 2017-08-11 19:00
Talked about this offline with @JoeyZwicker. I think the easiest way to solve this is to prevent making commits to repos that don't have a provenant commit for each of the repo's provenant repos. That will make it substantially harder, although not impossible to commit directly to an output repo.

**Comment by homme** [comment] 2017-10-11 12:39
I've just discussed a workflow on Slack with @dwhitena where it would be useful to be able to manually commit to a repo that is normally the output of a pipeline, and then have downstream pipelines depending on that repo be triggered to run against those manually committed datums.

The issue is that we have a downstream pipeline run against an input repo `vrt-dataset-rasters` with a large number of datums (say 50,000) that have been generated by the upstream pipeline `list-dataset-contents` which fans out from one input datum.  The `vrt-dataset-rasters` pipeline ran successfully.  Subsequently, however, we discover that we need to re-run a few of those datums.    We obviously don't want to have to process all inputs to `vrt-dataset-rasters` again, and because the `list-dataset-contents` fans out we can't update its input to manipulate its output.  Therefore we copy the output datums that we're interested in reprocessing from `list-dataset-contents` and commit them to the `master` branch of that repo; we expect this to kick off  `vrt-dataset-rasters` to reprocess those new commits, only it doesn't.

The workaround I'm using after speaking to Daniel is to commit the datums for reprocessing to a new repo, and update the `vrt-dataset-rasters` pipeline to point to that instead of `list-dataset-contents`.  This works, but seems a bit more unwieldy in terms of workflow than it needs to be.  Unless I'm missing something...?

**Comment by jdoliner** [comment] 2017-10-11 18:54
Committing to an output repo breaks a number of Pachyderms internal assumptions about how provenance works. That's the reason that it doesn't process the data, it has no provenance which Pachyderm uses to figure out what to process. The other big issue with committing to an output repo is that if new data comes into the input repo then the committed data is going to get overwritten which will lead to very confusing results. One fairly reasonable way to do this would be to have your pipeline take 2 inputs in a union, 1 being the output repo it already takes, the other being a side repo that you can commit raw data to. That way it'll be possible to easily add data.

Long term it would be nice if there was a way to force reprocessing on particular datums, it's not immediately obvious to me how that would work with our API but I think it should be possible to get it to work.

**Comment by homme** [comment] 2017-10-11 19:47
Thanks for the update @jdoliner and your suggestion for having the pipeline take to inputs in a union is a very good one - I'll go down that route!

**Comment by dwhitena** [comment] 2017-11-20 19:29
Yeah, this cropped up again today in Slack:

> still a little confused as to the best practice in the following scenario. Have a user trying to commit changes into the output of a pipeline stage b/c:

> ```User [1:47 PM] 
> Dang, okay.  We caught an error in one of the files that we wanted to update.  The previous pipeline stage takes ~30 hours to run, and the way the glob patterns work from the initial repos would cause all of that to run again.  We were hoping to just manually fix and commit the file downstream so we wouldn't have to wait for all of the upstream pipelines to run again```

**Comment by ClaytonJY** [comment] 2017-11-20 20:00
Does a manual commit to what is normally a pipeline-populated repository _have_ to break assumptions around provenance? If one was looking for the provenance of something further downstream that depended on that manually-committed data, could the reporting/introspection tools be made to indicate that it traces back to a manual commit?

I'm not saying that isn't a ton of work, and it might not be at all worth it given what your goals for this tool are, but as an outsider it seems provenance-tracking need not be incompatible with this sort of workflow. After all, every commit to a top-level repository is a manual one.

**Comment by jdoliner** [comment] 2017-11-21 19:29
@ClaytonJY manual commits to output repos break too many of our internal assumptions. Provenance is used to figure out which data should be processed together. For example if I have a DAG like this:

```
   B
  /  \
A     D
  \  /
   C
```
Pachyderm uses provenance to make sure that `D` will only process commits from `C` and `B` that came from the same commit to `A`. Without this you get a lot of user code which crashes because it expects to be able to match things between its 2 input commits. Worse, sometimes it gives wrong answers, such as numbers getting normalized to the `[0,1]` range and winding up outside the range because the max value you're using for normalization is the max value of a different commit. Allowing output commits would require, at the very least relaxing this safety, and possibly sacrificing it all together.

The other major issue with manually committing to output directories is that the data won't actually "stick". Output commits, unlike input commits, don't inherit content from their parents. Each time we build the commit from scratch by merging together the outputs of all the datums that were processed to create it. This is why deleting an upstream datum causes its output to disappear. If we wanted to be able to allow manual output commits and keep the ability to delete a datum we'd need someway to distinguish which data is actual "output" data and which data is "faux" output data so that we could preserve the latter and not preserve the prior. This opens up a whole can of worms, you could in theory have a file that's part real output and part faux output, you can get merge conflicts between the two.

So the tl;dr is that manual commits violate far too many of our assumptions to be workable. It's not so much the implementation work, although it would be a lot of work, but more the work required to figure out all of the corner cases in how the system should actually behave. I'm not fully convinced any amount of work would get us to a sensible set of semantics for manual output commits.

**Comment by jdoliner** [comment] 2019-06-20 18:26
Closing in favor of #3773 which has a proposal for solving this type of issue.

**Closed by jdoliner** 2019-06-20 18:26 UTC
Labels: 1.7 backlog, discussion
