### ISSUE TITLE
Reuse workers for pipelines that use the same docker image

### ISSUE THREAD

**Issue by gabrielgrant** [pachyderm/pachyderm#3008] opened 2018-06-19 23:58 UTC
This is an optimization we've talked about a few times in the context of [DAG branching](https://github.com/pachyderm/pachyderm/issues/1036), but it also applies whenever a pipeline uses a generic image that can be configured with it's pipeline spec (eg. shuffling pipelines that run simple bash scripts embedded in the pipeline spec) and particularly within the context of [a set of standard, reusable pipelines](https://github.com/pachyderm/pachyderm/issues/2242)

**Comment by jdoliner** [comment] 2019-06-24 20:37
Closing, dupe of #1955.

**Closed by jdoliner** 2019-06-24 20:37 UTC
