### ISSUE TITLE
Parallelism `coefficient` use worker nodes only

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1547] opened 2017-03-31 15:11 UTC
From #users
```
 instead of creating 32 (8vcpus*4worker nodes), i see that it created 48 pods (presumably 8 vcpus * 6 nodes including the 2 edge nodes ). Any ideas about this? I think it is desirable that they would only be scheduled in the worker nodes.
```

This has been asked a few times. I think it makes sense for `coeff` to reference number of worker nodes instead of total nodes

**Comment by jdoliner** [comment] 2017-04-02 02:35
I'm a bit confused on this one, I was under the impression that when you ask k8s to list its nodes it would only return worker nodes to you. I've never seen it return anything else. Will need to confirm exactly what's going on here.

**Comment by derekchiang** [comment] 2017-04-04 01:01
Seems to be a duplicate of #1541 ?

**Comment by emk** [comment] 2017-04-09 13:13
I can confirm that "coefficient" counts the kops-created master as well as the worker nodes.

**Comment by nitinjainsj** [comment] 2020-12-14 21:46
Will be deprecated in the future.

**Closed by nitinjainsj** 2020-12-14 21:46 UTC
Labels: feature request, user
