### ISSUE TITLE
Example pipeline does not work.

### ISSUE THREAD

**Issue by teodor-pripoae** [pachyderm/pachyderm#177] opened 2016-01-12 16:49 UTC
```bash
$ pachctl create-pipeline -f grep-example/grep-example-pipeline.json
Error reading from stdin: unknown field "input_repo" in pps.CreatePipelineRequest
```

After changing example pipeline to the json below[0], the `pachctl create-pipeline -f grep-example/grep-example-pipeline.json` command runs without any output but it fails silently [1]

[0]
```
{
  "pipeline": {
    "name": "grep-example"
  },
  "transform": {
    "image": "pachyderm/grep-example",
    "cmd": [
      "/bin/grep-example.sh"
    ]
  },
  "shards": "1",
  "inputs": [
    {
      "repo": {
        "name": "data"
      }
    }
  ]
}
```

[1]
```
2016-01-12T16:25:28Z INFO  protorpclog.Call {"service":"pachyderm.pps.persist.API","method":"CreatePipelineInfo","request":"pipeline_name:\"grep-example\" transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\004data\" \u003e created_at:\u003cseconds:1452615928 nanos:345096425 \u003e ","response":"pipeline_name:\"grep-example\" transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\004data\" \u003e created_at:\u003cseconds:1452615928 nanos:345096425 \u003e ","error":"","duration":{"seconds":"0","nanos":6094069}}
2016-01-12T16:25:28Z INFO  protorpclog.Call {"service":"pachyderm.pps.PipelineAPI","method":"CreatePipeline","request":"pipeline:\u003cname:\"grep-example\" \u003e transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\004data\" \u003e ","response":"","error":"","duration":{"seconds":"0","nanos":10328074}}
2016-01-12T16:25:28Z INFO  pipeline errored: rpc error: code = 2 desc = "repo \n\x04data not found"
```

**Comment by jdoliner** [comment] 2016-01-12 23:18
Oops, that's an error that's not being propagated correctly.
Pipelines expect their input repos to exist before they're created so just do `pachctl create-repo data` before you create the pipeline.
I'll get a fix for the error not propagating merged soon.

**Comment by teodor-pripoae** [comment] 2016-01-12 23:36
I had the repo created in `/tmp/pfs` which was mounted using `pachctl mount -p /tmp/pfs`. 

I'm working right now to setup a vagrant file with everything needed for working with pfs. Is this something I can contribute ?

There were a few problems:
- I can't mount by default to `/pfs` without beeing root
- If running on osx I need to install `osx-fuse` from homebrew which looks buggy.
- Port forwarding from docker-machine does not work well: In the quickstart it is recommented to port forward host port 650 to port 30650 running inside the vm. I can't bind to this port using ssh without beeing root. If I run it as root, ssh will not work since I don't have the public/private key set up.
- After binding on another port and setting `PFS_ADDRESS` and `PPS_ADDRESS` to localhost:30650 and 30651, ssh port forward breaks gRPC connection becouse it is tcp over tcp. I had this problem while port forwarding other gRPC services too, for example youtube vitess or my own services.
- if I set `PFS_ADDRESS=192.168.99.101:30650` and `export PPS_ADDRESS=192.168.99.101:30651` in my zshrc it works and I can succesfully mount the fuse filesystem, but it does not correctly get replicated. I lost my energy at this point :disappointed: 

I'm thinking of the following solution which will help other people to get a quick start using pfs:

- Create a ubuntu machine with docker running using device-mapper
- Start kubernetes cluster automatically using upstart so it can start on machine boot
- Persist etcd, so after vm restart kubernetes starts the pods again. Currently this pods need to be created every time if cluster is running under docker-machine.
- Mount `/pfs` automatically: here I need to find a way to delay this mount on machine boot since kubernetes pods take a while to start

What do you think ?

PS. Also, after created the pipeline which silently failed, `pachctl list-pipelines` was throwing a go panic, and `pachctl delete-pipeline` was exiting cleanely but the pipeline was not deleted. Here I suspect another silent error.

**Comment by jdoliner** [comment] 2016-01-13 01:43
First, thanks so much for taking the time to write this up for us :D. It's a huge help.
Send me an email at jdoliner@pachyderm.io with your address and tshirt size and I'd love to send you some swag.

> I'm working right now to setup a vagrant file with everything needed for working with pfs. Is this something I can contribute ?

Ideally I'd like to keep developing using `docker-machine`, I've found that flow to work really well. That being said it looks like there are some annoyances that need to be dealt with here.

> I can't mount by default to /pfs without beeing root

Not super attached to this default, I think it's good for inside containers since it saves you some typing but on user machines it's cumbersome. What would be a good default for this?

> If running on osx I need to install osx-fuse from homebrew which looks buggy.

https://osxfuse.github.io/ is the best bet for this, adding it to the README.

> Port forwarding from docker-machine does not work well: In the quickstart it is recommented to port forward host port 650 to port 30650 running inside the vm. I can't bind to this port using ssh without beeing root. If I run it as root, ssh will not work since I don't have the public/private key set up.
After binding on another port and setting PFS_ADDRESS and PPS_ADDRESS to localhost:30650 and 30651, ssh port forward breaks gRPC connection becouse it is tcp over tcp. I had this problem while port forwarding other gRPC services too, for example youtube vitess or my own services.
if I set PFS_ADDRESS=192.168.99.101:30650 and export PPS_ADDRESS=192.168.99.101:30651 in my zshrc it works and I can succesfully mount the fuse filesystem, but it does not correctly get replicated. I lost my energy at this point :disappointed:

Ugh, this sounds really annoying. Really sorry you ran into this. One easy thing we can do here is make it so that `mount` looks for pfs on port 30650 by default, then you can bind w/o sudo.

I'm not sure I totally understand the TCP over TCP problem what goes wrong with that?

For the replication problem are you seeing an issue where you create a repo and the results of `ls /pfs` don't change? If so that's an issue with the OS caching results. On OSX there's a flag you can pass that prevents it but last I checked it was obfuscated by the library. We're working with the maintainer to get it punched through so we can use it which should fix the problem.

---

In general I'm in favor of having a number of having different ways to deploy, but I have a pretty strong preference that our recommended deploy be possible with just Docker, no VMs needed.

---

Regarding the panic, pb definitions are still changing kind of fast, so it's possible just rebuilding will fix it. If it happens again definitely grab the back trace for me. I can't find a way to reproduce right now.

And regarding `delete-pipelines` that one's still unimplemented :(

**Comment by teodor-pripoae** [comment] 2016-01-13 07:12
Yes, I'd prefer using `docker-machine` too, I couldn't make docker work with devicemapper in vagrant without [any](https://github.com/docker/docker/issues/15651) [bugs](https://github.com/docker/docker/issues/5684].

It looks very convenient to mount to `/pfs` when running inside docker and I think you can let like this by default but maybe there should be a message if unable to mount to this path:

```
$ pachctl mount
mkdir /pfs: permission denied

$ # proposed:
$ pachctl mount
mkdir /pfs: permission denied
If you are not running as root you can use pachctl mount -p /path/to/mount/pfs to mount it to a different directory.
```

Currently as far as I understand, `pachctl` works by sending gRPC requests to `pachctl mount` daemon. Somehow, writing multiple times to a file inside a commit duplicates the file content:

```
$ ls /tmp/pfs      # ignore this files since I'm creating a new repo:
data                  example               pipeline-grep-example
$ pachctl create-repo testrepo
$ pachctl list-repo
NAME                    CREATED             SIZE
example                 46 years ago        0 B
testrepo                46 years ago        0 B
data                    46 years ago        0 B
pipeline-grep-example   46 years ago        0 B
$ ls /tmp/pfs
data                  example               pipeline-grep-example testrepo
$ commit=$(pachctl start-commit testrepo)
$ echo $commit
7c06c56e3a544a968060415679b6da5d
$ echo foo > /tmp/pfs/testrepo/$commit/file
$ echo bar > /tmp/pfs/testrepo/$commit/file
$ echo baz > /tmp/pfs/testrepo/$commit/file
$ pachctl finish-commit testrepo $commit
$ cat /tmp/pfs/testrepo/$commit/file # bar gets duplicated
foo
bar
baz
bar
$ pachctl create-pipeline -f grep-example/grep-example-pipeline.json # changed pipeline name and repo
```

ppsd log:

```
2016-01-13T06:57:44Z ERROR protorpclog.Call {"service":"pachyderm.pps.persist.API","method":"CreatePipelineInfo","request":"pipeline_name:\"grep-example\" transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\010testrepo\" \u003e created_at:\u003cseconds:1452668264 nanos:279957078 \u003e ","response":"\u003cnil\u003e","error":"Duplicate primary key `PipelineName`:\n{\n\t\"CreatedAt\":\t{\n\t\t\"Nanos\":\t179209495,\n\t\t\"Seconds\":\t1452666254\n\t},\n\t\"InputRepo\":\t[\n\t\t{\n\t\t\t\"Name\":\t\"\\n\\u0004data\"\n\t\t}\n\t],\n\t\"PipelineName\":\t\"grep-example\",\n\t\"Shards\":\t1,\n\t\"Transform\":\t{\n\t\t\"Cmd\":\t[\n\t\t\t\"/bin/grep-example.sh\"\n\t\t],\n\t\t\"Image\":\t\"pachyderm/grep-example\",\n\t\t\"Stdin\":\t\"\"\n\t}\n}\n{\n\t\"CreatedAt\":\t{\n\t\t\"Nanos\":\t279957078,\n\t\t\"Seconds\":\t1452668264\n\t},\n\t\"InputRepo\":\t[\n\t\t{\n\t\t\t\"Name\":\t\"\\n\\btestrepo\"\n\t\t}\n\t],\n\t\"PipelineName\":\t\"grep-example\",\n\t\"Shards\":\t1,\n\t\"Transform\":\t{\n\t\t\"Cmd\":\t[\n\t\t\t\"/bin/grep-example.sh\"\n\t\t],\n\t\t\"Image\":\t\"pachyderm/grep-example\",\n\t\t\"Stdin\":\t\"\"\n\t}\n}","duration":{"seconds":"0","nanos":8113960}}
2016-01-13T06:57:44Z ERROR protorpclog.Call {"service":"pachyderm.pps.PipelineAPI","method":"CreatePipeline","request":"pipeline:\u003cname:\"grep-example\" \u003e transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\010testrepo\" \u003e ","response":"\u003cnil\u003e","error":"Duplicate primary key `PipelineName`:\n{\n\t\"CreatedAt\":\t{\n\t\t\"Nanos\":\t179209495,\n\t\t\"Seconds\":\t1452666254\n\t},\n\t\"InputRepo\":\t[\n\t\t{\n\t\t\t\"Name\":\t\"\\n\\u0004data\"\n\t\t}\n\t],\n\t\"PipelineName\":\t\"grep-example\",\n\t\"Shards\":\t1,\n\t\"Transform\":\t{\n\t\t\"Cmd\":\t[\n\t\t\t\"/bin/grep-example.sh\"\n\t\t],\n\t\t\"Image\":\t\"pachyderm/grep-example\",\n\t\t\"Stdin\":\t\"\"\n\t}\n}\n{\n\t\"CreatedAt\":\t{\n\t\t\"Nanos\":\t279957078,\n\t\t\"Seconds\":\t1452668264\n\t},\n\t\"InputRepo\":\t[\n\t\t{\n\t\t\t\"Name\":\t\"\\n\\btestrepo\"\n\t\t}\n\t],\n\t\"PipelineName\":\t\"grep-example\",\n\t\"Shards\":\t1,\n\t\"Transform\":\t{\n\t\t\"Cmd\":\t[\n\t\t\t\"/bin/grep-example.sh\"\n\t\t],\n\t\t\"Image\":\t\"pachyderm/grep-example\",\n\t\t\"Stdin\":\t\"\"\n\t}\n}","duration":{"seconds":"0","nanos":8414681}}
2016-01-13T06:57:58Z INFO  protorpclog.Call {"service":"pachyderm.pps.persist.API","method":"CreatePipelineInfo","request":"pipeline_name:\"grep-example2\" transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\010testrepo\" \u003e created_at:\u003cseconds:1452668278 nanos:719612052 \u003e ","response":"pipeline_name:\"grep-example2\" transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\010testrepo\" \u003e created_at:\u003cseconds:1452668278 nanos:719612052 \u003e ","error":"","duration":{"seconds":"0","nanos":3852347}}
2016-01-13T06:57:58Z INFO  protorpclog.Call {"service":"pachyderm.pps.PipelineAPI","method":"CreatePipeline","request":"pipeline:\u003cname:\"grep-example2\" \u003e transform:\u003cimage:\"pachyderm/grep-example\" cmd:\"/bin/grep-example.sh\" \u003e shards:1 input_repo:\u003cname:\"\\n\\010testrepo\" \u003e ","response":"","error":"","duration":{"seconds":"0","nanos":11903499}}
2016-01-13T06:57:58Z INFO  pipeline errored: rpc error: code = 2 desc = "repo \n\btestrepo not found"
```

pfsd log
```
2016-01-13T06:56:59Z INFO  protorpclog.Call {"service":"pachyderm.pfs.InternalAPI","method":"FinishCommit","request":"commit:\u003crepo:\u003cname:\"testrepo\" \u003e id:\"b123fa7293f84173adc92b9ca4fd7177\" \u003e finished:\u003cseconds:1452668219 nanos:596205987 \u003e ","response":"","error":"","duration":{"seconds":"0","nanos":32633490}}
2016-01-13T06:56:59Z INFO  protorpclog.Call {"service":"pachyderm.pfs.API","method":"FinishCommit","request":"commit:\u003crepo:\u003cname:\"testrepo\" \u003e id:\"b123fa7293f84173adc92b9ca4fd7177\" \u003e finished:\u003cseconds:1452668219 nanos:596205987 \u003e ","response":"","error":"","duration":{"seconds":"0","nanos":34046873}}
2016/01/13 06:57:14 Appends: map[.:children:<key:"file" value:true >  file:block_refs:<block:<hash:"DPkYCnZKuoY6Z7bXLwkYvBMcZ3JkLLLc5aNPCnAvlHDdwr8SXBIZixmVwjPDS0r9NGxUojNMNQqUilG26LTmtg==" > range:<upper:4 > > block_refs:<block:<hash:"zAaAjLvuBRAzGql5dBMujcKWrreVviKdBkuueEsKh6XPQoHYLoyZJxt12yFI8IoCbBpg7Zyr24ysbSQkLaxAYw==" > range:<upper:4 > > block_refs:<block:<hash:"yoCXzzisVHEYV9lrMk2vhW5Y240E9X1X_rppOvdIIn-_-u2rWqzp96YQ2XOJS9C_hLtaljbbDNhrSFzsfoE7Kw==" > range:<upper:8 > > ]
2016/01/13 06:57:14 using: block_refs:<block:<hash:"DPkYCnZKuoY6Z7bXLwkYvBMcZ3JkLLLc5aNPCnAvlHDdwr8SXBIZixmVwjPDS0r9NGxUojNMNQqUilG26LTmtg==" > range:<upper:4 > > block_refs:<block:<hash:"zAaAjLvuBRAzGql5dBMujcKWrreVviKdBkuueEsKh6XPQoHYLoyZJxt12yFI8IoCbBpg7Zyr24ysbSQkLaxAYw==" > range:<upper:4 > > block_refs:<block:<hash:"yoCXzzisVHEYV9lrMk2vhW5Y240E9X1X_rppOvdIIn-_-u2rWqzp96YQ2XOJS9C_hLtaljbbDNhrSFzsfoE7Kw==" > range:<upper:8 > >
2016/01/13 06:57:14 returning: file:<commit:<repo:<name:"testrepo" > id:"b123fa7293f84173adc92b9ca4fd7177" > path:"file" > file_type:FILE_TYPE_REGULAR size_bytes:16 modified:<seconds:1452668219 nanos:596205987 > commit_modified:<repo:<name:"testrepo" > id:"b123fa7293f84173adc92b9ca4fd7177" >
2016-01-13T06:57:14Z INFO  protorpclog.Call {"service":"pachyderm.pfs.InternalAPI","method":"GetFile","request":"file:\u003ccommit:\u003crepo:\u003cname:\"testrepo\" \u003e id:\"b123fa7293f84173adc92b9ca4fd7177\" \u003e path:\"file\" \u003e size_bytes:16 ","response":"","error":"","duration":{"seconds":"0","nanos":7933837}}
2016-01-13T06:57:14Z INFO  protorpclog.Call {"service":"pachyderm.pfs.API","method":"GetFile","request":"file:\u003ccommit:\u003crepo:\u003cname:\"testrepo\" \u003e id:\"b123fa7293f84173adc92b9ca4fd7177\" \u003e path:\"file\" \u003e size_bytes:16 ","response":"","error":"","duration":{"seconds":"0","nanos":8808770}}
2016-01-13T06:57:58Z INFO  protorpclog.Call {"service":"pachyderm.pfs.InternalAPI","method":"CreateRepo","request":"repo:\u003cname:\"pipeline-grep-example2\" \u003e ","response":"","error":"","duration":{"seconds":"0","nanos":5120}}
2016-01-13T06:57:58Z INFO  protorpclog.Call {"service":"pachyderm.pfs.API","method":"CreateRepo","request":"repo:\u003cname:\"pipeline-grep-example2\" \u003e ","response":"","error":"","duration":{"seconds":"0","nanos":1989055}}
2016-01-13T06:57:58Z ERROR protorpclog.Call {"service":"pachyderm.pfs.InternalAPI","method":"ListCommit","request":"repo:\u003cname:\"\\n\\010testrepo\" \u003e commit_type:COMMIT_TYPE_READ block:true ","response":"\u003cnil\u003e","error":"repo \n\u0008testrepo not found","duration":{"seconds":"0","nanos":59402}}
2016-01-13T06:57:58Z ERROR protorpclog.Call {"service":"pachyderm.pfs.API","method":"ListCommit","request":"repo:\u003cname:\"\\n\\010testrepo\" \u003e commit_type:COMMIT_TYPE_READ block:true ","response":"\u003cnil\u003e","error":"rpc error: code = 2 desc = \"repo \\n\\btestrepo not found\"","duration":{"seconds":"0","nanos":2517764}}
```

Regarding tcp over tcp, I tried again now and it looks to work for pachctl mount and maybe I was missing something last night, I can't reproduce anymore. Nevermind about tcp over tcp, I think this is happening only if I tunnel the traffic over a ssh socks socket.

**Comment by teodor-pripoae** [comment] 2016-01-13 07:19
`pachctl list-pipeline` is returning a panic:

```
pachctl list-pipeline
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x15f5d5]

goroutine 1 [running]:
github.com/pachyderm/pachyderm/src/pps/pretty.PrintPipelineInfo(0x2043028, 0xc82010e800, 0xc82017b400)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/src/pps/pretty/pretty.go:38 +0x435
github.com/pachyderm/pachyderm/src/pps/cmds.Cmds.func6(0x10f5cd0, 0x0, 0x0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/src/pps/cmds/cmds.go:226 +0x3ea
github.com/pachyderm/pachyderm/vendor/go.pedge.io/pkg/cobra.RunBoundedArgs.func1(0xc820249000, 0x10f5cd0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/pkg/cobra/pkgcobra.go:25 +0xb0
github.com/pachyderm/pachyderm/vendor/github.com/spf13/cobra.(*Command).execute(0xc820249000, 0x10f5cd0, 0x0, 0x0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/github.com/spf13/cobra/command.go:572 +0x869
github.com/pachyderm/pachyderm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc820126400, 0xc820249000, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/github.com/spf13/cobra/command.go:662 +0x54e
github.com/pachyderm/pachyderm/vendor/github.com/spf13/cobra.(*Command).Execute(0xc820126400, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/github.com/spf13/cobra/command.go:618 +0x2d
main.do(0x7aa3a0, 0xc82015c5a0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/src/cmd/pachctl/main.go:118 +0x7a7
github.com/pachyderm/pachyderm/vendor/go.pedge.io/env.Main(0xd42750, 0x7aa3a0, 0xc82015c5a0, 0x0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/go.pedge.io/env/env.go:46 +0x1ff
main.main()
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/src/cmd/pachctl/main.go:37 +0x74

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [chan receive]:
github.com/pachyderm/pachyderm/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x10cc300)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/github.com/golang/glog/glog.go:882 +0x67
created by github.com/pachyderm/pachyderm/vendor/github.com/golang/glog.init.1
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/github.com/golang/glog/glog.go:410 +0x297

goroutine 22 [select]:
github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc.(*Conn).transportMonitor(0xc820252000)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/clientconn.go:452 +0x417
github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc.NewConn.func1(0xc820252000)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/clientconn.go:291 +0x1b5
created by github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc.NewConn
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/clientconn.go:292 +0x4ab

goroutine 24 [select]:
github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport.(*http2Client).controller(0xc8202383c0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport/http2_client.go:812 +0x5d8
created by github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport/http2_client.go:193 +0x1536

goroutine 25 [IO wait]:
net.runtime_pollWait(0x2042be0, 0x72, 0xc820012210)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82011ad80, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82011ad80, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82011ad20, 0xc8201794f4, 0x9, 0x9, 0x0, 0x15a0050, 0xc820012210)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200fc2f8, 0xc8201794f4, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
io.ReadAtLeast(0x2042cc8, 0xc8200fc2f8, 0xc8201794f4, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:298 +0xe6
io.ReadFull(0x2042cc8, 0xc8200fc2f8, 0xc8201794f4, 0x9, 0x9, 0xc82023f2c8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:316 +0x62
github.com/pachyderm/pachyderm/vendor/golang.org/x/net/http2.readFrameHeader(0xc8201794f4, 0x9, 0x9, 0x2042cc8, 0xc8200fc2f8, 0x20000000, 0x0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/golang.org/x/net/http2/frame.go:227 +0xa5
github.com/pachyderm/pachyderm/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc8201794d0, 0x0, 0x0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/golang.org/x/net/http2/frame.go:372 +0xe6
github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc82023f230, 0x0, 0x0, 0x0, 0x0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport/http_util.go:450 +0x3d
github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport.(*http2Client).reader(0xc8202383c0)
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport/http2_client.go:742 +0x115
created by github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport.newHTTP2Client
	/Users/toni/code/gopath/src/github.com/pachyderm/pachyderm/vendor/google.golang.org/grpc/transport/http2_client.go:199 +0x1595
```

**Comment by derekchiang** [comment] 2016-06-01 00:28
We now have new examples: https://github.com/pachyderm/pachyderm/tree/master/examples/fruit_stand

**Closed by derekchiang** 2016-06-01 00:28 UTC
