### ISSUE TITLE
Pachyderm on GKE won't deploy on the first try

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1620] opened 2017-04-07 14:20 UTC
Using 1.4.1 or 1.4.2, Pachyderm doesn't seem to deploy on the first try to GKE.  That is, I deploy with the normal Google settings (as outlined here http://docs.pachyderm.io/en/latest/deployment/google_cloud_platform.html), and `etcd` get into a crash loop backoff.  However, when I run `pachctl undeploy` and then run the same deploy command again, everything comes up as expected.

This is extremely reproducible for me. I can't say it has happened every time (I don't remember to be honest), but I can't remember the last time I deployed to GKE without this happening (with 1.4+).

**Comment by JoeyZwicker** [comment] 2017-04-07 15:33
This seem similar to what @gabrielgrant  could have been hitting yesterday although he wasnt able to get it to come up either after undeploy and redeploy. 

We should look into this asap.

**Comment by jdoliner** [comment] 2017-04-07 20:53
I just tried this and it worked for me first try. I've deployed on GKE several times over the last few days and I've yet to see this issue. I think there might be some flakiness around kubernetes attaching drives to machines, unfortunately I'm not quite sure what we can do to fix that. I think it's a bit more reliable if you use dynamically allocated drives rather than statically allocated.

**Comment by JoeyZwicker** [comment] 2017-04-07 21:10
@dwhitena is there anything else we can look at to try to figure out if this is just flakeiness of truly reproducible? What was the error you were getting? Was it about the pvc not being mounted correctly? That's what @gabrielgrant was getting and I want to make sure they're the same.

**Comment by dwhitena** [comment] 2017-04-07 21:14
@jdoliner, were you deploying with dynamic volumes every time?  I was using manual volumes every time and it happens every time for me. For me it can be reproduced by following our docs for Google deploys exactly.  That is what I have been doing.  etcd will just sit there is crash backoff until you undeploy and redeploy.  Then it works like a charm.

**Comment by jdoliner** [comment] 2017-04-07 21:52
@dwhitena I normally use dynamic volumes but I just tried with static volumes and that worked for me too. The only thing I did that was a little different from the docs was I did `--dry-run` so I could manually edit the image name because `pachctl` installed via `make install` outputs weird image names with uuid in them. But this shouldn't really change the behavior.

**Comment by dwhitena** [comment] 2017-04-07 21:54
@jdoliner not really sure what I'm doing different then.  The only other variables are region, volume size, etc.

**Comment by dwhitena** [comment] 2017-04-07 21:56
@jdoliner I am away from my laptop now, but I will try again on Monday and document the whole thing better.

**Comment by dwhitena** [comment] 2017-04-10 13:38
@jdoliner  and @JoeyZwicker, I tried this again with 1.4.3 and the cluster deployed on the first try.  I guess I will just bring this up again if/when I see it again.  Maybe 1.4.3 fixed this, maybe it is intermittent, or maybe @gabrielgrant has a way to reproduce?

**Comment by derekchiang** [comment] 2017-04-10 21:35
Closing for now until we can reproduce this issue.

**Closed by derekchiang** 2017-04-10 21:35 UTC
Labels: deployment, high priority
