### ISSUE TITLE
list-datum hangs everything

### ISSUE THREAD

**Issue by suneeta-mall** [pachyderm/pachyderm#3102] opened 2018-08-02 05:08 UTC
**What happened?**:
Trying to find what datums have failed in job is not easy. 
- `list-datum` does not provide any filter to list only a subset of datum .. useful case of failed datum. @jdoliner mentioned that list will automatically push top datums as failed ones so that might be enough. But this interface can be slightly more 'filtery' may be 
- A job with 16K datum, fails to list datum even with request of just page 1. 
`pachctl list-datum d0f2c827b1344cdfbec30b4401db9bf9 --page 1`
It does not did not take forever to return but also caused dashboard to hang. Killing this request resurrected everything. 

**What you expected to happen?**:
-  list-datum to return results without hang

**How to reproduce it (as minimally and precisely as possible)?**:

**Anything else we need to know?**:

**Environment?**:
- Kubernetes version (use `kubectl version`):
- Pachyderm CLI version (use `pachctl version`): 1.7.4
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s):
- OS (e.g. from /etc/os-release):
- Others:

**Comment by jdoliner** [comment] 2018-08-02 18:05
This is due to `list-datum` doing an in memory sort to make sure it returns the failed datums first. This can be fixed by converting it to a streaming model.

**Comment by echohack** [comment] 2021-04-05 17:40
This is a duplicate of #5835 

Also note that failed datums can be queried directly from stats as so:

```shell
pachctl glob file <pipeline>@stats:/*/failure

NAME TYPE SIZE
/ff66317d7d460b10fa733c7b5f07b372d84deced1d8f2d93334aa9bd02bed34a/failure file 15B
/ff774fc235996a33b059cb705833dc719d96a9a2a584aac3d2acb42584c52750/failure file 15B
/ff7f9777e485e5fc22fc32322295c4e65f33b142fe9102cc41db82074833c475/failure file 15B
/ff83cf36e1d61f648265423536faf048b868ef8f2afe5d5f411534b1f93cb8a1/failure file 15B
```

I'm closing this issue as a duplicate.

**Closed by echohack** 2021-04-05 17:40 UTC
