### ISSUE TITLE
Pipelines with cron input do not overwrite the contents of their output repo

### ISSUE THREAD

**Issue by brendoncarroll** [pachyderm/pachyderm#6467] opened 2021-07-02 22:04 UTC
Each cron tick has a separate datum, and so we never actually overwrite the file for the tick.

This pipeline can be used to reproduce.
```json
{
    "pipeline": {
        "name": "a"
    },
    "description": "Cron squash test",
    "transform": {
        "image": "debian:stable",
        "cmd": ["/bin/bash"],
        "stdin": ["ls -Rv /pfs > /pfs/out/ls.txt"]
    },
    "input": {
        "cron": {
            "name": "tick",
            "spec": "@every 10s"
        }
    }
}
```

```
pachctl list file a@master:
```
Each of the output commits for this pipeline produces a version of `ls.txt` with a different tag.

We expected to see a single `ls.txt ` in the commit `a@master` with a single tag.

**Comment by brendoncarroll** [comment] 2021-07-02 23:11
@brycemcanally pointed out that this is the documented behavior in 1.x
https://docs.pachyderm.com/latest/concepts/pipeline-concepts/pipeline/cron/

Maybe we should consider changing the default.  In 1.x this pipeline would concatenate to `ls.txt` but in 2.x it will create a new (path, tag) for every commit.

**Comment by jdoliner** [comment] 2021-07-06 18:20
This seems to be working as intended. `cron` inputs have an `overwrite` field which will give you the behavior you're describing. Closing since I don't think there's anything to fix here, feel free to reopen if I missed something.

**Closed by jdoliner** 2021-07-06 18:20 UTC
