### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [pachyderm/pachyderm#5847] opened 2021-03-18 12:47 UTC
[jw@cn05 pachyderm]$ sudo make VERBOSE=1 -j$(nproc)
# GOPATH/bin must be on your PATH to access these binaries:
go install -ldflags "-X github.com/pachyderm/pachyderm/v2/src/version.AdditionalVersion=-35eb75a25336e0ad9c7466919a600ece51d246a0" -gcflags ""all=-trimpath="" ./src/server/cmd/pachctl

go: cloud.google.com/go/storage@v1.3.0: unrecognized import path "cloud.google.com/go/storage": https fetch: Get "https://cloud.google.com/go/storage?go-get=1": dial tcp: lookup cloud.google.com: no such host
make: *** [Makefile:54: install] Error 1
[jw@cn05 pachyderm]$

**Comment by actgardner** [comment] 2021-03-18 15:43
Hi @LutzWeischerFujitsu - this looks like a DNS issue, your build machine isn't able to resolve `cloud.google.com`. That's a little outside of what we can troubleshoot in Github issues. We also don't support ARM builds (yet), so you may run into other problems.

**Comment by echohack** [comment] 2021-03-18 16:06
Thanks for opening this issue! As @actgardner said above, we don't intend to support this platform at this time. I'm closing this issue to reflect that. Thanks for using Pachyderm!

**Closed by echohack** 2021-03-18 16:06 UTC
Labels: user

**Comment by LutzWeischerFujitsu** [comment] 2021-04-26 12:12
I retried fresh and get now this error, which doesn't look CPU-specific: 

[jw@cn05 pachyderm]$ sudo make VERBOSE=1 -j$(nproc)
# GOBIN (default: GOPATH/bin) must be on your PATH to access these binaries:
go install -ldflags "-X github.com/pachyderm/pachyderm/v2/src/version.AdditionalVersion=-e464bc33164dbaf4448624d1b555bfe31307d534" -gcflags ""all=-trimpath="" ./src/server/cmd/pachctl
go: github.com/crewjam/saml@v0.4.4-0.20201214083806-0dd2422c212e: invalid pseudo-version: tag (v0.4.3) found on revision 0dd2422c212e is already canonical, so should not be replaced with a pseudo-version derived from that tag
make: *** [Makefile:42: install] Error 1
[jw@cn05 pachyderm]$ echo $GOPATH
/usr/local/go/bin:/home/jw/.sdkman/candidates/groovy/current/bin:/home/jw/.sdkman/candidates/gradle/current/bin:/opt/FJSVstclanga/default/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/opt/FJSVstclanga/default/bin:/home/jw/go/bin
[jw@cn05 pachyderm]$

**Comment by jrockway** [comment] 2021-04-26 15:13
I re-ran that command with my existing `~/go/pkg` module cache and it ran fine.  From that error, it appears that an upstream dependency did some git force pushes of tags, but rerunning with `~/go/pkg` moved out of the way (and therefore getting all modules fresh) I couldn't reproduce the problem.  I ran with `GOARCH=arm64` as well as my default `GOARCH=amd64` and both builds succeeded.  I suspect that your local cache of go modules is outdated in some way; it wouldn't hurt to move it out of the way, `mv ~/go/pkg ~/go/pkg2`, and to try rebuilding.

Of note is that the commit you're building from is for Pachyderm 2.x, which is not currently released.  If you want to build an ARM pachctl that will work with an existing deployed cluster, you'll want to check out a release tag like `v1.13.0` and build from there.

**Comment by LutzWeischerFujitsu** [comment] 2021-04-28 06:46
Did 'mv ~/go/pkg ~/go/pkg2', than 'make', but get still this error.

**Comment by jrockway** [comment] 2021-04-28 16:14
Sorry to hear that.  These look like module resolution problems, and I can't reproduce them on `go version go1.16.3 linux/amd64`.  I've successfully built (via cross-compiling) an arm64 binary and it succeeded.  I have a PR open to create binary arm64 client releases in the future: https://github.com/pachyderm/pachyderm/pull/6021.  I looked at the code and we rely on the fact that `int` == `int64`, so 32-bit ARM releases probably aren't going to happen in the near future.  And, for the server-side components, we just aren't set up to validate those releases, so we aren't planning on building them right now.

If you end up figuring out how to fix this, please let me know.  I'd be happy to review a PR that improves the arm situation.  Thank you for taking a look!

**Comment by LutzWeischerFujitsu** [comment] 2021-04-29 06:50
I cross-checked on x86 and get assembler errors, starting on 'github.com/minio/sha256-simd'. 
I do 'yum golang, git, and sudo make'.
