### ISSUE TITLE
pachyderm stops responding after trying to delete a running pipeline

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#650] opened 2016-07-12 22:12 UTC
Through some magic combination of deleting pipelines and their corrisponding repos one can get pachyderm into a state where it no longer responds to requests relating to repos. It cannot (for example) list-repo any longer.

**Comment by jdoliner** [comment] 2016-07-12 23:00
@JonathanFraser real sorry you hit this. My hypothesis on this is that it's related to the pfs state locking, we've had issues like this in the past although hadn't seen them in a while.
I think this issue is likely to be fixed by #641, however we should also expand our test suite to include lots more deletions and recreations of pipelines and repos.

**Comment by sjezewski** [comment] 2016-09-06 21:48
This may have been caused by the other PFS hang. Since we don't have a way to reproduce this, I'm closing for now.

**Closed by sjezewski** 2016-09-06 21:48 UTC
Labels: bug, pfs_refactor
