### ISSUE TITLE
[put-file] Bug when uploading big datasets

### ISSUE THREAD

**Issue by jonandernovella** [pachyderm/pachyderm#1548] opened 2017-03-31 16:09 UTC
Using v 1.4. When pushing a relatively big data-set (5Gb only)  to a repo with the recursive flag, the process fails. The executed command is the following:

`pachctl put-file metabrepo master -c -r -f . 
transport is closing`

I tested it with a smaller subset with the same kind of files, and it worked.

**Comment by dwhitena** [comment] 2017-03-31 16:47
+1

**Comment by jdoliner** [comment] 2017-04-02 02:31
`transport is closing` normally indicates that the pachd process encountered an error or that there was some error with a connection such as a port-forward breaking. Unfortunately this might prove hard to diagnose without logs from pachd from when the error happened. @jonandernovella has this error proven to be reproducible?

**Comment by derekchiang** [comment] 2017-04-04 00:59
@jonandernovella could you describe your infrastructure?  Are you doing the `put-file` remotely or in the same cluster?  I've put many multi-GB files with no issues on AWS from within the cluster.

**Comment by dwhitena** [comment] 2017-04-05 16:56
Ok, I was able to reproduce this @derekchiang and @jdoliner with 239Mb of images recursively uploading to a GKE cluster with Pachyderm 1.4.1.

```
➔ pachctl put-file training master -c -r -f .
transport is closing
```

I'm doing this remotely, so @derekchiang are you saying I should try from within the cluster?  Or maybe I upload to a bucket and then put-file from there?

**Comment by dwhitena** [comment] 2017-04-05 18:30
I've tried a couple different things here as well.  I uploaded all my files to my object store, got URLs for each of the files, and tried to `put-file` with `-i`, thinking that would be better.  Also, I killed my port-forward and manually set `ADDRESS`, but still:

```
➔ 
➔ pachctl create-repo training
➔ pachctl put-file training master -c -i maps.txt 
transport is closing
➔ pachctl list-repo
NAME                CREATED             SIZE                
training            8 minutes ago       0 B                 
➔ 
```

So, I guess we can rule out port-forward?

**Comment by dwhitena** [comment] 2017-04-05 19:54
Ok, now I tried this from an instance in the same region as my cluster (because there are some weird settings on the instances in my GKE cluster, and I couldn't quickly get `pachctl` up and running).  But, alas, the same:

```
dwhitena@put-file:~/maps/train$ pachctl create-repo training
dwhitena@put-file:~/maps/train$ pachctl put-file training master -c -r -f .
transport is closing
```

**Comment by dwhitena** [comment] 2017-04-05 20:09
This seems to be related to the actual number of files and/or how long it takes to upload them.  The above attempt was with 1097 images.  If I take out a sample of around 200 images:

```
dwhitena@put-file:~/maps/train/sample$ pachctl put-file training master -c -r -f .
dwhitena@put-file:~/maps/train/sample$ 
```

Success!  So, this definitely seems to be reproducible as the number and/or size of the files increases.

**Comment by derekchiang** [comment] 2017-04-06 00:26
@dwhitena @jonandernovella could you guys try using a lower parallelism, like `-p 10`?  The default is 100 and I wonder if that's too much.

**Comment by jonandernovella** [comment] 2017-04-06 08:21
@dwhitena @derekchiang yes, that definitely works.

**Comment by derekchiang** [comment] 2017-04-06 23:29
@jonandernovella Great.  We will lower the default parallelism to 10 in the next release.

**Closed** 2017-04-07 00:42 UTC
Labels: bug, high priority, users-channel
