### ISSUE TITLE
Stuck in bad auth state

### ISSUE THREAD

**Issue by jdoliner** [pachyderm/pachyderm#5018] opened 2020-06-17 22:37 UTC
**What happened?**:

On a hub cluster I somehow got myself stuck in a bad state with auth that seems to prevent me from doing things with pipelines. Here's the terminal log:

```
➜  pachyderm git:(gpt_upgrade) ✗ pachctl update pipeline -f examples/ml/gpt-2/train.json --reprocess
robot:account-8 is not authorized to perform this operation on the repo train, must have at least WRITER access
➜  pachyderm git:(gpt_upgrade) ✗ pachctl delete repo train
robot:account-8 is not authorized to perform this operation on the repo train, must have at least OWNER access
➜  pachyderm git:(gpt_upgrade) ✗ pachctl list repo
NAME    CREATED      SIZE (MASTER) ACCESS LEVEL 
tweets  27 hours ago 68.93KiB      OWNER        Output repo for pipeline tweets. 
queries 27 hours ago 9B            OWNER                                         
➜  pachyderm git:(gpt_upgrade) ✗ pachctl delete repo train
robot:account-8 is not authorized to perform this operation on the repo train, must have at least OWNER access
➜  pachyderm git:(gpt_upgrade) ✗ fg
[1]  - 12022 continued  nvim examples/ml/gpt-2/tweets.py

[1]  + 12022 suspended  nvim examples/ml/gpt-2/tweets.py
➜  pachyderm git:(gpt_upgrade) ✗ pachctl update pipeline -f examples/ml/gpt-2/train.json --reprocess
robot:account-8 is not authorized to perform this operation on the repo train2, must have at least WRITER access
➜  pachyderm git:(gpt_upgrade) ✗ pachctl create repo test
➜  pachyderm git:(gpt_upgrade) ✗ pachctl list repo                                                  
NAME    CREATED       SIZE (MASTER) ACCESS LEVEL 
test    6 seconds ago 0B            OWNER                                         
tweets  27 hours ago  68.93KiB      OWNER        Output repo for pipeline tweets. 
queries 27 hours ago  9B            OWNER                                         
➜  pachyderm git:(gpt_upgrade) ✗ pachctl update pipeline -f examples/ml/gpt-2/train.json --reprocess
➜  pachyderm git:(gpt_upgrade) ✗ pachctl auth whoami
You are "robot:account-8"
session expires: 16 Jul 20 12:34 PDT                                                                  
```

**Comment by msteffen** [comment] 2020-08-14 14:43
@jdoliner This is quite old, but do you happen to recall if, when you've run into this, you might've been using `create repo --update`? That was the issue with python pipelines, and those should be fixed by https://github.com/pachyderm/pachyderm/pull/5193.

I'm closing this issue because the error from `create_python_pipeline` is the closest I've been able to come to reproducing it, and that's fixed. If we encounter this issue again we should repoen it

**Closed by msteffen** 2020-08-14 14:43 UTC
Labels: bug
