### ISSUE TITLE
Remove visibility of inaccessible objects

### ISSUE THREAD

**Issue by sjezewski** [pachyderm/pachyderm#3174] opened 2018-10-04 18:38 UTC
If a user does not have access to a repo/pipeline, it should not be visible in the dash for that user.

**Comment by gabrielgrant** [comment] 2018-10-04 20:33
I don't think this is just a dash issue, it's an API-level change, and I think it's covered by #2434, right?  (that's where we've been tracking this feature in the context of other auth changes)

**Comment by jdoliner** [comment] 2018-10-04 23:12
I think it's probably not even a dash level change at all, we don't want these objects to be accessible through the API or pachctl either.

**Comment by ysimonson** [comment] 2019-06-12 00:18
Dupe of #2434

**Closed by ysimonson** 2019-06-12 00:18 UTC
