### ISSUE TITLE
create a standard pachctl docker image

### ISSUE THREAD

**Issue by pappasilenus** [pachyderm/pachyderm#5058] opened 2020-06-30 19:33 UTC
**What is the goal / desired outcome?**

To enable CI/CD of my pipelines, I would like a standard pachctl docker image so that I don't have to build and maintain one myself.

**If there is a way to accomplish this today via workaround, what does that require?**

Building an image myself

**(Optional) What is your proposal for a feature to solve this?**

A standard docker image that's updated every version.

**Comment by JoeyZwicker** [comment] 2020-06-30 23:01
dupe of #3446?

**Comment by pappasilenus** [comment] 2020-06-30 23:43
GitHub search sucks

--
John Karabaic
gpg key available at hkp://keys.gnupg.net
513.295.6365

**Comment by ysimonson** [comment] 2020-07-01 13:59
Closing as dupe of #3446

**Closed by ysimonson** 2020-07-01 13:59 UTC
Labels: feature request
