### ISSUE TITLE
2.0.0-alpha.10 - Auth - `pachctl undeploy` and nuclear K8s reset both kept the enterprise status ACTIVE

### ISSUE THREAD

**Issue by nadegepepin** [pachyderm/pachyderm#5930] opened 2021-04-02 19:08 UTC
**What happened?**:

1. After auth activation -> undeploy Pachyderm or reset K8s then re-deploy: `pachctl deploy local`
2. `pachctl list pipeline` -> No auth token - please login
3. `pachctl auth login` -> Bad request - invalid client_id("pachd"0
4. `pachctl enterprise get-state` -> ACTIVE
 It looks like Enterprise stayed ON with NO root token.

**Comment by actgardner** [comment] 2021-04-05 13:43
This is an issue with `pachctl undeploy` with minikube on OS X - we store cluster state in a hostpath, and when the persistent volume is deleted and recreated the data remains in the same path in the minikube VM. The only fix is to restart the VM or delete the data from within `minikube ssh`.

I'll see if I can come up with a fix for this since it seems like it'll mostly affect auth users.

**Comment by jdoliner** [comment] 2021-06-14 20:35
I think this might be the intended behavior. In general `pachctl undeploy` doesn't delete data unless you pass it the `-a` flag. I'm not sure if the `-a` flag will work on minikube though due to the `hostpath` issue that @actgardner described but I think without `-a` this is expected.

**Comment by actgardner** [comment] 2021-06-29 19:36
Closing this, running `pachctl undeploy --metadata` does seem to clean up the host path data, and pachctl deploy/undeploy is deprecated in favour of helm.

**Closed by actgardner** 2021-06-29 19:36 UTC
Labels: 2.0.0
