### ISSUE TITLE
commits outputting incorrect data

### ISSUE THREAD

**Issue by JonathanFraser** [pachyderm/pachyderm#296] opened 2016-04-13 23:15 UTC
I'm getting strange data out of the series of commits thats difficult to describe, so I'll just pastebucket the command [history](http://pastebucket.com/279578).

**Comment by jdoliner** [comment] 2016-04-13 23:27
@JonathanFraser sorry you ran into this, that is some strange output. I'm going to take a crack at reporting this locally and see if I can figure out what's going on. Will report back.

**Comment by JonathanFraser** [comment] 2016-04-13 23:35
and it just go weirder, I did a cat again on the file, without any additional commits and got a larger output
`jfraser@ubunutVirt:/pfs/test$ cat a01f9e808b41461c9516fb29637a3f49/a
1
2
3
2
4
2
3
2
5
2
3
2
4
2
3
2`

**Comment by jdoliner** [comment] 2016-04-13 23:37
What happens if you do `pachctl get-file test a01f9e808b41461c9516fb29637a3f49 a`? I'm wondering if maybe the fuse layer is doing something weird.

**Comment by JonathanFraser** [comment] 2016-04-13 23:38
@jdoliner same output

**Comment by jdoliner** [comment] 2016-04-14 00:25
Alright I got this working locally, I think what's going on here is that the semantics of the `>` operator in shell don't quite play nice with our fuse layer. The command `echo 3 > ...` sends the `PutFile` request to pachd with the data `3\n2\n`... very strange.

@tv42 any ideas why we'd see this behavior? My guess is that we might need to make our fuse layer open files in a non seekable mode but that's just a guess.

**Comment by jdoliner** [comment] 2016-04-14 00:29
For the time being, I think the easiest way to sidestep this problem would be to just use `pachctl` for loading data.

**Comment by tv42** [comment] 2016-04-14 01:40
Shell `echo a >f` is just a `Setattr` for truncating and then `Write` at offfset 0. Seekability doesn't really enter that picture.. perhaps you're not handling the truncate right?

That you're getting a write error there means your fuse handlers are returning errors. What, why? Is this because of the write-only nature of your open commits? Is it actually write-once?

The data being corrupted, especially the repeating 2 in `1232`, almost must be something in the storage backend (the handling of the sharded blocks?).

You can see tons more debug by enabling debug in https://godoc.org/bazil.org/fuse/fs#Config or https://godoc.org/bazil.org/fuse#Debug

**Comment by JonathanFraser** [comment] 2016-04-14 16:30
@jdoliner sure, but for the containers running partial jobs how does that work?

**Comment by JonathanFraser** [comment] 2016-04-14 17:17
I'm also getting this error is a decrease the pachd replicas down to 1.

**Comment by JonathanFraser** [comment] 2016-04-14 19:08
@tv42 I'm pretty sure this is in fuse and has to do with the reusing of the message buffers, these strange values are being handed directly to the files Write method.

**Comment by tv42** [comment] 2016-04-14 19:13
@JonathanFraser Show me.

**Comment by jdoliner** [comment] 2016-04-14 19:19
For containers using pachctl isn't a great option, we're going to try to get these fuse bugs worked out asap.

> I'm also getting this error is a decrease the pachd replicas down to 1.

Little confused by what this means, would you mind clarifying?

@tv42 Yup seekability doesn't come into this, my mistake. I think it's likely we're not handling the truncate properly. I've got a test that exposes this error and I'm going to turn on debugging to see if it shows what we want it to.

**Comment by JonathanFraser** [comment] 2016-04-14 19:27
This could be a misinterpretation of what I understand should happen but I put a log entry followed by a panic into the Write which is called directly by the fuse bindings
[data](http://pastebucket.com/281728)
This report is in response to echo 5 > file
Although its entirely possible I might be missing something.

**Comment by jdoliner** [comment] 2016-04-14 19:36
Alright here's the output:
[out.txt](https://github.com/pachyderm/pachyderm/files/219816/out.txt)

This is from a test that does:

```
StartCommit
echo 1 >
echo 2 >
FinishCommit
StartCommit
echo 3 >
```

the weird part is the second write has the data `3\n2\n` rather than the expected `3\n`.

This test is available in the issue_270 branch (there's enough overlap between this issue and 270 that I'm working on both in the same place). It's called `Test296`.

**Comment by JonathanFraser** [comment] 2016-04-14 19:42
Looking into fuse.go when generating the Write request there is an explicit check that the buffer is not less than in.Size but it doesn't seem to care that it might be larger.

**Comment by tv42** [comment] 2016-04-14 21:06
@jdoliner Looks like the file wasn't truncated, only overwritten. The `3\n` goes on top of the `1\n`.

**Comment by tv42** [comment] 2016-04-14 21:07
And the `2\n` goes after the `1\n`, not overwriting, because at that point the kernel still knows the file contents; the FinishCommit thing probably flushes that out.

**Comment by jdoliner** [comment] 2016-04-14 21:47
@tv42 I'm kind of confused I think you're saying that the kernel is storing the contents of the file and thinks that the `echo 3 >...` should result in the file having the contents `3\n2\n` but that seems weird because isn't the expect after that command that the file will just contain `3\n`.

Is there anything we can do to get it so that the kernel sends us that write `3\n` instead of what we're getting now?

**Comment by JonathanFraser** [comment] 2016-04-14 21:53
The kernel holding on to it also seems weird because from the perspective of the file-system I'm writing to a new distinct file each time (as seen [here](http://pastebucket.com/282120)).

**Comment by tv42** [comment] 2016-04-14 21:56
Okay now there's multiple scenarios in flight, this gets confusing.

**Comment by tv42** [comment] 2016-04-14 22:01
Here are the facts:

- you are using page cache backed files (no `fuse.OpenDirectIO` visible); that means kernel writes a page at a time
- `file.Setattr` is not implemented, hence truncation does not do anything
- your `file.Write` does not pass `request.Offset` to the `pfsclient.Putfile`, hence the storage backend thinks all writes are appends

This combination results in the kernel page cache contents differing from what your storage backend thinks they are.

**Comment by jdoliner** [comment] 2016-04-14 22:17
What's the correct way to set `fuse.OpenDirectIO` I'm noticing that in my `Open` callback the response object is `nil` I feel like I must be missing something kind of obvious here.

**Comment by tv42** [comment] 2016-04-14 22:30
`resp` is `nil` in your `Open` handler? I find that very hard to believe. Show me.

Here's an example using `fuse.OpenDirectIO`:

```go
func (f *myFile) Open(ctx context.Context, req *fuse.OpenRequest, resp *fuse.OpenResponse) (fs.Handle, error) {
        resp.Flags |= fuse.OpenDirectIO
        ...
}
```

**Comment by jdoliner** [comment] 2016-04-14 22:45
Whoops, I figured it out I was doing something pretty silly.

I just tried setting `fuse.OpenDirectIO` and that seems to fix the problem.

**Comment by JonathanFraser** [comment] 2016-04-14 22:56
@jdoliner does it also fix it for test [script](http://pastebucket.com/282120).

**Comment by jdoliner** [comment] 2016-04-14 23:06
@JonathanFraser yup!! just ran it

**Comment by JonathanFraser** [comment] 2016-04-14 23:28
@jdoliner huh, ok because at no point was I writing to same file twice and yet DirectIO fixed it. Glad it's fixed but damned if I understand why.

**Comment by jdoliner** [comment] 2016-04-19 23:03
Update on this. We have a PR fixing this in review.
We've also added a regression test for this issue: `Test296`

**Comment by jdoliner** [comment] 2016-04-21 21:59
Fix for this has been merged into master.
Thanks for bearing with us while we got it dealt with and don't hesitate to reopen if there are other unexpected quirks in the behavior.

**Closed by jdoliner** 2016-04-21 21:59 UTC
