### ISSUE TITLE
port-forward is flaky

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#1440] opened 2017-03-18 02:06 UTC
I've been able to repro consistently on v1.3 and v1.4 so it must be something else with my setup. @dwhitena Can you repro since you're the only other one who uses minikube as regularly as me? 

Port-forward seems to work successfully, but after about ~60 seconds the connection dies. Setting export ADDRESS seems to work fine.
Either:
a) it's a problem with my setup (perhaps the new generation of macbook pro?) and we should to debug that. I can set ADDRESS manually for demos, but this might be something others hit and we should know why. 
b) it's a problem with minikube v0.17.1 and we need to update our docs and beginner guides to warn people and/or work them around it. 

```
Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ kc get all
NAME               READY     STATUS    RESTARTS   AGE
po/etcd-rxp08      1/1       Running   0          15m
po/pachd-7cq11     1/1       Running   3          15m
po/rethink-w8z7p   1/1       Running   0          15m

NAME         DESIRED   CURRENT   READY     AGE
rc/etcd      1         1         1         15m
rc/pachd     1         1         1         15m
rc/rethink   1         1         1         15m

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)                                          AGE
svc/etcd         10.0.0.119   <none>        2379/TCP,2380/TCP                                15m
svc/kubernetes   10.0.0.1     <none>        443/TCP                                          1h
svc/pachd        10.0.0.8     <nodes>       650:30650/TCP,651:30651/TCP                      15m
svc/rethink      10.0.0.246   <nodes>       8080:32080/TCP,28015:32081/TCP,29015:31818/TCP   15m

NAME                                    DESIRED   SUCCESSFUL   AGE
jobs/bf681a76a66d38c2e9dabcf42be90d86   1         1            4m
jobs/pachd-init                         1         1            15m
Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ minikube version
minikube version: v0.17.1
Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ pc port-forward &
[1] 11694
Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ Port forwarded, CTRL-C to exit.

Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ pc version
COMPONENT           VERSION
pachctl             1.3.16
pachd               1.3.16
Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ E0317 19:03:47.757160   11699 portforward.go:175] lost connection to pod
E0317 19:03:47.830873   11699 portforward.go:269] error creating error stream for port 30650 -> 650: EOF
E0317 19:03:47.830935   11699 portforward.go:269] error creating error stream for port 30650 -> 650: EOF
E0317 19:03:47.830972   11699 portforward.go:269] error creating error stream for port 30650 -> 650: EOF
E0317 19:03:47.831005   11699 portforward.go:269] error creating error stream for port 30650 -> 650: EOF
E0317 19:03:47.831036   11699 portforward.go:269] error creating error stream for port 30650 -> 650: EOF
Joseph-Zwickers-MacBook-Pro:pachyderm joeyzwicker$ kc get all
NAME               READY     STATUS    RESTARTS   AGE
po/etcd-rxp08      1/1       Running   0          20m
po/pachd-7cq11     1/1       Running   3          20m
po/rethink-w8z7p   1/1       Running   0          20m

NAME         DESIRED   CURRENT   READY     AGE
rc/etcd      1         1         1         20m
rc/pachd     1         1         1         20m
rc/rethink   1         1         1         20m

NAME             CLUSTER-IP   EXTERNAL-IP   PORT(S)                                          AGE
svc/etcd         10.0.0.119   <none>        2379/TCP,2380/TCP                                20m
svc/kubernetes   10.0.0.1     <none>        443/TCP                                          1h
svc/pachd        10.0.0.8     <nodes>       650:30650/TCP,651:30651/TCP                      20m
svc/rethink      10.0.0.246   <nodes>       8080:32080/TCP,28015:32081/TCP,29015:31818/TCP   20m

NAME                                    DESIRED   SUCCESSFUL   AGE
jobs/bf681a76a66d38c2e9dabcf42be90d86   1         1            9m
jobs/pachd-init                         1         1            20m
```

**Comment by dwhitena** [comment] 2017-03-20 17:15
@JoeyZwicker I'm unable to reproduce this on:

- Pachyderm 1.3
- Ubuntu 16.04
- minikube 0.17.1

I can bring up port-forward and it stays good for 10+ minutes at least.  I haven't tested 1.4 yet.  However, it doesn't appear to be across the board with minikube 0.17.1.  

I think we should definitely add a note to the docs however about manually setting ADDRESS.

**Comment by JoeyZwicker** [comment] 2017-03-20 17:25
sigh -- must be something with my computer then. I can add to the docs.

On Mon, Mar 20, 2017 at 10:15 AM, Daniel Whitenack <notifications@github.com

**Comment by jdoliner** [comment] 2017-04-04 21:57
Moving this to 1.5 milestone, port-forward seems to have been having a lot of issues in general in newer versions of kubernetes. Unfortunately I'm not sure exactly what we can do about this, we should look into it more and try to document things better, maybe in the worst case if it's become completely unreliable we should just remove the functionality.

**Comment by JoeyZwicker** [comment] 2017-10-20 21:44
port-forward is still a cause of flakiness in general. Leaving open because I'd love to not have this, but we don't have any real proposals in place.

**Comment by bpb** [comment] 2017-10-23 15:27
Just some context as to how I'm using port-forward and mount that might shift paradigm of usage of these commands.

I have the wrapper bash scripts called _pachyderm_connect_, _pachyderm_disconnect_, and a combination called _pachyderm_reconnect_.  

_pachyderm_connect_ polls kubectl get all to ensure that etcd is up and running and pachd is up and running. If they are port-forward and mount get created with _nohup_ and _&_ pipeing the stdout to separate log files. Otherwise we wait until etcd and pachd are up.

_pachyderm_disconnect_ deletes the pfs mount and forces a dismount if unsuccessful and deletes the mount path. It then kills all kubectl and pachctl portforwarding processes and deletes the log files. 

_pachyderm_reconnect_ basically runs pachyderm_disconnect followed by pachyderm_connect.

These wrapper scripts have effectively eliminated connectivity issues and concerns. I just run the reconnect script every time I open a new terminal or get a network disconnect.

I can post these scripts here if you guys find this helpful.

**Comment by sjezewski** [comment] 2018-02-08 23:43
Yea, I have something similar, where it kills the old port forward command, issues a new one, and then issues whatever api call you're making. 

Ideally we bake this into the go client though.

**Comment by hchauvin** [comment] 2018-02-27 14:52
Hi, my two cents, while I'm evaluating Pachyderm :) For reasons I cannot understand, doing a port forward using kubectl is more flaky for me than doing it directly using k8s.io/client-go/tools/portforward, so I have a tool that does that directly.

This is also the approach taken by Helm: it needs a port forward to access the Tiller server, and it does so not through kubectl but directly in Go.  This is a good starting point.

Moreover, it is possible not only to have a port forward in the background but to do as they do: just forward the remote port to a random local port each time the pachctl client is invoked, the user won't see the difference in terms of performance.

**Comment by jdoliner** [comment] 2018-02-28 00:25
@hchauvin thanks for the good information here. I think making a `port-forward` each time we want to make a request would actually be a really nice improvement.

**Comment by ysimonson** [comment] 2019-01-22 16:43
We follow the same approach as Helm now. Maybe this is good to close?

**Closed** 2019-06-06 17:37 UTC
Labels: docs
