### ISSUE TITLE
Replace satori/uuid with gofrs/uuid

### ISSUE THREAD

**Issue by kevindelgado** [pachyderm/pachyderm#3897] opened 2019-07-09 20:51 UTC
Our current uuid package is no longer maintained and we should switch to using the community fork that is maintained (see https://github.com/satori/go.uuid/issues/84)

**Comment by jdoliner** [comment] 2019-07-09 21:03
Agree with this, dupe of #3044 though so closing.

**Closed by jdoliner** 2019-07-09 21:03 UTC
