### ISSUE TITLE
Error on Incremental Cron Jobs

### ISSUE THREAD

**Issue by jiaqi216** [pachyderm/pachyderm#2762] opened 2018-03-12 17:12 UTC
**What happened?**:
When attempting to run an Incremental Cron Job, I'm getting this error

```
"failed to process datum with error: error getting parent for datum [file_info:<file:<commit:<repo:<name:\"mapr-scraper_input\" > id:\"fd1d084701284c10945615e06f6c6f34\" > path:\"/time\" > file_type:FILE size_bytes:26 hash:\"\\237\\275\\373un\\201\\334<_\\255\\373\\324i\\2632\\342\\254\\307\\340Dw\\2250\\025\\371\\346\\322\\030Cu\\266\\020\" > parent_commit:<repo:<name:\"mapr-scraper_input\" > id:\"314acd04f65d46f08dc249a2b50ee324\" > name:\"input\" branch:\"master\" ]: tagGetter: tag 159f1a93cd1af769ce2fd5bbd31edbab689cd82ee0961f60c67639d109398103fc2a not found"
```

**What you expected to happen?**:
The non-incremental cron job works fine but the incremental version of the same pipeline fails

**How to reproduce it (as minimally and precisely as possible)?**:
On our cluster - running any incremental cron job 
example pipeline config

```
{
  "pipeline": {
    "name": "mapr-scraper"
  },
  "transform": {
    "cmd": [
      "curl https://raw.githubusercontent.com/pachyderm/pachyderm/master/doc/examples/word_count/Dockerfile > file_$(date +%s)"
    ]
  },
  "egress": {
    "URL": "s3://btn-pachyderm-staging-egress/mapreduce/scraper_out"
  },
  "input": {
    "cron": {
      "name": "input",
      "spec": "@every 30s"
    }
  },
  "incremental": true
}
```

**Anything else we need to know?**:

the DL and UL of the incremental cron job is always 0B even though the DL of the non-incremental cron job seems to be 26B (or something to indicate the `time` file was downloaded)

```
DL       UL       STATE 
0B       0B       failure 
```

**Environment?**:
- Kubernetes version (use `kubectl version`): v1.8.6
- Pachyderm CLI version (use `pachctl version`): 1.6.7
- Cloud provider (e.g. aws, azure, gke) or local deployment (e.g. minikube vs dockerized k8s): AWS
- OS (e.g. from /etc/os-release):
- Others:

**Comment by dwhitena** [comment] 2018-03-12 17:18
Thanks for this info @jiaqi216. I seem to remember from Slack that you also tried this with 1.7.0rc, but that didn't solve the problem. Can you confirm?

**Comment by jiaqi216** [comment] 2018-03-12 17:24
I did not try this in 1.7.0rc. I encountered this issue with
```
COMPONENT           VERSION
pachctl             1.6.9
pachd               1.6.9
```
and
```
COMPONENT           VERSION
pachctl             1.6.9
pachd               1.6.7
```

**Comment by dwhitena** [comment] 2018-03-12 17:32
@jiaqi216 Are you able to try this on 1.7.0rc2? I only mention this because the commit structure for jobs changed somewhat in 1.7, and this could be a non-issue. Just want to confirm. I was running 1.7.0rc2 when I tried to reproduce, and I didn't see the issue.

**Comment by jiaqi216** [comment] 2018-03-12 17:44
@dwhitena do you mean 1.7 for the pachd version or pachctl version?

**Comment by dwhitena** [comment] 2018-03-12 17:53
@jiaqi216 Both should match, so you would need to do the following (if possible, depending on what you need to save from the cluster etc.):

1. undeploy your 1.6.x cluster with `pachctl undeploy`
2. upgrade `pachctl` to 1.7.0rc2
3. deploy a 1.7.0rc2 cluster with the upgraded `pachctl`
4. Try the pipeline again.

You will also be able to migrate automatically without the undeploy for the actual 1.7.0 release, but the above would be what you should do for now with the RC.

**Comment by jdoliner** [comment] 2019-06-21 18:24
We no longer have incremental pipelines so there's no way we can repro this issue. I addition most of the underlying code has been rewritten since 1.6 so it's unlikely that the bug is still there in a form similar to what's described here. Closing this, feel free to reopen if you're hit something similar to this again.

**Closed by jdoliner** 2019-06-21 18:24 UTC
Labels: user
