### ISSUE TITLE
Incremental reduce not parenting output commits properly

### ISSUE THREAD

**Issue by JoeyZwicker** [pachyderm/pachyderm#597] opened 2016-06-28 16:39 UTC
While running the fruit stand demo and using generate.go, some outputs in the Sum repo show up as not having parents. 
<img width="914" alt="screen shot 2016-06-28 at 9 29 54 am" src="https://cloud.githubusercontent.com/assets/1795008/16424201/05c88e56-3d14-11e6-918e-34e34f8b0088.png">

Seems fairly random as I was generating commits in 10-100 commit increments.

**Comment by sjezewski** [comment] 2016-09-07 18:01
Hmm I'm seeing a different bug that seems related.

I ran through the fruit-stand, and everything looked normal. Output commits from pipeline worked fine.

Then I ran the generate script:

```shell
$go run examples/fruit_stand/generate/generate.go 
```

And I see a bunch of commits on the data repo:

```shell
$ pachctl list-commit data
BRANCH                             ID                                 PARENT                             STARTED             FINISHED            SIZE                
master                             35d7476b4f8540a48323a01a6a79802c   2175158356f84421b1b460e950ce5b7b   11 seconds ago      10 seconds ago      863 B               
master                             2175158356f84421b1b460e950ce5b7b   28d07f999a864bddb553fcf7167d0015   11 seconds ago      11 seconds ago      863 B               
master                             28d07f999a864bddb553fcf7167d0015   cb0a94fa5a0b493599886230c01ff581   11 seconds ago      11 seconds ago      872 B               
master                             cb0a94fa5a0b493599886230c01ff581   9719744873d34067bf0de78141fc64a0   11 seconds ago      11 seconds ago      866 B               
master                             9719744873d34067bf0de78141fc64a0   37035da60a5a43169869945437f6b960   12 seconds ago      12 seconds ago      866 B               
master                             37035da60a5a43169869945437f6b960   8fb102b7b7ff4927a7ef656de8a4a5df   12 seconds ago      12 seconds ago      868 B               
master                             8fb102b7b7ff4927a7ef656de8a4a5df   ee7fc238e26d4312b5b22546aaa6e889   12 seconds ago      12 seconds ago      870 B               
master                             ee7fc238e26d4312b5b22546aaa6e889   f9af7b21342147e383363c0d040c5a2f   13 seconds ago      13 seconds ago      875 B               
master                             f9af7b21342147e383363c0d040c5a2f   fcd208e19e9d4dc2812c9565cd6967b9   13 seconds ago      13 seconds ago      865 B               
master                             fcd208e19e9d4dc2812c9565cd6967b9   6a8d09045bf24eae99183a6128ec73b2   13 seconds ago      13 seconds ago      867 B             
```

But no new ones on the sum repo:

```shell
$ pachctl list-commit sum
BRANCH                             ID                                 PARENT                             STARTED             FINISHED            SIZE                
17570ca4af614a869d45f9210c998c4d   a39d43799aea440b9a60052902a1891f   91a7f4d930884beb90b140c641ddf56c   9 minutes ago       9 minutes ago       12 B                
17570ca4af614a869d45f9210c998c4d   91a7f4d930884beb90b140c641ddf56c   <none>                             21 minutes ago      21 minutes ago      12 B 
```

**Comment by jdoliner** [comment] 2016-09-07 18:36
@sjezewski hmm my hunch is that this is a different bug. It looks like for some reason the pipeline isn't triggering when it should be. It'd be nice to have this as part of the test suite. Maybe it's time we get the fruit stand demo running as part of CI.

**Comment by sjezewski** [comment] 2016-09-07 21:40
That seems reasonable. As the person who tried to do the Fancy Thing and parse the fruitstand walkthrough to run the commands ... thats more trouble than its worth. If we add a test we should just have an integration test that does the steps in the walkthrough. We'll just have to keep that in sync.

**Comment by derekchiang** [comment] 2016-09-07 23:03
An update.  Seems like the issue that @sjezewski was seeing was just Pachyderm/Kubernetes being slow.  After all, hundreds of containers are created if you run the generate script.  I just tried and the pipelines do complete successfully after a while.

I will take a look and see if @JoeyZwicker 's issue still exists.

**Comment by sjezewski** [comment] 2016-09-08 00:07
Another data point

When trying to reproduce via CLI by doing `pachctl start-commit data master`

I see a commit in the `data` repo, but no corresponding commits in `filter` or `sum`

**Comment by jdoliner** [comment] 2016-09-08 00:23
@sjezewski you did `pachctl finish-commit data master` too right?

**Comment by derekchiang** [comment] 2016-09-09 08:37
Turns out there were a couple bugs in PPS/PFS that together caused this issue.  Not going into the details here, but the issue has been fixed on the refactor branch.

**Closed by derekchiang** 2016-09-09 08:37 UTC
Labels: bug, pfs_refactor
