### ISSUE TITLE
Error: Received message larger than max (4210693 vs. 4194304)

### ISSUE THREAD

**Issue by kalugny** [pachyderm/pachyderm#1774] opened 2017-05-02 14:23 UTC
Hi,
I've stumbled on this when trying to d/l a large file using `pypachy`.
```
<_Rendezvous of RPC that terminated with (StatusCode.RESOURCE_EXHAUSTED, Received message larger than max (4210693 vs. 4194304))>
```

Reading about it a bit and looking at the code seems to indicate that it's something to do with `grpc` where there's a mismatch between the client's `max response size` and the server.
Also, it seems that there's no way to set the client's `max response size` for the python `grpc` client.

Do you know anything about this?
Thanks!

**Comment by jdoliner** [comment] 2017-05-05 19:19
@kalugny we've hit similar thing with the go client. Normally I've seen this with sending messages that are too big. Is it possible that what you're seeing is from the server returning that error rather than the client? Also just to confirm this is happening on a call to `PutFile`, if so it seems unlikely to me that the problem is the size of the response because `PutFile` has an empty response.

**Comment by kalugny** [comment] 2017-05-06 11:49
It's a `GetFile` request, though

**Comment by jdoliner** [comment] 2017-05-12 20:10
I see, perhaps we should add a way for requests to specify what the largest response size they can accept is? Is that number easily available to you on the sender side?

**Comment by kalugny** [comment] 2017-05-17 16:51
From what I could gather, the limit is on the server side.

**Comment by ysimonson** [comment] 2019-06-10 21:41
Possible dupe of #1280?

**Comment by marcadella** [comment] 2019-11-04 08:41
Happened to me regularly with `pachctl delete`. This is a really annoying as I am stuck with pipelines I cannot delete and have to delete everything manually in minio and re-deploy my pipelines...

**Comment by ysimonson** [comment] 2020-03-05 14:13
GetFile now handles this appropriately. There are other endpoints that can still send or receive messages that are too large, but there's separate issues for them.

**Closed by ysimonson** 2020-03-05 14:13 UTC
