### ISSUE TITLE
Document IDE installation instructions for enterprise 

### ISSUE THREAD

**Issue by chainlink** [pachyderm/pachyderm#6878] opened 2021-09-15 20:57 UTC
The current plan is to install Jupyterhub along side Pachyderm. The best example of this is what we do in Hub, but this needs to be documented for on prem enterprise customers.

**Comment by avigil** [comment] 2021-09-22 16:52
closed as a duplicate of #6882

**Closed** 2021-09-22 16:52 UTC
Labels: docs, helm
