### ISSUE TITLE
Make job's progress more visible

### ISSUE THREAD

**Issue by derekchiang** [pachyderm/pachyderm#1622] opened 2017-04-07 18:46 UTC
We should show how many datums have been processed, how many datums have failed to be processed, etc.  That way a user won't look at a running job and wonder if it's their code that's taking so long or if there's some internal failures going on.

**Comment by jdoliner** [comment] 2017-04-07 20:08
dupe of #1588, I copied over the labels

**Closed by jdoliner** 2017-04-07 20:08 UTC
Labels: core-feature, high priority
